### ISSUE TITLE
Craft CDF China Presence

### ISSUE THREAD

**Issue by caniszczyk** [cdfoundation/foundation#1]
We should leverage the LF China team and setup a contract to get CDF support. This involves registering CDF related project WeChat handles and maintaining their social presence. We should also setup the agreement so they handle membership management in China, similar to CNCF.

**Comment by kimsterv** [comment]
Budget was approved for $5k / month for 6 months. Board is requesting quarterly reports as part of the contract.

**Comment by danlopez00** [comment]
@kimsterv the reporting is a great value-add to the contract retainer.

**Comment by danlopez00** [comment]
The approved budget was communicated with the team and Jacque has been added to the conversation and planning.

**Comment by danlopez00** [comment]
Response from Wayne and team:

- Dan please send a formal email to me stating CDF’s intention to work with LF APAC on behalf of the governing board, with stated terms and within the normal LF.Org and LF.APAC agreement (commission structure, etc). LF Exec management confirms an email is fine to kick off. Just state the start date (which I suggest as OCT 1st 2019) and duration for the 6 months.
- Then I suggest we have a (or multiple) training calls with our team.  We can set these up for week of Sept 30th.   HK time zone during this week.
- Please send us any/all materials and links to the same so we can begin to review these.
- Please send any/all PPT’s and documentation you have so we can begin to review these and translate them into Chinese as well.

**Comment by kimsterv** [comment]
Dan, did these action items get taken care of? If not, let's create a new issue to do so or leave this one open.

**Comment by danlopez00** [comment]
yes, closing.
