### ISSUE TITLE
Digicert validation is holding up Code Signing

### ISSUE THREAD

**Issue by danlopez00** [cdfoundation/foundation#105]
re: #10 
Digicert is asking to validate the project series LLC https://www.digicert.com/ssl-certificate-purchase-validation.htm

Per @olblak
- tried to request one with my own credit card, and my request staid pending for a little bit more than a week without further notification then I canceled when I discovered that I should use the CDF credit card but I can't use it either.
  >> This is due to required org validation. nothing on your end. also, please use the corp card on file

Could we plan a zoom session to move this issue forward?
   >> This is scheduled

**Comment by danlopez00** [comment]
Call with Digicert management, supporting legal documentation provided to Digicert by LF Legal

**Comment by danlopez00** [comment]
Request from vendor for signed docs from LF atty. Working on that now

**Comment by danlopez00** [comment]
Documentation provided to vendor from LF Legal

**Comment by olblak** [comment]
Is there any news on this?

**Comment by danlopez00** [comment]
This is resolved. Please open new tickets regarding specifics
