### ISSUE TITLE
Create a service desk page similar to CNCF's

### ISSUE THREAD

**Issue by kimsterv** [cdfoundation/foundation#107]
https://github.com/cncf/servicedesk
We don't have all these things in place yet, but we have a few! Let's start with all the things we do provide for members/projects and expand this page as needed.

**Comment by danlopez00** [comment]
@kimsterv this is in progress. we may want to consider Jira, but lets sync up on it

**Comment by danlopez00** [comment]
A service desk should require a definition of services available such as https://www.cncf.io/services-for-projects/

**Comment by caniszczyk** [comment]
@danlopez00 please don't use a JIRA or service desk, just this foundation github for project support, it's working well to keep everything transparent (i.e., https://github.com/cdfoundation/foundation/issues/10)

I recommend just taking advantage of what LF AI put together which is simpler and work with that: https://lfai.foundation/services-for-projects/

**Comment by danlopez00** [comment]
We will keep Github issues and posted this page: https://cd.foundation/project-services/

If we need to tweak the content of that page, we can open a new ticket to triage
