### ISSUE TITLE
Set up salesforce for CDF members

### ISSUE THREAD

**Issue by kimsterv** [cdfoundation/foundation#11]
We need a way to see CDF members and contact details, companies that are in the pipeline, etc

**Comment by kimsterv** [comment]
I think Dan said we'd use Saleforce CRM to track members.

**Comment by caniszczyk** [comment]
We have sf.cd.foundation that's available for internal LF. I think the solution here is to get a monthly report out of SF and send it to the gb list or some specific mailing list for people that care :)

**Comment by kimsterv** [comment]
How do we view the pipeline of interested parties and their status? I'd like to get more transparency into the entire process and see how the GB can help influence new members. Who are the inbound requests going to? How are they tracked? What are other foundations doing to track memberships and prospective members?

**Comment by caniszczyk** [comment]
All inbound member requests should be routed to info@cd.foundation where a program manager will pick it up and take them through a call/presentation to answer any questions.

The best thing the GB and other members can do is make intros.

@danlopez00 is working to get a report of the pipeline from SFDC, ideally that can be just sent to the GB list monthly or a list the GB can subscribe too.

**Comment by danlopez00** [comment]
We will actually be switching over to a webform for contacting the CDF so leads get into SFDC and an autoresponder replies to the requestor. The workflow will be implemented in the coming weeks.

We will also be automating reports of leads and opportunities to the GB on a monthly basis

**Comment by kimsterv** [comment]
What's the status on this? I'd also like to see a process that CDF foundation members can use for getting new members into the pipeline.

**Comment by danlopez00** [comment]
Closing this ticket and opening a new ticket for reports, as CDF members will not have direct access to SFDC
