### ISSUE TITLE
Add google analytics code to jenkins.io

### ISSUE THREAD

**Issue by danlopez00** [cdfoundation/foundation#121]
Add google analytics code to jenkins.io

**Comment by oleg-nenashev** [comment]
Hi @danlopez00 . We already have Google Analytics configured AFAIK. CC @olblak @rtyler

**Comment by danlopez00** [comment]
@oleg-nenashev We are ideally looking for GA that CDF owns and shares with each project respectively. This way the CDF team, and CDF board can keep up to date with all metrics for projects. In short term, lets coordinate to add a few emails to the user group on GA

**Comment by olblak** [comment]
I confirm there is already something for Jenkins and Jenkins X

**Comment by danlopez00** [comment]
ok, lets add a couple of emails to the accounts for metrics and kpi management. will connect over email / slack
