### ISSUE TITLE
add wechat to cd.foundation pg

### ISSUE THREAD

**Issue by jsalinas29** [cdfoundation/foundation#123]

**Comment by danlopez00** [comment]
Spoke with web team and they are working on this now

**Comment by danlopez00** [comment]
![LFAPAC-WeChat-Text](https://user-images.githubusercontent.com/727396/72006600-d9968600-3204-11ea-8083-273d41065b94.jpg)
![LFAPAC-WeChat](https://user-images.githubusercontent.com/727396/72006601-d9968600-3204-11ea-8425-3141c22a7230.jpg)
<img width="151" alt="Screenshot 2019-10-11 at 10 21 28" src="https://user-images.githubusercontent.com/727396/72006602-d9968600-3204-11ea-9671-b1f1f65ad838.png">

**Comment by danlopez00** [comment]
In progress from web team
