### ISSUE TITLE
Apply for Summer of Code 2020

### ISSUE THREAD

**Issue by caniszczyk** [cdfoundation/foundation#129]
I believe Jenkins has historically done this on their own, CDF should do this for its project.

https://opensource.googleblog.com/2020/01/google-summer-of-code-2020-is-now-open.html

**Comment by danlopez00** [comment]
Applied and completed form. Waiting for response.

**Comment by danlopez00** [comment]
https://summerofcode.withgoogle.com/organizations/5550056498790400/

Accepted
