### ISSUE TITLE
clarify who's eligible to vote for active committer board seat

### ISSUE THREAD

**Issue by kimsterv** [cdfoundation/foundation#13]

**Comment by danlopez00** [comment]
After a discussion with @kohsuke he is going to define with the project leaders and maintainers the following:

- Eligibility
- Nomination process

@danlopez00  has the preferred methodology for the following when ready:
- Voting process
- Removal process
- Adding and modifying seats based on org growth and number of projects

**Comment by danlopez00** [comment]
Here is a general process we can follow:

https://github.com/cncf/foundation/blob/master/gb-developer-reps.md

**Comment by danlopez00** [comment]
Updated link: https://github.com/cncf/foundation/blob/master/maintainers-election-policy.md

This should be drafted and proposed to the TOC then to the board

**Comment by galemccommons** [comment]
@tracymiranda I believe we can close out this issue as there is similar work being done on the charter right now. can you please confirm? thank you!

**Comment by fdegir** [comment]
Closing the issue as this has been documented in the charter: https://github.com/cdfoundation/charter/blob/main/CHARTER.md#3-governing-board
