### ISSUE TITLE
MLOps SIG meetings Zoom link + calendar

### ISSUE THREAD

**Issue by MarckK** [cdfoundation/foundation#131]
MLOps SIG meetings no longer appears on the [calendar]( https://lists.cd.foundation/g/sig-mlops/calendar).

For the moment, the schedule is 9:30 - 10:30 PST on Thursday, once every 4 weeks, starting on January 16.

The MLOps SIG will also meet once every 4 weeks at an alternative time to accommodate more time zones. 

Overall, the MLOps SIG will meet once a fortnight.

**Comment by danlopez00** [comment]
CD Foundation is inviting you to a scheduled Zoom meeting.

Topic: CDF SIG MLOps
Time: Feb 13, 2020 09:30 AM Pacific Time (US and Canada)
        Every 2 weeks on Thu, until Mar 25, 2021, 30 occurrence(s)
        Feb 13, 2020 09:30 AM
        Feb 27, 2020 09:30 AM
        Mar 12, 2020 09:30 AM
        Mar 26, 2020 09:30 AM
        Apr 9, 2020 09:30 AM
        Apr 23, 2020 09:30 AM
        May 7, 2020 09:30 AM
        May 21, 2020 09:30 AM
        Jun 4, 2020 09:30 AM
        Jun 18, 2020 09:30 AM
        Jul 2, 2020 09:30 AM
        Jul 16, 2020 09:30 AM
        Jul 30, 2020 09:30 AM
        Aug 13, 2020 09:30 AM
        Aug 27, 2020 09:30 AM
        Sep 10, 2020 09:30 AM
        Sep 24, 2020 09:30 AM
        Oct 8, 2020 09:30 AM
        Oct 22, 2020 09:30 AM
        Nov 5, 2020 09:30 AM
        Nov 19, 2020 09:30 AM
        Dec 3, 2020 09:30 AM
        Dec 17, 2020 09:30 AM
        Dec 31, 2020 09:30 AM
        Jan 14, 2021 09:30 AM
        Jan 28, 2021 09:30 AM
        Feb 11, 2021 09:30 AM
        Feb 25, 2021 09:30 AM
        Mar 11, 2021 09:30 AM
        Mar 25, 2021 09:30 AM
Please download and import the following iCalendar (.ics) files to your calendar system.
Weekly: https://zoom.us/meeting/tZwlf-6orzsubcRZxykyjaEa3v90b2nOlA/ics?icsToken=98tyKuGgpjMtGtWVtF3tRaovW9ribOHyl3NNmJlFhRT8CSF2Y1Dgb7JAYLxQHPmB

Join Zoom Meeting
https://zoom.us/j/888870104

Meeting ID: 888 870 104

One tap mobile
+16699006833,,888870104# US (San Jose)
+16465588656,,888870104# US (New York)

Dial by your location
        +1 669 900 6833 US (San Jose)
        +1 646 558 8656 US (New York)
        855 880 1246 US Toll-free
        877 369 0926 US Toll-free
        +1 647 558 0588 Canada
        855 703 8985 Canada Toll-free
Meeting ID: 888 870 104
Find your local number: https://zoom.us/u/afxZRrxiW
