### ISSUE TITLE
Update MLOps meeting time to support other time zones

### ISSUE THREAD

**Issue by MarckK** [cdfoundation/foundation#132]
Relates to #131

An alternative meeting time for the MLOps SIG needs to be agreed on and scheduled.

**Comment by MarckK** [comment]
Proposed alternative meeting time of: 8:00 UK / 19:00 Sydney 

This would then meet once every 4 weeks on Thursdays, on a bi-weekly cadence with the MLOps SIG meeting time of 9:30 PST / 5:30 UK.

**Comment by MarckK** [comment]
Another alternative meeting could be: 22:00 UK / 9:00 Sydney / 14:00 PST.

**Comment by danlopez00** [comment]
@MarckK have you all decided on a final day/time?

**Comment by danlopez00** [comment]
Closing as I think this is resolved.
