### ISSUE TITLE
Associate CDF billing accounts with Spinnaker AWS project

### ISSUE THREAD

**Issue by ttomsu** [cdfoundation/foundation#134]

**Comment by danlopez00** [comment]
In progress

**Comment by danlopez00** [comment]
Completed with @ttomsu

**Comment by ttomsu** [comment]
Looks like I still need some permissions to create and edit IAM policies so we can get our testing setup ported over.

**Comment by danlopez00** [comment]
Looking into it with @ttomsu

**Comment by danlopez00** [comment]
Granted but switching points of contact to new team member. Closing this as the account is stood up and working with Spinnaker team to complete access
