### ISSUE TITLE
2 Website updates

### ISSUE THREAD

**Issue by TracyRagan** [cdfoundation/foundation#138]
1)Screwdriver needs to be added to Projects and mentioned on front page
2)SIG and Working Groups should be separated

**Comment by danlopez00** [comment]
![image](https://user-images.githubusercontent.com/727396/73687286-83d7c100-467e-11ea-9478-2e212c1a765f.png)

**Comment by danlopez00** [comment]
![image](https://user-images.githubusercontent.com/727396/73687328-98b45480-467e-11ea-8ab6-5c04f4a49c3c.png)

Added to projects page and on home page we now have a button that says "view projects"
