### ISSUE TITLE
Email List for Outreach Sub-Committes

### ISSUE THREAD

**Issue by TracyRagan** [cdfoundation/foundation#139]
We need to have 3 new email lists for the outreach sub-committees:

Member Outreach Sub-Committee:  Chair Anita Rass Wan IBM (email ???)
Project Outreach Sub-Committee:  Chair Rosalind Benoit Armory (rosalind.benoit@armory.io)
CDF Messaging Outreach Sub-Committee: Chair Tracy Ragan, DeployHub (tracy@deployhub)

These groups will all report up to the outreach committee but will be working on specific tasks.  The email-lists are to help the sub-committee chairs communicate meetings, etc. Not sure if we want to call them working groups or not.

**Comment by danlopez00** [comment]
We should be calling them Subcommittees and placed under https://github.com/cdfoundation/foundation/tree/master/committees/subcommittees

Please add members to the subcommittees, we will then be able to add the email distros

**Comment by danlopez00** [comment]
@TracyRagan please feel free to email the members and we can take care of it.

**Comment by danlopez00** [comment]
cdf-outreach-events@lists.cd.foundation 
cdf-outreach-member@lists.cd.foundation 
cdf-outreach-messaging@lists.cd.foundation 
cdf-outreach-projects@lists.cd.foundation
