### ISSUE TITLE
Set up monthly informal GB meetings that alternate with our formal meetings

### ISSUE THREAD

**Issue by kimsterv** [cdfoundation/foundation#14]

**Comment by jsalinas29** [comment]
@danlopez00 can you add me to the formal GM mtgs? Currently, I am not on those mtgs. Thanks!

**Comment by jsalinas29** [comment]
Hi all, 

I kept the same cadence (every third Thursday of every other month) and this will kick off beginning in November. 

I've attached this already in the mtg invite but pasting here: 

Jacqueline Salinas is inviting you to a scheduled Zoom meeting.

Topic: Informal GB mtg
Time: This is a recurring meeting Meet anytime

Join Zoom Meeting
https://zoom.us/j/297308500

One tap mobile
+17207072699,,297308500# US (Denver)
+16465588656,,297308500# US (New York)

Dial by your location
        +1 720 707 2699 US (Denver)
        +1 646 558 8656 US (New York)
Meeting ID: 297 308 500
Find your local number: https://zoom.us/u/axDKdcjnL

**Comment by danlopez00** [comment]
This should take the for of subcommittee meetings. We can establish subcommittees to focus in on specific topics
