### ISSUE TITLE
Request for separate zoom account for Jenkins 

### ISSUE THREAD

**Issue by tracymiranda** [cdfoundation/foundation#144]
Jenkins community has been sharing the CDF zoom account but now we are at a point where with more CDF meetings and Jenkins working groups there is more overlap in schedules. e.g CDF MLOps SIG and Jenkins advocacy and outreach meeting often overlap - whoever gets there first can run their meeting. 

Now would be great to set up Jenkins with a separate way to run zoom that can be used for:
- Jenkins GSoC meetings (ramping up)
- Advocacy & outreach SIG
- Pipeline authoring SIG
- Docs SIG
- Platform SIG
- Chinese internationalization sig, etc

The Jenkins governing board can manage how access is shared, am happy to be point of contact to help bootstrap this.

**Comment by oleg-nenashev** [comment]
Hi @danlopez00 . Any updates on that?

**Comment by danlopez00** [comment]
Completed. @oleg-nenashev and @tracymiranda I will send creds over different medium.
