### ISSUE TITLE
Create Tekton CLI Logo

### ISSUE THREAD

**Issue by caniszczyk** [cdfoundation/foundation#147]
> we'd really like to get a logo for the Tekton CLI (https://github.com/tektoncd/cli) - it's a command line interface for interacting with Tekton, so inspiration wise we thought something involving the tekton cat using a computer keyboard could be really cute.
> 
> Let me know if there's someone else I should direct this request to! And there's one other Tekton project - the dashboard - that we'd potentially like to request a logo for as well.

**Comment by caniszczyk** [comment]
inspiration for the logo design:

![unnamed](https://user-images.githubusercontent.com/63777/75465505-595fe780-594e-11ea-8fee-5bb6e8fcb7a6.png)

**Comment by christianvogt** [comment]
Tekton cat is pretty awesome, so I created a couple logo suggestions:

![image](https://user-images.githubusercontent.com/14068621/75466826-c6787a80-5958-11ea-97c6-6847a67a79fe.png)

![image](https://user-images.githubusercontent.com/14068621/75466982-07708f00-5959-11ea-96cd-c5dbec46957a.png)

**Comment by rtyler** [comment]
:laughing: the second option can be interpreted to be that Tekton cat craps on your command line :laughing:

**Comment by danlopez00** [comment]
In progress

**Comment by caniszczyk** [comment]
@danlopez00 did this ever happen?

**Comment by danlopez00** [comment]
Yes, this has been in process from the design team (internal Jira ticket), but got de-prioritized during last couple weeks.  Its between #1 option above or the sketch provided in jira.

**Comment by bobcatfish** [comment]
@danlopez00 how do we see the sketch in jira?

Very exciting!

**Comment by danlopez00** [comment]
![image](https://user-images.githubusercontent.com/727396/80252323-f0ce7780-862b-11ea-9679-b896b0d7d192.png)

@bobcatfish ^^^^

**Comment by bobcatfish** [comment]
ahhhh that's so cute! i love that! That one gets my vote but ultimately I think it's up to the folks who own the CLI project so I'll ping them in here to decide:

- @vdemeester
- @sthaha
- @hrishin
- @chmouel
- @danielhelfand
- @piyush-garg
- @pradeepitm12

**Comment by vdemeester** [comment]
Oh I definitely vote for this one :heart_eyes_cat:

**Comment by sthaha** [comment]
I ❤️ 

![image](https://user-images.githubusercontent.com/3005132/80322919-6d02ce00-886b-11ea-9aaa-c86d70897d1d.png)

**Comment by chmouel** [comment]
I would vote for this one  : https://github.com/cdfoundation/foundation/issues/147#issuecomment-619214804

**Comment by hrishin** [comment]
I liked https://github.com/cdfoundation/foundation/issues/147#issuecomment-619214804. However, the CLI sign is not that visible.

Otherwise would vote for https://github.com/cdfoundation/foundation/issues/147#issuecomment-619643367.

it could be nice if we can write `> tkn` in front of the terminal sign. 

Thanks!

**Comment by pradeepitm12** [comment]
My personal favorites https://github.com/cdfoundation/foundation/issues/147#issuecomment-619214804
and https://github.com/cdfoundation/foundation/issues/147#issuecomment-619643367

**Comment by danielhelfand** [comment]
I like the one below, but I think all are great and thanks to everyone who put these together. 

![image](https://user-images.githubusercontent.com/34258252/81631904-f3282400-93d6-11ea-9476-8b87823de647.png)

**Comment by vdemeester** [comment]
Alright, final vote in on https://github.com/cdfoundation/foundation/issues/147#issuecomment-619214804 :angel:

**Comment by danlopez00** [comment]
SGTM. @bobcatfish ... the vote suggests. Will set in motion.

![image](https://user-images.githubusercontent.com/727396/81705983-83d92100-9424-11ea-9eab-51e579a59db3.png)

**Comment by caniszczyk** [comment]
@danlopez00 make sure it ends up here thanks https://github.com/cdfoundation/artwork/tree/master/tekton

**Comment by vdemeester** [comment]
@danlopez00 just to make sure, the vote suggested ![cli logo](https://user-images.githubusercontent.com/727396/80252323-f0ce7780-862b-11ea-9679-b896b0d7d192.png)

**Comment by bobcatfish** [comment]
@danlopez00 anything more we need to do to get the above sketched into a final logo? Let me know if I should open another issue :D

**Comment by bobcatfish** [comment]
I'm not 100% sure what the next steps are here so I've opened https://github.com/cdfoundation/foundation/issues/197
