### ISSUE TITLE
Change SIG Interoperability Meeting Invitation Timezone to UTC

### ISSUE THREAD

**Issue by fdegir** [cdfoundation/foundation#149]
US daylight saving time will start earlier than the rest of the world on March 8th which could cause confusion for people. It would be good to update the meeting invitation and change its timezone to UTC as decided by SIG so people could join the meeting at the right time. [0]

The meeting on March 19th will happen at 08:00PDT/15:00UTC/16:00CET.

[0] https://docs.google.com/document/d/13hCBpmuAj3e0gADo1TCjsEwmz57_fw74OhQmeY1extk/edit#heading=h.3ub7vmz2qqtp

**Comment by danlopez00** [comment]
Moved to 3p UTC.
