### ISSUE TITLE
Publishing missing SIG Interoperability Meeting Recordings on Youtube

### ISSUE THREAD

**Issue by fdegir** [cdfoundation/foundation#159]
Can we please get the missing recordings of the SIG Interoperability Meetings uploaded/published on Youtube CDF Channek so people can watch them and see presentations from users and projects when they want?

https://www.youtube.com/playlist?list=PL2KXbZ9-EY9QxICOnONBFPn_cYfJ8BsaG

**Comment by tracymiranda** [comment]
I believe these are now upto date. Please reopen if not and let us know which dates are missing.
