### ISSUE TITLE
Create Zoom Meeting and Calendar event for MLOps SIG Asia-Pacific/Oceania

### ISSUE THREAD

**Issue by tdcox** [cdfoundation/foundation#160]
Please could we arrange a second meeting slot for the MLOps SIG to cater for those based in Asia-Pacific/Oceania?

The consensus seems to be 11:00 BST / 15:00 IST / 18:00 CST / 19:00 JST / 20:00 AEST

Thanks!

**Comment by tdcox** [comment]
Any update on this, please @danlopez00 ? First session is due to be this Thursday at 11:00 BST.

**Comment by danlopez00** [comment]
details sent
