### ISSUE TITLE
Screwdriver logo

### ISSUE THREAD

**Issue by TracyRagan** [cdfoundation/foundation#162]
We need a screwdriver logo that has their image on top and 'screwdriver.cd' under it like the other project logos for the website.  Their logo does not have the same dimensions as the others and looks odd on the case studies page.  See https://cd.foundation/case-studies/

**Comment by danlopez00** [comment]
Requested from the screwdriver team

**Comment by galemccommons** [comment]
Hi @TracyRagan - was this resolved or is this still needed? Thanks!

**Comment by TracyRagan** [comment]
No this is still an issue for the website - check out https://cd.foundation/case-studies/   Notice how it is not in the same size and looks like it is floating above the rest.   We need one that is stacked (logo on top - name on bottom) so it looks consistent.  I'm sure the Screwdriver team has one in svg format that we can use.

**Comment by galemccommons** [comment]
Thanks for the clarification, Tracy. I'll put in a ticket with creative services to get this sorted.

Gale

**Comment by tracymiranda** [comment]
![screwdriver-full-blk-stacked_4x](https://user-images.githubusercontent.com/5173122/97345781-e2724a00-1860-11eb-8dfd-66c95d4b97ab.png)
Jithin was able to provide this logo. Let's:

- [ ] add to artwork github repo
- [ ] use it to update the website case study page.

**Comment by galemccommons** [comment]
This should be resolved now
