### ISSUE TITLE
Dailymotion blog to case study

### ISSUE THREAD

**Issue by TracyRagan** [cdfoundation/foundation#163]
Can we re-purpose this blog:
https://cd.foundation/blog/2020/03/30/dailymotion-continuous-delivery-story-with-jenkins-jenkins-x-and-tekton/

to a case study that could then be posted on Jenkins, JenkinsX and Tekton case study pages. This would put at least one entry into those project's case study pages.  Right now they have nothing and this would give them at least a start.  

Also this blog does not have an author, even though it is written in the voice of someone from Dailymotion.  We should have the authors name and possibly linkedIn info.

**Comment by danlopez00** [comment]
Agreed. This should be put into our formatted template.
