### ISSUE TITLE
High Level case study menu goes to archive pages

### ISSUE THREAD

**Issue by TracyRagan** [cdfoundation/foundation#164]
From the website main menu, under Projects > Case Studies > [Project]
The links goes to the archive pages. The links should go to the page anchor URLs. 

https://cd.foundation/case-studies/#jenkins
https://cd.foundation/case-studies/#jenkinsx
https://cd.foundation/case-studies/#spinnaker
https://cd.foundation/case-studies/#tekton
https://cd.foundation/case-studies/#screwdriver

**Comment by danlopez00** [comment]
resolved
