### ISSUE TITLE
File Jira ticket for CDF Ambassador Program logo & digital badge request from design team

### ISSUE THREAD

**Issue by jsalinas29** [cdfoundation/foundation#165]
We need a logo & digital badge that helps identify CDF Ambassadors on their LInkedIn profile and the logo will help establish the brand of the program & templated marketing materials for the program.

**Comment by jsalinas29** [comment]
- logo
- ambassador digital badge
- email header/hero banner
- email footer banner
- template for social media art to promote latest ambassador 
- sticker decal design

**Comment by danlopez00** [comment]
in progress

**Comment by jsalinas29** [comment]
will create through canva instead of cs
