### ISSUE TITLE
File Jira ticket to design team: create logo & creative assets for CDF podcast 

### ISSUE THREAD

**Issue by jsalinas29** [cdfoundation/foundation#166]
- 400 x 400 logo for podcast cover art 
- email header/hero banner 
- email footer banner 
- template for social media art to promote upcoming episode speakers
- sticker decal design 

name of the podcast - the pipeline (tbd on final name)

**Comment by danlopez00** [comment]
in progress with design team

**Comment by galemccommons** [comment]
hey @jsalinas29 was this ever completed? checking if I can close it out. thanks!
