### ISSUE TITLE
Jenkins would like to request assistance conducting Governance elections

### ISSUE THREAD

**Issue by tracymiranda** [cdfoundation/foundation#18]
Jenkins project will be running board and officer elections and would like CDF to supervise and conduct voting using The Condorcet Internet voting system. Voting period is 14 October to 27 October 2019.

Proposed election schedule is:
13 September, 2019: Nominations open. 
4 October, 2019: Nominations close
8 October, 2019: List of nominees posted to (mailing list)
11 October, 2019: Nominees’ personal statements made available
14 October, 2019: Voting begins
27 October, 2019: Voting closes 5pm Pacific Time
4 November, 2019: New representatives announced

**Comment by tracymiranda** [comment]
Follow up meeting with Dan, Kohsuke & Tracy (after Sep 11 Jenkins board meeting)

**Comment by danlopez00** [comment]
There are some process and procedures that CNCF has done that we can draw from. We will look to use Cornell's voting system: https://civs.cs.cornell.edu/civs_create.html

**Comment by danlopez00** [comment]
Working with @kohsuke to come up with a plan

**Comment by danlopez00** [comment]
@kohsuke would Jenkins team like to engage CDF for overseeing election for 2020?

**Comment by tracymiranda** [comment]
Jenkins community successfully conducted elections in 2019.
