### ISSUE TITLE
Spinnaker logo usage for Spinnaker.Live

### ISSUE THREAD

**Issue by dnilasor** [cdfoundation/foundation#180]
Hi, I'd like to request the use of the Spinnaker logo and trademark for a proposed event happening June 18, "Spinnaker.Live"

This event does not require any additional funding resources from the CDF, although we would love your attendance and support. Please let me know if more context is needed.

**Comment by caniszczyk** [comment]
CDF is now co-hosting the event so this is no longer an issue, thanks for the request!
