### ISSUE TITLE
Create CDF Branding Guidelines

### ISSUE THREAD

**Issue by caniszczyk** [cdfoundation/foundation#185]
Essentially a nicer version of this: https://www.linuxfoundation.org/trademark-usage/

The goal would be to crank something out by end of month so it can be shared with the outreach committee.

**Comment by fdegir** [comment]
@micmarti85 @zestyroxy I remember us discussing CDF Branding Guidelines but I fail to locate it now.

If I remember correctly, can you please point it to me so we close this issue?
If I am mistaken, we could perhaps work on one in collaboration with @LoriLorusso and broader outreach committee?

**Comment by micmarti85** [comment]
@fdegir @zestyroxy 
Our website has links to the copyright and trademark usage. LF owns them so we don't establish those rules, they're legal so they are enforced and managed by LF legal.

I don't see anything like this for CNCF, the closest i see is https://github.com/cncf/foundation/blob/main/style-guide.md

I think we should have an artwork repo we link to but I don't think we own the CDF "brand"  the LF does.

**Comment by fdegir** [comment]
@micmarti85 created the brand guidelines: https://github.com/cdfoundation/foundation/pull/427 so closing this issue.
