### ISSUE TITLE
Spinnaker Zoom account for SIG meetings and community events

### ISSUE THREAD

**Issue by dnilasor** [cdfoundation/foundation#186]
The Spinnaker SIG meetings are currently using Google Hangouts (not China-friendly) and are also managed by Google employees. If googlers can't make the meetings, other folks get locked out. Can we please create a Zoom account for Spinnaker that will allow us to make these meetings open? @link108 made the most recent request for this feature and will need credentials once the account is set up. 

I am also hoping that "[Join multiple meetings](https://support.zoom.us/hc/en-us/articles/360001120743-Join-Multiple-Meetings-Simultaneously-on-Desktop)" feature could be enabled on the Spinnaker account. I needed this type of account to run the Spinnaker Gardening Days hackathon effectively and still don't have a China-friendly workaround to use for the June hackathon coming up. This feature is only enabled on very large accounts, but it seems like the LF may have the critical mass. It would allow us to monitor events that use multiple zoom meetings for folks who need help, as well as inappropriate content or zoom bombing.

**Comment by caniszczyk** [comment]
@danlopez00 this should be a quick turn around, if you want to see how we automate uploads to youtube from zoom in k8s land you can see this https://github.com/kubernetes/community/blob/master/communication/youtube/youtube-guidelines.md#automation

**Comment by danlopez00** [comment]
This was submitted for. 

re: Splain.io. Will give it a go. Previous scripting with adding pre/post roll is ideal, but automated that does have much downtime would be better to meet growing demand.

**Comment by danlopez00** [comment]
creds provided to Spinnaker team. Moving Splain.io to another task
