### ISSUE TITLE
automate zoom video recordings to youtube channel

### ISSUE THREAD

**Issue by danlopez00** [cdfoundation/foundation#188]
automate uploads to youtube from zoom in k8s land you can see this https://github.com/kubernetes/community/blob/master/communication/youtube/youtube-guidelines.md#automation

**Comment by dnilasor** [comment]
FWIW the "stream live on Youtube" feature in Zoom automates this natively without much work.

**Comment by jsalinas29** [comment]
@markyjackson-taulia - i think this is a duplicate of 202

**Comment by markyjackson-taulia** [comment]
Agreed, this is a dup

**Comment by markyjackson-taulia** [comment]
I have completed this work as discussed and will pr the new zoom and YouTube guidelines in by the end of the week.
You rock @jsalinas29
