### ISSUE TITLE
Secrets management for Zoom creds

### ISSUE THREAD

**Issue by dnilasor** [cdfoundation/foundation#189]
Is there a standard secrets management tool that the CDF or LF uses to manage shared credentials like the Zoom login? There are other areas where the need for this has popped up. I don't want to post the creds in GitHub obviously, and sharing them individually in Slack isn't scalable. I don't know of a 2-way secrets sharing solution in GitHub but maybe there is one?

**Comment by caniszczyk** [comment]
@dnilasor two options, generally recommend projects use something like 1password https://github.com/1Password/1password-teams-open-source or keybase.io, both are free :)
