### ISSUE TITLE
Add an events page to cd.foundation

### ISSUE THREAD

**Issue by tracymiranda** [cdfoundation/foundation#19]
Currently there is no place on cd.foundation to raise awareness of CDF events e.g. CD Summit NA. Would be great to have an events section.

**Comment by tracymiranda** [comment]
Discussed 6/9 and @danlopez00 can enable events module e.g. https://www.hyperledger.org/events

**Comment by danlopez00** [comment]
Plugin installed on site. Will enable and grant access to site content admins. 

Next step is to create the events on the site.

**Comment by danlopez00** [comment]
https://cd.foundation/events
