### ISSUE TITLE
Join multiple meetings feature for CDF/LF Zoom account

### ISSUE THREAD

**Issue by dnilasor** [cdfoundation/foundation#190]
I am hoping that "Join multiple meetings" feature could be enabled on the Spinnaker Zoom account. I needed this type of account to run the Spinnaker Gardening Days hackathon effectively and still don't have a China-friendly workaround to use for the June hackathon coming up. I will not be able to spin up multiple meetings for hackathon project teams using the Spinnaker account because each account can only have one active meeting (even on different devices).

This feature is only enabled on very large accounts, but it seems like the LF may have the critical mass. It would allow us to monitor events that use multiple zoom meetings for folks who need help, as well as inappropriate content or zoom bombing. Can someone please look into it?

**Comment by dnilasor** [comment]
Hi, any update on this? SGD is coming up June 25th and I'll need to figure out a free or inexpensive workaround asap if we can't use this feature

**Comment by dnilasor** [comment]
I guess this is a no?

**Comment by caniszczyk** [comment]
@dnilasor I reached out to Brian Warner who is helping with program management in CDF that should be able to fulfill this request, sorry for the delay, we had a change in program management within CDF.

**Comment by dnilasor** [comment]
No worries, I understand! Thanks for your follow-up. I am putting together a workaround in case this doesn't work out but glad he can look into it, as I think everyone at the CDF would likely use this feature.

**Comment by brianwarner** [comment]
@dnilasor I'll find you on Slack and we can get this figured out.

**Comment by galemccommons** [comment]
@dnilasor the "join multiple meetings" option is not available with our Zoom accounts. I know this is late, but as a workaround for future events, Zoom breakout rooms are an option. Some projects also use Google Meet when needs like this arise. Please keep me posted with how I can help in the future.  -G
