### ISSUE TITLE
Design services for Spinnaker.io

### ISSUE THREAD

**Issue by dnilasor** [cdfoundation/foundation#192]
I'm working on a refresh of Spinnaker.io with the Spinnaker Docs SIG and TOC. The RFC for the refresh has been approved and is documented [here](https://github.com/spinnaker/governance/blob/master/rfc/website-revamp.md).  

I have found a contractor who is experienced with the infrastructure and eager to begin work on the [development work outlined](https://github.com/spinnaker/governance/blob/master/rfc/website-revamp.md#development) in the SOW. I'd like to request that the Linux Foundation creative team help with the [design work outlined](https://github.com/spinnaker/governance/blob/master/rfc/website-revamp.md#design-1) and collaborate with the dev contractor (Amy) on resources such as wireframes as needed.

**Comment by danlopez00** [comment]
Working with design team to coordinate

**Comment by dnilasor** [comment]
I'm also waiting to hear whether or not I should proceed with paying the dev. contractor with Armory budget (this has been approved by the SIG), or should wait to see if my funds request to the CDF has been approved by the board. 

Can you let me know what to do? I don't want to commit an OSS governance faux pas

**Comment by dnilasor** [comment]
We have hired the dev contractor and are ready to begin with design services. Please advise on next steps.

**Comment by dnilasor** [comment]
I'm talking with the dev contractor now and she needs design input on the work she is doing for the Home page and other pages. 

We are unable to wait any longer than about a week to secure design services from the CDF/LF. Moving forward with the dev work that is already underway requires some wireframes to work from. There's a possibility for us to hire a contract designer for the work, but this will make the spinnaker.io refresh project being funded by Armory go over-budget, as we had planned to leverage LF services. 

@ccraigross are we still able to collaborate on this? What kind of timeline is possible? What are my next steps at this point given Dan's departure? Thanks!

**Comment by dnilasor** [comment]
Hi @brianwarner can you help me with this? The designer is waiting on Hero image, etc. 

We can hire out a designer but since Armory is already footing the bill for development of this project, I was hoping for some more LF support for this much-needed re-platforming and update of Spinnaker.io. Either way, we need to move forward. Thanks.

CC Spinnaker Docs SIG @dorbin @brian-armory @aimeeu

**Comment by dnilasor** [comment]
Hey @brianwarner, thanks for sharing this. I want to confirm - is the designer who created this engaged with our developer (@amygroshek), and able to work on the project? We need more than just a hero design. Re: choosing between these designs, it is a bit difficult to choose without considering the other elements. This is what the frontend designer from Netflix on our SIG said:

>  It’s a difficult call to make in isolation, because the hero image is kind of like your opening statement on how the rest of the design will go. The statement should echo throughout the rest of the design. So my answer would be whatever gives the designer enough liberty to play off of their declared visual cues elsewhere, vs a hero image that doesn’t match everything else.
Taken in isolation, I like the first one the best, but I want to see where these color selections, photos of sailboats, and splashes of water go. I’m a sucker for good illustrations too, so if the hero has the same illustrative style as secondary elements, that could be great.

This is fine for a first attempt but we're not super in love with any of these proposed hero's. We need a designer who can get engaged in our project on GitHub/Slack, listen to our requirements and preferences, and iterate with us. Do we have that from the LF team?

**Comment by dnilasor** [comment]
So we need design concepts that show us other concepts besides the hero, and that are based on our current mock-up for the new site (not just the home page of the existing site, which is changing significantly with the redesign). The mock-up is linked in the [RFC](https://github.com/brian-armory/governance/blob/rfc.website/rfc/website-revamp.md).

**Comment by brianwarner** [comment]
Hi @dnilasor, thanks for the feedback, I've passed this to the LF team.

**Comment by dnilasor** [comment]
Great! Thanks @brianwarner . I have a bit more, from our dev, about what she is looking for:

> ...the industry standard is a Sketch file or a design in Figma, something where styles can be easily copied, commented on, revised, etc. You might not have that option… But that’s definitely what I would try for.
b) This is also very far from the [Tensorflow](https://www.tensorflow.org/) site you provide as an example. Ideally I think you would be able to get very close to that, with different color scheme and motifs but a similar aesthetic. I can get you very close without any help, but some of the very specific background patterns & etc we would need a designer for.

So that's the kind of engagement and artifacts we are hoping for - Sketch or Figma files and help with advanced designs

**Comment by dnilasor** [comment]
Following up. @brianwarner, we are looking for a yes/no on whether this is the kind of support that an LF designer can offer. @Amygroshek still hasn't heard from them to my knowledge.

**Comment by brianwarner** [comment]
All, I chatted with Tracy and Rosalind offline, and due to a variety of constraints we agreed this probably doesn't make sense to come from the LF. I'll go ahead and close out the issue.
