### ISSUE TITLE
CDF Brand Kit Update

### ISSUE THREAD

**Issue by dnilasor** [cdfoundation/foundation#193]
We'd like an updated version of the CDF brand kit. A number of different tweaks and enhancements have been suggested, and we'd like to see the suggestions addressed in a concerted branding update effort rather than piecemeal. 

Our most pressing request is that we come up with an alternative to the Spiral graphic:
![image](https://user-images.githubusercontent.com/36797588/83171547-23580e00-a0cb-11ea-9069-753ba159a247.png)
as this has turned out to be very difficult to incorporate into collateral. We'd like a simpler and more portable core branding artifact, perhaps based on the infinity sign?

Other requests include a "mascot" character, along with a customized mascot to represent the CDF Ambassador program. I'll let others add comments or links to related requests in other issues.

**Comment by danlopez00** [comment]
Opening with design team, and will get something on the calendars to coordinate updated messaging.
