### ISSUE TITLE
Spinnaker Gardening Days hackathon branding and logo usage

### ISSUE THREAD

**Issue by dnilasor** [cdfoundation/foundation#195]
Hi, I am preparing materials for another hackathon for Spinnaker. I am reviewing the trademark guidelines and have a couple questions.

First, do I have permission to call the event "Spinnaker Gardening Days" and use the official Spinnaker logo? This event is a Spinnaker community hackathon, a 2.0 of [this event](https://github.com/spinnaker-hackathon/gardening). It's happening June 25th-July 2.

Second, would it be acceptable to create/use a "sketched" version of the Spinnaker logo to put on event-related heroes and swag? We would use the horizontal black version of the logo:
![image](https://user-images.githubusercontent.com/36797588/83782785-cc12ea00-a644-11ea-8234-b2507a34bddc.png)
and then have a designer render a slightly sketched version like this:
![image](https://user-images.githubusercontent.com/36797588/83784103-362b8f00-a645-11ea-973e-631871a20302.png)

this will match the design we have put together for an event graphic. LMK if this is acceptable within the guidelines and/or if there are specific requirements to meet when executing it. I can provide a mock-up if desired but don't want to spend the designer's time on it if it is prohibited. 

Thanks!

**Comment by dnilasor** [comment]
Turns out the designer churned out mockups pretty quickly so this is in the vein of what I am proposing: 
![image](https://user-images.githubusercontent.com/36797588/83920985-43727780-a732-11ea-8ed7-115fbc6abd88.png)
![image](https://user-images.githubusercontent.com/36797588/83921003-4c634900-a732-11ea-8674-7b3eef57963a.png)

**Comment by dnilasor** [comment]
Are these approved?

**Comment by caniszczyk** [comment]
@dnilasor I believe @danlopez00 is on vacation and is back on Monday so sorry for the slow response there. I'll step in for now. We usually allow marks for non-commercial uses such as t-shirts and stickers without permission and this case it would fall under that but I'd have Dan get a policy cemented by the GB in the coming months.

If that spinnaker-hackathon is part of the spinnaker project then it's a definite no problem.

**Comment by dnilasor** [comment]
Hey @caniszczyk sounds good and thanks! Note this is overall branding for the event so will also be featured on web assets on Eventbrite, Spinnaker.io, Slack, etc. 

The spinnaker-hackathon org on GitHub isn't part of the spinnaker GitHub org simply because, I want to have an umbrella org where I can give participants permissions to create their own project repositories while doing the hackathon. But the goal of the event is to contribute to the Spinnaker project, so I think it should be OK.
