### ISSUE TITLE
New Subdomain on Jenkins-X.io for Community Discourse Forum

### ISSUE THREAD

**Issue by Dgiordano33** [cdfoundation/foundation#196]
We'd like to create a new subdomain on Jenkins-X.io -> discussion.jenkins-x.io. That subdomain then needs to be pointed to 34.105.109.153 - an open-source discourse forum that will be used to advance the JX community.

The issue was originally raised here: https://github.com/jenkins-x/jx/issues/7044

**Comment by brianwarner** [comment]
Hi @Dgiordano33, just confirming that I'm on this. The request has been filed with LF IT.

**Comment by brianwarner** [comment]
Hi @Dgiordano33, confirming that this is done.
