### ISSUE TITLE
Track work for final version of Tekton CLI logo?

### ISSUE THREAD

**Issue by bobcatfish** [cdfoundation/foundation#197]
Hi all!

In https://github.com/cdfoundation/foundation/issues/147 we looked at options for the Tekton CLI logo and had a bunch of submissions from @christianvogt and the CDF design team via @danlopez00 

The final decision was:

![image](https://user-images.githubusercontent.com/432502/84166959-98203600-aa43-11ea-8aa4-0891265b0cd7.png)

I wanted to double check that there is work in progress to make a final version of that logo and ask what the best way is to keep track of that progress.

Thanks!

**Comment by danlopez00** [comment]
The final versions are getting chopped up into SVGs today and will post to the artwork repo, but here is the final version:

![image](https://user-images.githubusercontent.com/727396/84170826-eb3bbe00-aa2e-11ea-8d59-122bfe38cf3f.png)

**Comment by bobcatfish** [comment]
AMAZING!!!! 😻
