### ISSUE TITLE
Create Tekton Dashboard logo

### ISSUE THREAD

**Issue by a-roberts** [cdfoundation/foundation#198]
https://github.com/cdfoundation/foundation/issues/147 is awesome and it would be great to have a logo in the same style for our Tekton Dashboard!

I've added a few ideas at https://github.com/tektoncd/dashboard/issues/1012 - more always welcome.

I think it's especially useful for presentations - nobody wants to have the words "Tekton Dashboard"  and I'd like to continue the theme of having the Tekton cat doing something fun that's easily recognisable and associated with this. 

Lemme know if you're looking for anything to help make this happen please, thanks!

**Comment by tracymiranda** [comment]
I've added this to agenda for TOC meeting tomorrow, under 'pending project requests'
https://docs.google.com/document/d/1uBHar55fTInWF9Li4t0lyG3tTC8BRLU0FfBfsgk_Jrs/edit?ts=5c9580be#

We just need to know what design ideas to move forward with and any deadlines to be aware off so let's discuss tomorrow then get the ball rolling on this. Please do join the meeting if you can.

**Comment by a-roberts** [comment]
@AlanGreene @eddycharly ^^ check this out! 😄 from my perspective, it'd be the Tekton cat inspecting a PipelineRun with a magnifying glass. The view of the PipelineRun would be a stylised one of the ones we render currently.

Example visualisation, taken straight from our [readme](https://github.com/tektoncd/dashboard):

![image](https://user-images.githubusercontent.com/12814972/97284139-96131400-1838-11eb-8543-eedcebaf652a.png).

We'd want it to be general/stylised enough so that we don't need to keep updating it.

I did think about having a notebook nearby with "Awesome Tekton plan" on it, or having some very obviously "for reading" glasses on the cat, but let's start with something simple for now I think - and we wouldn't want too much detail in there just incase it's going to be a tiny picture somewhere on a chart.

**Comment by AlanGreene** [comment]
🎉 @tracymiranda thanks for adding this to the agenda. Unfortunately I won't be able to attend. There's no particular deadline, but it would be great to have some artwork for the Dashboard since Tekton Pipelines, Triggers, CLI, and Chains already have their own.

@a-roberts There's too much detail to capture something like that and I feel it wouldn't translate very well at small sizes, not sure it'd be recognisable as any kind of dashboard. Maybe something simpler / more abstract would work?

Existing project icons for reference:
![image](https://user-images.githubusercontent.com/2829095/97291874-61a45580-1842-11eb-8491-961155f7a018.png)

I do like the idea of the cat inspecting something with a magnifying glass. Perhaps a screen displaying a simple pipeline graph to represent the Dashboard?

![image](https://user-images.githubusercontent.com/2829095/97296517-b054ee00-1848-11eb-8d35-82c19e5b8df5.png)

**Comment by a-roberts** [comment]
> 🎉 @tracymiranda thanks for adding this to the agenda. Unfortunately I won't be able to attend. There's no particular deadline, but it would be great to have some artwork for the Dashboard since Tekton Pipelines, Triggers, CLI, and Chains already have their own.
> 
> @a-roberts There's too much detail to capture something like that and I feel it wouldn't translate very well at small sizes, not sure it'd be recognisable as any kind of dashboard. Maybe something simpler / more abstract would work?
> 
> Existing project icons for reference:
> ![image](https://user-images.githubusercontent.com/2829095/97291874-61a45580-1842-11eb-8491-961155f7a018.png)
> 
> I do like the idea of the cat inspecting something with a magnifying glass. Perhaps a screen displaying a simple pipeline graph to represent the Dashboard?
> 
> ![image](https://user-images.githubusercontent.com/2829095/97296517-b054ee00-1848-11eb-8d35-82c19e5b8df5.png)

Exactly my thoughts, I imagine we'd want something that'd work even if it was just a 128x128 png - so my magnifying glass suggestion is what I'm leaning towards - looking at your simple chart yep (so that's good because it's abstract and not tied to our UI implementation)

My schedule's very packed today as well but will be checking here for updates and happy to pitch in/provide feedback for anything.

**Comment by galemccommons** [comment]
Hi team - ticket submitted to LF creative services to get work started on this logo.

**Comment by tracymiranda** [comment]
(Internal reference: https://jira.linuxfoundation.org/browse/LP-6892)

**Comment by galemccommons** [comment]
[tekton_dashboard_logoconcept_V1.pdf](https://github.com/cdfoundation/foundation/files/5598032/tekton_dashboard_logoconcept_V1.pdf)

Hi team - creative services has put together the attached draft for your review. Please let me know your feedback. 

-G

**Comment by a-roberts** [comment]
> [tekton_dashboard_logoconcept_V1.pdf](https://github.com/cdfoundation/foundation/files/5598032/tekton_dashboard_logoconcept_V1.pdf)
> 
> Hi team - creative services has put together the attached draft for your review. Please let me know your feedback.
> 
> -G

Yay! This looks super cool, better than looking at a monitor 😆 

I like the overall circular shape of the feature - would easily be at home and fit well on a document like when presenting at a conference. It's easily croppable and not something awkward.

I think that's the cat's body just between the paws, it does look a little strange (so it looks like the cat is in a reclined pose) - but maybe that's intended or something we could exaggerate? I like the idea of the cat just relaxing somewhere, in a reclined position, observing as things happen inside Tekton. Things seem a little slanted at the moment with it - like it's off to one side.

For the actual circles, I wonder if it's clear enough what they currently (or will) represent? Any ideas for what we could put in here @AlanGreene? I realise we probably don't want text, I love the style of this in general as is.

Thank you all for working on this and sharing 😄

**Comment by galemccommons** [comment]
Thanks! I'll share this feedback with creative services and we'll go from there.

**Comment by AlanGreene** [comment]
Sorry I didn't see the notifications before. I agree with Adam's comments, love the concept 👍 😸 

With the graph arcing over the cat's head it looks like this won't be as neat/compact as some of the other logos. Is that a concern? I wonder if that part could (should?) be simplified, using fewer circles maybe.

**Comment by galemccommons** [comment]
Hi team - quick update, I am still waiting on feedback from creative services. I will keep you posted with updates.

**Comment by galemccommons** [comment]
@a-roberts @AlanGreene - do you have any feedback on this version of the logo? are we good to move forward with this one? Thank you!

**Comment by a-roberts** [comment]
> @a-roberts @AlanGreene - do you have any feedback on this version of the logo? are we good to move forward with this one? Thank you!

Hey there! I like it 😄 colouring is on-point, as is the font, I am wondering how we can explain what's going on with the shapes around the cat - like, how can we map them to what actually happens in the Tekton Dashboard?

It would be cool if, let's say you're at a conference, someone asks `sooo what do those circles represent, and what about the larger one at the top`? I've been thinking about a possible explanation and the best I've got is...optional Tasks in a Pipeline. If I can get that sorted, I'll be happy to say yep let's go with this!

@AlanGreene when you get a chance please

**Comment by galemccommons** [comment]
@dlorenc @AlanGreene @a-roberts - are there any final changes you would like made to the logo? thanks!

**Comment by a-roberts** [comment]
> @dlorenc @AlanGreene @a-roberts - are there any final changes you would like made to the logo? thanks!

Not from me! 👍

**Comment by galemccommons** [comment]
Thanks everyone for the feedback! I will let the creative team know that this logo is approved, and close out this issue.

@jsalinas29 the new Tekton dashboard logo is finalized if you would like to add it to our assets.

Thanks all!!

**Comment by AlanGreene** [comment]
@galemccommons @jsalinas29 where should we be sourcing the final logo assets from? I don't see the Dashboard logo (this issue) or the [Hub logo](https://github.com/cdfoundation/foundation/issues/218) in https://github.com/cdfoundation/artwork/tree/main/tekton

**Comment by dlorenc** [comment]
@galemccommons and @jsalinas29 would be the right ones to answer this. I'll ping them on slack.

**Comment by galemccommons** [comment]
@vdemeester @dlorenc the logos are uploaded in the additional artwork repo here: https://github.com/cdfoundation/artwork/tree/main/tekton/additional-artwork/tekton_dashboard
