### ISSUE TITLE
Plan budget for security audits for CDF projects

### ISSUE THREAD

**Issue by caniszczyk** [cdfoundation/foundation#2]
It would be ideal to have a budget set for security audits for CDF related projects.

e.g., https://coredns.io/2018/03/15/cure53-security-assessment/

**Comment by danlopez00** [comment]
There is an email thread that is tracking this activity.

**Comment by danlopez00** [comment]
Meeting with suggested provided setup from recommendation of CNCF. The meeting will help establish scope, timelines and budget.

**Comment by danlopez00** [comment]
ref: #6

**Comment by danlopez00** [comment]
Awaiting proposal from vendor

**Comment by danlopez00** [comment]
An initial estimate is $50k USD. Waiting on SOW and MSA for formal review with governing board for consideration

**Comment by danlopez00** [comment]
Requirement: First candidate will be Spinnaker

**Comment by danlopez00** [comment]
Received SOW and Estimate. Moving this to Governing Board and TOC decision making process and closing ticket
