### ISSUE TITLE
Update project status on cd.foundation website

### ISSUE THREAD

**Issue by tracymiranda** [cdfoundation/foundation#200]
The TOC are rebooting the CDF project lifecycle process and graduating all the projects. We need to update cd.foundation website to reflect the status, i.e. on https://cd.foundation/projects/ and in the menu items. 

@dlorenc please note if there are any other cases to note.

**Comment by tracymiranda** [comment]
Updates made to the main cd.foundation site by Brian Warner. 

Landscape needs to be updated too.

**Comment by brianwarner** [comment]
This should be done now.

**Comment by tracymiranda** [comment]
Great thanks!
