### ISSUE TITLE
Update of SIG Interoperability Meeting Invite with New Agenda Link

### ISSUE THREAD

**Issue by fdegir** [cdfoundation/foundation#201]
SIG Interoperability recently started using HackMD to keep meeting notes to allow access for contributors from countries with access restrictions to Google services while making collaborative editing possible.

Can you please update the SIG Interoperability meeting invite and replace the agenda link with the one below?

https://hackmd.io/HuufSDMaTPyb3qxkyBKg3A

/cc @rakhbari @MarckK

**Comment by jsalinas29** [comment]
- working on this

**Comment by fdegir** [comment]
@jsalinas29 any update on this?

**Comment by fdegir** [comment]
Thanks for updating the meeting invitation @jsalinas29.

We will need the meeting invitation include the Zoom meeting link as well but I'll close this one and open a new one instead.
