### ISSUE TITLE
Spinnaker.io Domain Mgmt via Netlify

### ISSUE THREAD

**Issue by dnilasor** [cdfoundation/foundation#203]
Hi! We're hoping it's possible to set up Spinnaker.io to use Netlify for domain management, the way that Kubernetes.io does. This way, SIG leads can manage DNS and can add users. The Spinnaker Docs SIG has noted that this will allow them to use Netlify DNS to create branched subdomains for previous releases. This helps with providing access to versioned documentation. 

When we have the bandwidth, is Netlify DNS possible for the Spinnaker domain? I think this would be a good "golden path" for community-managed project websites.

CC @markyjackson-taulia @aimeeu

**Comment by jsalinas29** [comment]
I believe this was already proposed to the board back in April: https://docs.google.com/presentation/d/1ZrwePi9hnW3A3sm1lPYnKZik-I6jvojge6u99RlEnmc/edit?usp=sharing

@tracymiranda - was there ever a resolution for this?

**Comment by tracymiranda** [comment]
I don't believe this was covered in that proposal. CDF uses LF infra to provide support for domain, DNS, etc. Let's connect you with those folks (via Brian Warner) so details can be worked out

**Comment by jsalinas29** [comment]
for some reason I can't assign this to Brian but I will follow up with him on next steps to figure this out

**Comment by brianwarner** [comment]
Thanks @tracymiranda and @jsalinas29. I'm working on the options for this now.

In the meantime, could you please connect me with the folks who should have access to this?

**Comment by timfong888** [comment]
@dnilasor -- hi, we are enabling for the community self-serve requests for IT assistance, which would include DNS.  This will enable the community to work directly with the IT team around infrastructure to ensure they understand your use case.  We are rolling out a capability for self-management of DNS, so I think connect with them directly will help make for a better solution as they understand your requirements.

Would you mind logging your details here (the main domain for the future is [https://support.linuxfoundation.org](https://support.linuxfoundation.org) : [https://jira.linuxfoundation.org/servicedesk/customer/portal/2](https://jira.linuxfoundation.org/servicedesk/customer/portal/2)?   

It also helps us improve that interface to know how to make it more valuable so the community can go to IT directly.  Thanks!

**Comment by aimeeu** [comment]
@timfong888 I logged into the service desk and looked at the _Update DNS records_ form. I'm guessing that's the form we have to submit when we want to update the DNS entries for spinnaker.io to point to Netlify's nameservers?

**Comment by brianwarner** [comment]
All, I connected with @dnilasor on this. It sounds like we can close this out, as it can be handled through subdomain redirects on ITx. Per the offline discussions, the Spinnaker team can just ping me or @galemccommons and we can take care of the redirects on the spot.

**Comment by timfong888** [comment]
@aimeeu  -- yes, there are two options.  You can fill out the form described above.  This will enable the team to do it.  Or per @brianwarner  you can go to him and they will make the change (ideally we should still log the ticket, regardless of who makes the change so we can review globally LF service levels.
