### ISSUE TITLE
Newsletter Mailing List Subscription

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#204]
In the footer of nearly every cd.foundation page there's a "sign up for our community mailing list" button. I understand that the community mailing list is different from the newsletter mailing list, but right now the button links to the newsletter subscription page.
Here's what I propose:
1) Change the current button link to direct to Community Mailing List
2) Disable or replace this button with "Subscribe to the monthly newsletter" (linking to https://cd.foundation/stay-connected/) for all newsletters pages `/stay-connected/`.

**Comment by tracymiranda** [comment]
Update button with 'Sign up for newsletter & CDF updates' for now

**Comment by galemccommons** [comment]
ticket submitted to creative services

**Comment by galemccommons** [comment]
this has been updated
