### ISSUE TITLE
Blog Post Preview Link

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#205]
When I create a newsletter article/blog post, I'd love to have the option to send the authors a preview link for them to review the article without publishing it publicly. Is there an option we could add to WordPress to make this possible?

**Comment by galemccommons** [comment]
JIRA ticket submitted to LF creative services

**Comment by galemccommons** [comment]
Hi,

Creative services has provided us with the below response:
`
They can do so by publishing it but not selecting a category (i.e. blog) so that it doesn't post. They can also set a password if they would like. If they want to have it be a draft, they will need to have account credentials where someone could login to view a draft post.`

Will this work for what you're trying to achieve?

Thank you!
Gale

**Comment by zestyroxy** [comment]
I have done both of those things, or I send them a screenshot, but I would prefer it if we could have a plugin link this one that activates "public previews": https://wordpress.org/plugins/public-post-preview/

> They can do so by publishing it but not selecting a category (i.e. blog) so that it doesn't post
But then I have to send them a new link later when I select a category 

> They can also set a password if they would like.
And this is an extra step for me and the author

**Comment by galemccommons** [comment]
Checking in with the team to see if they can activate this plugin.

**Comment by galemccommons** [comment]
Hi Roxanne,

The plugin is installed, and ready to go! :)

**Comment by zestyroxy** [comment]
The preview checkbox doesn't appear for me. Maybe I need to be given access? More details here: https://wordpress.org/plugins/public-post-preview/

**How it should look:**
![blogpreview](https://user-images.githubusercontent.com/18251881/97338443-b0251480-1881-11eb-88c1-5b72c404fdd4.png)

**What I see:**
![blog preview](https://user-images.githubusercontent.com/18251881/97338131-7227f080-1881-11eb-99ba-5ba7b904f13a.png)
