### ISSUE TITLE
Spinnaker.io certificate broken for links not including the www prefix

### ISSUE THREAD

**Issue by dnilasor** [cdfoundation/foundation#207]
When the Spinnaker.io certificate was messed up a little while ago, the new certificate that was created only works with www.spinnaker.io and not spinnaker.io. This is causing links to spinnaker.io across the web to break.

For example, in Armory docs, we have links to things like https://spinnaker.io/downloads/kubernetes/service-account.yml, and these resources now throw a cert error, whereas this works normally: https://www.spinnaker.io/downloads/kubernetes/service-account.yml.

@brianwarner can we fix this certificate to make it more inclusive, or add one for spinnaker.io without the prefix? Otherwise we'll need to search through and update all of our docs. 

CC @michaeldbrown @brian-armory

**Comment by brianwarner** [comment]
Hi @dnilasor, looking into this now. The server is running letsencrypt, so I'd bet someone just needs to add spinnaker.io as an alias and re-issue the cert.

I'm still getting my arms around where things are, can someone please connect with me on Slack so I can understand where the site is being hosted (and where the alias should be added)?

**Comment by brianwarner** [comment]
This appears to be fixed, thanks to @plumpy. Nice catch!

I'll close the issue.
