### ISSUE TITLE
Slack 10k message limit

### ISSUE THREAD

**Issue by dnilasor** [cdfoundation/foundation#208]
Hey, I'm seeing this message in CDF Slack and have heard others report it:

![image](https://user-images.githubusercontent.com/36797588/85619389-11f51980-b617-11ea-987d-04232fb9b31d.png)

Maybe this doesn't matter to us? If a paid plan isn't in the budget, I wonder if there is a way to hide it? It makes us look cheap, lol.

**Comment by dnilasor** [comment]
And I mean, hide it administratively from everyone (I know there is a way to X out).

**Comment by tracymiranda** [comment]
@brianwarner can you help with this?

**Comment by brianwarner** [comment]
Unfortunately Slack does not support our type of non-profit under the "Slack for Non-Profits" plan. I don't believe it's possible to suppress that notice.

**Comment by markyjackson-taulia** [comment]
To add to this. There is no way to remove this at the global level (without paying) but users can use scripts to remove older messages to avoid this.
