### ISSUE TITLE
CDF Landscape rollout yaml file

### ISSUE THREAD

**Issue by TracyRagan** [cdfoundation/foundation#21]
The Landscape processes uses a YAML file that members can update.  We need to build the initial file and test it out.

**Comment by caniszczyk** [comment]
@danlopez00 is working on it here: https://github.com/cdfoundation/landscape

**Comment by danlopez00** [comment]
Correct. We need to chase down the SVGs

**Comment by caniszczyk** [comment]
It should be in the CNCF landscape repo, you can just reuse the SVGs

https://github.com/cncf/landscape/tree/master/hosted_logos

**Comment by danlopez00** [comment]
@TracyRagan has made a lot of progress with logos after @danlopez00 initial code commit. @danlopez00 also provided @TracyRagan various API keys to allow the app to work. We will sync up next week but the next step is to deploy

@danlopez00 to work with @caniszczyk to deploy

**Comment by danlopez00** [comment]
deployed v0.5 draft https://landscape.cd.foundation/

https://github.com/cdfoundation/cdf-landscape/blob/master/landscape.yml

**Comment by danlopez00** [comment]
Closing this and will move discussion to [landscape](https://github.com/cdfoundation/cdf-landscape) repo
