### ISSUE TITLE
Blog post featured image behaviour

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#210]
When I set a "featured image" for a blog post (for it to be used on social media), it also adds the image to the top of the blog post's page and on the https://cd.foundation/blog/ page it blows up the image to page width (even if it's small). 
Can we change the code so that the featured image will not be displayed anywhere but in social media cards?

Sample blog post: https://cd.foundation/blog/2020/06/30/introducing-our-newest-cdf-ambassador-steven-terrana/
![featured-image-blog](https://user-images.githubusercontent.com/18251881/86475692-7023aa00-bd45-11ea-8ba7-c9b6adfe4df2.png)

**Comment by galemccommons** [comment]
JIRA ticket submitted to LF creative services

**Comment by galemccommons** [comment]
This should be corrected now. Can you please test and let me know if the issue is resolved?

Thank you!
Gale

**Comment by zestyroxy** [comment]
I added a picture to a post from September and the issue is still there on page: https://cd.foundation/blog/
Modified post: https://cd.foundation/blog/2020/09/15/tracy-miranda-joins-cd-foundation-as-new-executive-director/

recent:///ef023092cd8d17d9f92971f45f7f31ef

**Comment by zestyroxy** [comment]
recent:///ef023092cd8d17d9f92971f45f7f31ef

**Comment by galemccommons** [comment]
Thanks - reopening the ticket with creative services.

**Comment by galemccommons** [comment]
Hi Roxy - creative services says this is fixed. Can you please check?

**Comment by zestyroxy** [comment]
Looks like it's been fixed! Thanks @galemccommons

**Comment by zestyroxy** [comment]
The same problem in happening when you look for a tag on the website. E.g. https://cd.foundation/tag/community-ambassador/

**Comment by galemccommons** [comment]
@zestyroxy apologies for the delay on this! is this still happening?

**Comment by tracymiranda** [comment]
Fixed but if you search and click on a tag the issues is the same https://cd.foundation/tag/community-ambassador/

**Comment by galemccommons** [comment]
Reopened the ticket and bumped CS on this.
--
Gale McCommons
Program Manager, Linux Foundation
E: ***@***.***
M: +1 210 367 1795
Book time with me: https://calendly.com/gmccommons/meeting

**Comment by galemccommons** [comment]
@zestyroxy @tracymiranda I am not able to replicate this issue. can you please send me a screenshot of what you're seeing happen? thank you!

**Comment by zestyroxy** [comment]
When you click this link, do you see a huge image? https://cd.foundation/tag/community-ambassador/ 

It's taking the featured image and blowing it up, but the image is usually small since it's for social media cards. The fix would be not to display the featured image with the text.

![ambassador post](https://user-images.githubusercontent.com/18251881/116452942-95e2e800-a85e-11eb-983f-9d54426f184c.png)

**Comment by zestyroxy** [comment]
But that's the problem, it doesn't display at upload size but bigger and pixelates the images. so b) is out.
a) could work (max 400 width)
But they managed to deactivate it for the blog page (which I assume was also a default behaviour), so I thought they could for this too.

**Comment by zestyroxy** [comment]
Linux Foundation CS Team added image width max to solve this. Thanks!
