### ISSUE TITLE
Guidance needed for Spinnaker.io Footer

### ISSUE THREAD

**Issue by dnilasor** [cdfoundation/foundation#211]
Hi. We're finalizing our footer for the new Spinnaker.io Hugo site. Do we have any standards or guidelines I should pay attention to, or any assets for me to pass on to the developer?

This is the Tekton footer:
![image](https://user-images.githubusercontent.com/36797588/89346653-46b8af80-d65e-11ea-99fa-f33e11bae37c.png)
which is pretty nice. Are we hoping to standardize these at any point, or do we just need to make sure we're checking the boxes on elements like logo and LF copyright statement? 

Here's our existing footer:
![image](https://user-images.githubusercontent.com/36797588/89347046-e4ac7a00-d65e-11ea-98ba-6b50361e4a03.png)

Please advise : ) @brianwarner

**Comment by brianwarner** [comment]
Hi @dnilasor - yep! Both have the things they need, and it's a great idea to standardize.

I just added some sample footer text to the artwork repo, should be pretty straightforward to copy and paste from here on out: https://github.com/cdfoundation/artwork

**Comment by dnilasor** [comment]
Thanks @brianwarner! @AmyGroshek see here ^^ for guidance from the CDF.
