### ISSUE TITLE
Trademark question raised in Google Ads on term "spinnaker" by Spinnaker Support org

### ISSUE THREAD

**Issue by dnilasor** [cdfoundation/foundation#212]
Hi @caniszczyk! CC @brianwarner. Hope you are very well. Can you assist with something that's arisen for Armory's compliant use of the search term "spinnaker"?

When we inquired about why our ads re: Armory for Spinnaker were being blocked, Google provided this contact info for the complainant:
- Trademark Terms: Spinnaker Support & Spinnaker
- Contact Email: mwilkinson@spinnakersupport.com
- Contact Name:  Michelle Wilkinson

We're aware of [their copyright](http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4801:jyn9nz.2.14) but the TM registry seems to indicate that their mark is "spinnaker support," with no mention of the independent use of the term "spinnaker." 

So I think we need:

1. A Linux Foundation representative to contact Michelle with verification that Armory is a member of CDF and is authorized to use the Spinnaker mark. 
2. LF/CDF to submit this authorization form to Google, authorizing us with Google Ads

Not super familiar with this process re: Google ads to, please advise if needed. Thanks!

![image](https://user-images.githubusercontent.com/36797588/89589253-21f93f00-d7fa-11ea-911f-871af21342ea.png)

**Comment by caniszczyk** [comment]
@dnilasor fascinating issue, I need to loop our legal team, we will get you a formal followup next week, this particular situation is a bit complicated due to the name overlap

**Comment by dnilasor** [comment]
Great, thanks for your help @caniszczyk !

**Comment by tracymiranda** [comment]
@caniszczyk @brianwarner was this resolved?

**Comment by dnilasor** [comment]
@tracymiranda not from my perspective. I would love an update on the processing of the TM application for Spinnaker, and have requested that the LF reach out to the complainant who contacted Google about our ads directly. We've asked for the CDF/LF validate our claim to using the mark per the LF's terms and request that they pursue unblocking of the Ads, since Google indicated that an unblock request would need to come from the complainant. 

I understand that the latter may depend on the former.

**Comment by dnilasor** [comment]
I sent the request and sample language for the complainant comms to Brian via Slack but I can share with others as I know his attention is not fully devoted to CDF at this point.
