### ISSUE TITLE
Zoom Passcode Requirements

### ISSUE THREAD

**Issue by fdegir** [cdfoundation/foundation#214]
Zoom [announced](https://support.zoom.us/hc/en-us/articles/360045009111-FAQ-Meetings-Waiting-Room-and-Passcode-Requirements-September-27-2020) that they will require passcode or waiting rooms to be enabled for all the paid accounts starting from September 27th.

I am wondering if this impacts the existing meetings we have (e.g. updating the meetings with passcode) or will they continue working?

**Comment by markyjackson-taulia** [comment]
If the meeting is not with passcode then the only thing that will chaing is introducing the waiting room where the host of a given meeting will need to allow people in the waiting room access to the meeting

**Comment by fdegir** [comment]
Thanks for the info. So we need to find who is the current host for our meeting series and ensure we are also made hosts if we aren't already.

/cc @MarckK

**Comment by MarckK** [comment]
I believe the CDF (or an individual at the CDF) is the current host.

**Comment by galemccommons** [comment]
Hi - the zoom rooms for the Outreach Committee, TOC, and Governing Board have been updated to include a passcode. We have "join before host" enabled so a host is not required to start a meeting.
