### ISSUE TITLE
Empty Posts WordPress

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#216]
On some days, Wordpress "Post" gets filled with untitled and empty blog posts. Any idea why this is happening and how to stop it? Jacqueline and I keep deleting them.
![drafts-wp](https://user-images.githubusercontent.com/18251881/93908119-8a46a600-fcfe-11ea-930b-b4677f40d3ff.png)

**Comment by galemccommons** [comment]
JIRA ticket submitted to LF creative services

**Comment by galemccommons** [comment]
Heads up -  this has been assigned and is being looked in to by the creative services team.

**Comment by zestyroxy** [comment]
+1 thanks!

**Comment by galemccommons** [comment]
Hi Roxy - creative services advised this issue has been fixed. Please let me know if you see this pop up again.

**Comment by zestyroxy** [comment]
Wonderful, thank you :+1:
