### ISSUE TITLE
Create Tekton Hub Logo

### ISSUE THREAD

**Issue by PuneetPunamiya** [cdfoundation/foundation#218]
Hello from Hub, can we have a logo for [tektoncd/hub](https://github.com/tektoncd/hub)

Tekton hub is a web based platform for developers to discover, share and contribute tasks and pipelines for Tekton

Can we have a logo for Hub

Hub Preview : https://hub-preview.tekton.dev/

**Comment by vdemeester** [comment]
One "idea" I have would be a can in front of a library or on top of a bunch of books or papers (:thinking:)

**Comment by dlorenc** [comment]
> One "idea" I have would be a can in front of a library or on top of a bunch of books or papers (🤔)

This should say "cat" right?

**Comment by tracymiranda** [comment]
I've added this to agenda for TOC meeting tomorrow, under 'pending project requests' 
https://docs.google.com/document/d/1uBHar55fTInWF9Li4t0lyG3tTC8BRLU0FfBfsgk_Jrs/edit?ts=5c9580be#

We just need to know what design ideas to move forward with and any deadlines to be aware off so let's discuss tomorrow then get the ball rolling on this.

**Comment by galemccommons** [comment]
Ticket submitted to LF creative services to get process started

-G

**Comment by tracymiranda** [comment]
(Internal reference: https://jira.linuxfoundation.org/browse/LP-6893)

**Comment by galemccommons** [comment]
[tekton_hub_logoconcepts_V1.pdf](https://github.com/cdfoundation/foundation/files/5598029/tekton_hub_logoconcepts_V1.pdf)

Hi team - please find attached a draft from our creative services team, and let me know your thoughts.

-G

**Comment by galemccommons** [comment]
@PuneetPunamiya @dlorenc do either of you have feedback on this? We'd like to get feedback over to the creative services team by Monday, 7 December. Thank you!

**Comment by chmouel** [comment]
Sounds good to me! although it describes more a catalog or a library than a hub, I think it look good to me!

**Comment by siamaksade** [comment]
I agree with @chmouel that the icon might be more suited for the catalog concept, as opposed to a hub which is a central place to pull content from multiple catalogs. 

Nitpicking here but regardless of the icon used for the hub concept, it might be worth to consider moving it to the left or right side of the cat to make sure the icon doesn't become vertically too long which is usually problematic on slides.

**Comment by galemccommons** [comment]
Thanks team! I've shared this feedback with our creative services team and will keep you posted.

**Comment by galemccommons** [comment]
@chmouel @siamaksade @dlorenc @PuneetPunamiya - do we have consensus on whether to keep the logo as designed _or_ to move the cat to one side?

Thanks!
Gale

**Comment by siamaksade** [comment]
@galemccommons my vote to move it to one side

**Comment by galemccommons** [comment]
@dlorenc - do you have any final feedback on the logo before we submit these change requests to creative services? thank you!

**Comment by nikhil-thomas** [comment]
how about a drooling cat, with cans of cat food around (or in hands). :nerd_face: 

or a cat with boots, batman's utility belt, chewbacca's cross belt. and a magic wand

**Comment by dlorenc** [comment]
> @dlorenc - do you have any final feedback on the logo before we submit these change requests to creative services? thank you!

No opinions from me!

**Comment by galemccommons** [comment]
@siamaksade @dlorenc please see revised logo attached. thank you!

[tekton_hub_logo_v2.pdf](https://github.com/cdfoundation/foundation/files/5765876/tekton_hub_logo_v2.pdf)

**Comment by galemccommons** [comment]
Thanks everyone! I will let the creative team know this logo is accepted, and close out this issue.

@jsalinas29 the Tekton Hub logo is finalized.

Thanks all!

**Comment by vdemeester** [comment]
Same question as https://github.com/cdfoundation/foundation/issues/198#issuecomment-774217616, can we get dashboard and hub image assets on https://github.com/cdfoundation/artwork/ 🙏🏼 

/cc @danlopez00

**Comment by galemccommons** [comment]
@vdemeester the new logos are here https://github.com/cdfoundation/artwork/tree/main/tekton/additional-artwork/tekton-hub

**Comment by PuneetPunamiya** [comment]
@galemccommons  Thank you for adding Hub logo :hugs:

**Comment by galemccommons** [comment]
@PuneetPunamiya you're welcome!
