### ISSUE TITLE
Add 'Best Practices' intro to CDF YouTube channel

### ISSUE THREAD

**Issue by tracymiranda** [cdfoundation/foundation#219]
Michael Galloway of Netflix recorded a clip on the Best Practices working group for CDCon that is part of the 'State of the Union' talk. However I would like to make it available as a standalone clip we can embed in landing page, docs, etc. so would need it uploaded on its own 

It is available in the Governing Board folder:
https://drive.google.com/file/d/1AGh0u-xjQ4t5sf39aMgO-wNFaOLhfe1q/view

**Comment by galemccommons** [comment]
Starting work on this

**Comment by tracymiranda** [comment]
Any update on this @galemccommons we would like to link in a public doc for Tuesday toc meeting.

**Comment by galemccommons** [comment]
The clip is uploaded at the below link. Please review and let me know if you would like any changes.

https://youtu.be/iw7_2ZEutHE

**Comment by tracymiranda** [comment]
Awesome, thanks that works!
