### ISSUE TITLE
Jenkins X: Request for a new groups.io mailing list

### ISSUE THREAD

**Issue by tracymiranda** [cdfoundation/foundation#22]
Jenkins X is bootstrapping a steering committee https://github.com/jenkins-x/steering and requires a mailing list for committee members to communicate. 

The initial list would be bootstrap members here https://github.com/jenkins-x/steering as well as myself @tracymiranda and @MarckK (Kara or I can share email addresses as necessary)

For name, something along the lines of this should work:
jx-steering

**Comment by tracymiranda** [comment]
Yes, that works well.

**Comment by danlopez00** [comment]
Completed: https://lists.cd.foundation/g/jenkinsx-steering

Please let me know if we need to update the settings for the list.
