### ISSUE TITLE
Update IBM GB rep

### ISSUE THREAD

**Issue by tracymiranda** [cdfoundation/foundation#220]
Peter Klenk replaces Shawn Clymer as IBM rep https://cd.foundation/about/governing-board/

**Comment by galemccommons** [comment]
@tracymiranda @jsalinas29 do either of you have Peter's headshot/bio? If no, I can reach out directly. Thanks! -G

**Comment by tracymiranda** [comment]
I do not, please reach out directly thanks @galemccommons

**Comment by galemccommons** [comment]
This is complete
