### ISSUE TITLE
Add outreach committee members to cd.foundation

### ISSUE THREAD

**Issue by kimsterv** [cdfoundation/foundation#24]
include headshots and short bios - similar format to board.

**Comment by danlopez00** [comment]
For reference: https://www.cncf.io/people/marketing-committee/

**Comment by jsalinas29** [comment]
@danlopez00 - clarifying question on who the members of the outreach committee are? I just want to make sure that if I need to reach out to everyone for bios and preferred headshots that I know who I need to talk to. Thanks!

**Comment by danlopez00** [comment]
per the CDF charter:

```
 Outreach Committee
a) The Outreach Committee will include one appointed voting representative from each Premier Member. Each General Member may appoint a non-voting representative to observe and contribute ideas to the Outreach Committee.
```

We can pull the latest fro SFDC

**Comment by danlopez00** [comment]
similar to https://www.cncf.io/people/marketing-committee/

**Comment by danlopez00** [comment]
In progress: https://github.com/cdfoundation/foundation/projects/1

**Comment by danlopez00** [comment]
The first version will entail all premier member marketing contacts, and the outreach chair

**Comment by danlopez00** [comment]
First pass is now live: https://cd.foundation/about/outreach-committee/

@jsalinas29 will also help maintain moving forward
