### ISSUE TITLE
SIG Interoperability meetings missing on CDF public calendar

### ISSUE THREAD

**Issue by fdegir** [cdfoundation/foundation#252]
SIG Interoperability meetings are no longer included on CDF public calendar. Has the occurence of it ended somehow?

https://calendar.google.com/calendar/u/0/embed?src=linuxfoundation.org_mhf0kmgedn67ihni8r129avp24@group.calendar.google.com&ctz=America/Los_Angeles

**Comment by tracymiranda** [comment]
Not sure, I have copied the instance to the CDF calendar again and it runs until Dec 24th. For 2021 we should create a new calendar instance as the old one (originally created via Zoom) was pretty problematic.

**Comment by fdegir** [comment]
Thanks for fixing it Tracy.
