### ISSUE TITLE
Update Fujitsu board rep

### ISSUE THREAD

**Issue by tracymiranda** [cdfoundation/foundation#253]
The Fujitsu board rep has changed

- [x] Update contact email in Salesforce
- [x]  Added to board meeting calendar invite
- [x]  Added to CDF Board calendar
- [x]  Added to CDF Board Google Drive
- [x]  Added to CDF cdf-gb mailing list
- [x]  Added to Governing Board
- [ ] Consider blog post announcment

**Comment by tracymiranda** [comment]
We received contact info & headshot so believe we have what we need now to update these.

**Comment by galemccommons** [comment]
@tracymiranda I am not an admin on the board calendar so I could not update access, but I did forward the invite.

-G

**Comment by galemccommons** [comment]
All steps completed
