### ISSUE TITLE
Governing Board Minutes for November meeting

### ISSUE THREAD

**Issue by tracymiranda** [cdfoundation/foundation#255]

**Comment by tracymiranda** [comment]
First draft done, I need to review

**Comment by tracymiranda** [comment]
Feedback on email voting due to go out this week.

**Comment by galemccommons** [comment]
completed and approved by board on 11 Feb 2021

**Comment by galemccommons** [comment]
reopening

**Comment by tracymiranda** [comment]
Posted https://github.com/cdfoundation/foundation/blob/master/governing-board/minutes/2020-11-12.md
