### ISSUE TITLE
Tekton Security Audit

### ISSUE THREAD

**Issue by tracymiranda** [cdfoundation/foundation#257]
Tekton project has requested a project security audit. This issue tracks progress towards that.

**Comment by tracymiranda** [comment]
Setting up discovery meeting with Tekton community & trailofbits to figure out scope, commitment, etc

**Comment by tracymiranda** [comment]
CDF Governing Board has approved the 2021 budget which means we can fund this audit this year.

**Comment by afrittoli** [comment]
At least myself and @vdemeester are available for an initial meeting to understand how the audit would work and what kind of commitment is required from the Tekton community side. @tracymiranda could you help setting up the initial meeting?
@bobcatfish might be interested to join too.

**Comment by tracymiranda** [comment]
I will set up a call with trailofbits folks for 11.30am Eastern Tuesday 22nd July. Please shout if this does not work!

**Comment by tracymiranda** [comment]
Tekton Security Audit planning doc - https://docs.google.com/document/d/1K5NYOHTVQicZeB2lrLJylO3InNBzICBuDjdU5HcQriE/edit#

**Comment by tracymiranda** [comment]
Kickoff meeting is schedule for 17th Feb at 12pm ET - calendar invite sent out to Tekton folks

https://docs.google.com/document/d/1K5NYOHTVQicZeB2lrLJylO3InNBzICBuDjdU5HcQriE/edit#

**Comment by fdegir** [comment]
Closing the issue since the Tekton Security Audit completed few months ago and Tekton is a graduated project now!

Thanks everyone for their help!
