### ISSUE TITLE
Create repo for personas

### ISSUE THREAD

**Issue by dnilasor** [cdfoundation/foundation#259]
Hi! I prepared this persona brief a while back and got some great feedback from our community to improve it:

https://github.com/dnilasor/outreach

I think it's ready to be added to the cdfoundation org. Can someone either give me permission to create a repo in the org, or else create a repo for this so I can submit a PR with my addition?

Thanks!

**Comment by tracymiranda** [comment]
Yes, we are setting up teams so will do an outreach team, add you to it and give access to the repo

**Comment by tracymiranda** [comment]
Updated version has been added: https://github.com/cdfoundation/outreach/blob/main/personas.md
