### ISSUE TITLE
Explain how cd.foundation store works

### ISSUE THREAD

**Issue by kimsterv** [cdfoundation/foundation#26]
Does CDF pay for initial inventory?
Who manages the store?
How do we realize revenue for sales?
What if companies want to buy their own swag?

**Comment by danlopez00** [comment]
- Does CDF pay for initial inventory?
   CDF pays for initial runs and stocking of storefront
- Who manages the store?
   The LF has contracted this service with an external team. This team supports all LF projects and foundations

**Comment by danlopez00** [comment]
- What if companies want to buy their own swag?
  To clarify, ex: "Acme Corp commercially supports and started Project ABC. Project ABC is now part of the CDF. Acme Corp wants to buy swag XYZ for a conference" Is this what you mean?

**Comment by danlopez00** [comment]
Some reporting from the Storefront team is available, and coordination has begun to get monthly or quarterly reports

**Comment by jsalinas29** [comment]
Does CDF pay for initial inventory?

- typically we submit a request for swag (stickers), send mock ups, order, then invoice (net 30) via bill pay

Who manages the store?

- self managed, pinnacle manages swag production to distribution but we have to submit request to restock. 
- for stickers we have a min number of 500 pieces and pinnacle pings us that we are running low on inventory before re-ordering
- we get monthly reporting and an inventory report at the beginning of each month and this is how we can also track

How do we realize revenue for sales?

- pinnacle creates a cost/we define the margin. Pinnacle collects the funds and deposits into a bank account that pinnacle manages and they can wire the money. They provide us all the rev and then at the end of the month they invoice us the shipping at the end of the month

What if companies want to buy their own swag?

- yes, they can (we should set up pinnacle as a vendor at cloudbees/netflix)
- they can pay via credit card and/or they can give CDF the money and we pay them
