### ISSUE TITLE
Graphic & Creative Design for cdCON

### ISSUE THREAD

**Issue by jsalinas29** [cdfoundation/foundation#263]

**Comment by jsalinas29** [comment]
- [ ] Branding assets for cdCON event website		
- [ ] Graphic & Creative Designs for cdCON CFP website	
- [ ] Graphics for email, social media	
- [ ] Graphics for keynote & speaker cards	
- [ ] cdCON promo video	
- [ ] cdCON speaker badges	
- [ ] Graphics for display ads	
- [ ] Pics from speakers due	
- [ ] cdCON welcome & navigation video

**Comment by jsalinas29** [comment]
@zestyroxy - could you help me with some of the graphic design for keynote/speaker cards, display ads?

**Comment by zestyroxy** [comment]
Will do! Any special requests?

**Comment by jsalinas29** [comment]
not really, I will let your creativity flow. I always love your stuff. Up to you!

**Comment by jsalinas29** [comment]
cdcon 2021 sponsor templates: https://www.canva.com/design/DAET-CgfrPA/ECHXQQgd7QEkO2I7ZXCcXA/view?utm_content=DAET-CgfrPA&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink
