### ISSUE TITLE
Community Bridge demo

### ISSUE THREAD

**Issue by kimsterv** [cdfoundation/foundation#28]
Present to the board.

**Comment by danlopez00** [comment]
Demo 1 of 2 provided to @danlopez00 as there are multiple sub-products with varying degree of GTM readiness. EasyCLA, Security, and Dev Analytics were demoed. Getting the next set of demos from the product team is scheduled for next week. A summary demo will be compiled and shared with the CDF

**Comment by danlopez00** [comment]
Update: CB is slated for a release in the next couple of weeks.  However, CDF now has 2 main URLs:

https://people.communitybridge.org/project/515e26a1-9e56-49e6-bb87-ce5544e8ee10
https://funding.communitybridge.org/projects/continuous-delivery-foundation 

These are only preliminarily setup and will take some time to refine and get the pages setup appropriately

**Comment by danlopez00** [comment]
Closing. Will open a new ticket when product teams are ready with updates
