### ISSUE TITLE
3rd Party Event Websites Promotion for cdCON 2021

### ISSUE THREAD

**Issue by jsalinas29** [cdfoundation/foundation#284]
- [x] Research publications w/event calendars | Roxanne | Deadline: Dec. 11, 2021
- [x] Reach out & confirm event calendar placements | Roxanne | Deadline: Jan. 10, 2021

**Comment by zestyroxy** [comment]
Created list and reached out: https://docs.google.com/document/d/1kmG_2ss4J-ytE3KUjosA1LSzmtBt_KqPAQsfEEzg6Lg/edit#

**Comment by jsalinas29** [comment]
great! ty, I've added this to the cdcon notes & also for the feb. 3rd mtg agenda to review.
