### ISSUE TITLE
BoF Sessions for cdCON 2021

### ISSUE THREAD

**Issue by jsalinas29** [cdfoundation/foundation#288]
- [ ] Confirm BoF topics | CDF Planning Outreach Committee | Deadline: Feb. 13, 2021
- [ ] Recruit 12 BoF moderators | CDF Planning Outreach Committee | Deadline: Mar. 29, 2021
- [ ] Publish topic & hosts | LF Events | Publish: April 15, 2021

**Comment by tracymiranda** [comment]
Need to figure out how many slots we have for projects/SIGs and sponsored topics

**Comment by jsalinas29** [comment]
- reach out to the chairs of SIG 
- assign topics
- reach out to community leaders

**Comment by jsalinas29** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSeWf6oM4plK6ow6MY3flObxeBplHnzNJ73ghPt-XNs3FyVhcQ/viewform
first come, first serve - folks will need to submit an application vs CDF chasing folks to particpate
