### ISSUE TITLE
Spinnaker YouTube access for Nikema Prophet

### ISSUE THREAD

**Issue by dnilasor** [cdfoundation/foundation#292]
Hi! Can you help me grant YouTube channel administrator access to @prophen for the Spinnaker YouTube account? I'd like to have some support on tasks like uploading Spinnaker Summit videos to the channel, and curating the content. I looked at the account and I am not able to authorize other administrators with my access.

**Comment by galemccommons** [comment]
@dnilasor do you have insight in to who owns the Spinnaker YouTube? We don't have ownership of this asset at LF. Thanks! -Gale

**Comment by tracymiranda** [comment]
@prophen did this ever get sorted?

**Comment by prophen** [comment]
> @prophen did this ever get sorted?

Hi, @tracymiranda. It has not been sorted as far as I know. I don't have access to the Spinnaker YouTube account.

**Comment by prophen** [comment]
@galemccommons, @tracymiranda any updates on this? We would like to get access to YouTube before we launch the updated website.

**Comment by galemccommons** [comment]
@prophen neither of us have access to the Spinnaker YouTube, and we are working to determine who is the owner that can add/update permissions.

**Comment by prophen** [comment]
> @prophen neither of us have access to the Spinnaker YouTube, and we are working to determine who is the owner that can add/update permissions.

Thank you, @galemccommons

**Comment by dnilasor** [comment]
I recommend trying to reach Rob Zienert at Netflix or Michael Plump at Google. Adam Jordens at Netflix may also have administrative access or knowledge of the person who does. Someone does because I was recently removed from the channel; when I did have access, I did not have privileges sufficient to add @prophen .

**Comment by galemccommons** [comment]
Thanks, Rosalind!
--
Gale McCommons
Program Manager, Linux Foundation
E: ***@***.***
M: +1 210 367 1795
Book time with me: https://calendly.com/gmccommons/meeting

**Comment by nikema-armory** [comment]
We can close this issue. I was able to get access by requesting it from Adam Jordens.

**Comment by tracymiranda** [comment]
Thanks for the update Nikema!
