### ISSUE TITLE
CDF Interoperability SIG Recordings

### ISSUE THREAD

**Issue by MarckK** [cdfoundation/foundation#293]
We are missing Interoperability SIG meeting recordings on [our YouTube channel ](https://www.youtube.com/playlist?list=PL2KXbZ9-EY9QxICOnONBFPn_cYfJ8BsaG) for 10 Dec, 2020 and 7 Jan, 2021.

Could these be added to the playlist?

@galemccommons

**Comment by galemccommons** [comment]
@MarckK sure thing! i'll get started on uploading these. -Gale

**Comment by MarckK** [comment]
Thank you, @galemccommons :)
