### ISSUE TITLE
Make CDF End User 2021 Plan available from cd.foundation 

### ISSUE THREAD

**Issue by tracymiranda** [cdfoundation/foundation#296]
Can we please add a button to https://cd.foundation/end-user-council/ that says 'Download 2021 Plan' which links to this pdf https://github.com/cdfoundation/end-user-council/blob/main/End%20User%20Council%20Plan%202021.pdf

**Comment by zestyroxy** [comment]
Updated: https://cd.foundation/end-user-council/

**Comment by tracymiranda** [comment]
Awesome, thank you!
