### ISSUE TITLE
Gutenburg Editor Disappeared - Wordpress

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#298]
In December, the Gutenberg editor disappeared from the CDF's wordpress. Can someone help bring it back?

**Comment by galemccommons** [comment]
@zestyroxy I have a ticket in with creative services to look in to this. I'll keep you posted!

internal reference: https://jira.linuxfoundation.org/browse/LP-7074

**Comment by tracymiranda** [comment]
This has been resolved.
