### ISSUE TITLE
Webcast/Webinar Link Redirect

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#299]
Can we redirect: https://cd.foundation/webinar to https://cd.foundation/webcast/

The webinar page is linked on old posts and now leads to a 404 since the page link was updated to `/webcast`

**Comment by galemccommons** [comment]
@zestyroxy this has been updated. thank you! :)

**Comment by zestyroxy** [comment]
Doh, sorry! the link was https://cd.foundation/webinars/ I forgot the s

**Comment by galemccommons** [comment]
Fixed!
