### ISSUE TITLE
Fund and build try.tekton.dev

### ISSUE THREAD

**Issue by caniszczyk** [cdfoundation/foundation#3]
We have had success in the past of building educational getting started tools for projects which I think would benefit tekton as an early project. See https://www.envoyproxy.io/try as an example, but we could essentially have a set of interactive labs like:

* Create your first pipeline
* Sharing a tekton task to the catalog
* etc (the tekton maintainers should come up with a set of tasks)

**Comment by danlopez00** [comment]
@caniszczyk what infrastructure would this ideally run. We are talking to Google about setting up a GCP account for CDF

**Comment by danlopez00** [comment]
GCP is now setup.  We have initial budget for this but we should work closely with the Tekton and Google team to maximize / optimize

**Comment by caniszczyk** [comment]
@danlopez00 this will be taken care of by the vendor who can build this, I sent the intro to the person and happy to share previous contracts

**Comment by danlopez00** [comment]
@caniszczyk is this a good candidate to use the Packet infrastructure?

**Comment by galemccommons** [comment]
@caniszczyk @tracymiranda is this still an active task, or are we good to close out this issue? thank you!
