### ISSUE TITLE
Create a CDF "popup" schedule for kubecon SD

### ISSUE THREAD

**Issue by kimsterv** [cdfoundation/foundation#30]
Create a schedule for kubecon participants to see one off demos of CDF projects in conjunction with company booths at Kubecon.
Some ideas for demos:
-CDF Landscape
-Tekton
-Jenkins/Jenkins X
-Spinnaker

**Comment by jsalinas29** [comment]
hi all - i've created a form to collect demo volunteers - https://forms.gle/diMoEBmBgyMf7vEa9
take a look and provide feedback of any missing fields. Once we finalize I can send out to the members. Thx

**Comment by jsalinas29** [comment]
closing this as only 2 ppl signed up for the demos (deployhub & whitesource)
