### ISSUE TITLE
Blog Title Line break too soon

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#301]
The titles of blog posts breaks too early and looks odd. Is there a way to fix this?
https://cd.foundation/blog/2021/02/05/celebrating-black-history-month-and-our-amazing-community/

![linebreak title](https://user-images.githubusercontent.com/18251881/108106380-2ac2ab80-708e-11eb-8d60-0f07acb8fa61.png)

**Comment by galemccommons** [comment]
@zestyroxy thanks for this report! 

internal reference link: https://jira.linuxfoundation.org/browse/LP-7224

**Comment by galemccommons** [comment]
@zestyroxy this has been updated to full width instead of a line break. can you please confirm you're good with this update?

**Comment by zestyroxy** [comment]
Yes, thank you!
