### ISSUE TITLE
Meeting recording and youtube channel for Events SIG

### ISSUE THREAD

**Issue by afrittoli** [cdfoundation/foundation#303]
The newly formed CDF Events SIG would like the recording of their meetings to be available in a dedicated youtube playlist, similar to what is already available for other SIG: [Best practices](https://www.youtube.com/watch?v=iw7_2ZEutHE&list=PL2KXbZ9-EY9SicnUcg9XMiq5nmXnVDJgb), [Interoperability](https://www.youtube.com/watch?v=7fVPnBVTMYA&list=PL2KXbZ9-EY9QxICOnONBFPn_cYfJ8BsaG).

The zoom meeting ID for the Events SIG is [976 6071 2600](https://zoom.us/j/97660712600?pwd=Z3BqYTE5YzNsbEhmck16cjdZNEFIUT09)

**Comment by tracymiranda** [comment]
@galemccommons can we please get this setup

**Comment by galemccommons** [comment]
@tracymiranda @afrittoli Hi team! I have the youtube channel set up. Are the recordings under "SIG: Events in CICD Workstream Meeting"? The recordings start in November. Would like to confirm before I start uploading. Thank you!

**Comment by afrittoli** [comment]
Thank you @galemccommons, it sounds good!

The group used to be called "Events in CICD Workstream" and it's now called "SIG Events".
It would be perfect to have all the meeting in the same channel / playlist. 

The name visible in youtube should be "SIG Events".

**Comment by afrittoli** [comment]
Thank you @galemccommons 🙏

**Comment by tracymiranda** [comment]
@afrittoli @e-backmark-ericsson are we ready to move forward here?

**Comment by afrittoli** [comment]
Thank you @tracymiranda, we are ready indeed.
We synced with @galemccommons via slack on this - forgot to update the ticket 🙏

**Comment by afrittoli** [comment]
@galemccommons any update on this? We did not see any recording in the youtube channel yet.

**Comment by afrittoli** [comment]
Thank you @galemccommons !
I can see one recording from the end of April. Do you have any update on more recent recordings and the past ones?
Thank you

**Comment by tracymiranda** [comment]
I believe this was resolved with afrittoli having access to zoom/youtube.
