### ISSUE TITLE
Latest Blog Posts Images - Home Page

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#309]
The blog gallery images on the cd.foundation homepage aren't square like the featured images, which means they get cut off. Can we update the homepage gallery to display square images?

Featured Image:
![blog post featured](https://user-images.githubusercontent.com/18251881/112008132-823cb700-8b25-11eb-8a79-86d27a8c1420.png)

Homepage 
![homescreen blog](https://user-images.githubusercontent.com/18251881/112007794-3d188500-8b25-11eb-8256-e1169debcfb5.png)

**Comment by zestyroxy** [comment]
Looks so good! Thanks 😍

**Comment by zestyroxy** [comment]
Can we also have the images link to the post when you click on them?

**Comment by galemccommons** [comment]
Sure thing, I'll update the CS ticket with this request.

Gale

**Comment by galemccommons** [comment]
@zestyroxy CS says this should be fixed. Please test and let me know. Thanks!

**Comment by zestyroxy** [comment]
It is! Works great! 

Can you ask them to exclude the "unpublished" and "in the news" post category on the homepage. Only the "blog" and "announcement" category should be featured there.
