### ISSUE TITLE
Swag Store - Small Bundle for Jenkins contributors

### ISSUE THREAD

**Issue by oleg-nenashev** [cdfoundation/foundation#311]
Hello,

As a Jenkin s project, we would like to be able to distribute small swag packages to the contributors. To simplify the process, we would like the swag kit to be available on https://store.cd.foundation/ and to include content from the CDF store. It woduld allow us to request swag and issue discount codes quickly without recreating the package on the store.

* 3 CDF stickers
* 3 Classic Jenkins stickers
* Jenkins Socks or a T-shirt (selection of a type and size)
* Nice 2 have: additional Jenkins stickers from https://www.jenkins.io/artwork/ , e.g. 3 extra sticker types of the same size as the Jenkins decal

We can cover the production and delivery costs from the Jenkins budget if needed.

**Comment by fdegir** [comment]
@oleg-nenashev could you please check [the Jenkins Swag Box](https://store.cd.foundation/products/jenkins-ui-ux-hackfest-swag-box) to see if this is good?

**Comment by micmarti85** [comment]
out of date 2021
