### ISSUE TITLE
Confusing Slack registration flow

### ISSUE THREAD

**Issue by oleg-nenashev** [cdfoundation/foundation#312]
Hello. After the recent Slack registration updates, it is difficult to register in the CDF Slack.

**Expected behavior**: Any community participants can register with their email.

**Actual behavior:** With the new Slack design it requires email from opsmx, and it confuses participants following the guidelines, e.g. listed here: https://github.com/cdfoundation/meetups#ask-for-help . It also leads to a confusion that CDF is owned by Ops Mx like one of our community members assumed after following the guidelines.

![image](https://user-images.githubusercontent.com/3000480/113590869-7e378b80-9633-11eb-9224-edbef38807d8.png)

**Comment by oleg-nenashev** [comment]
CC @galemccommons

**Comment by galemccommons** [comment]
@oleg-nenashev thanks for reporting this! I will take a look and update this issue when I have a solution or workaround. -Gale

**Comment by galemccommons** [comment]
@oleg-nenashev I updated the join link. Not sure why that one was requiring an opsmx domain, but it should no longer have this behavior. Can you confirm the new link is working appropriately on your end? thank you!

**Comment by oleg-nenashev** [comment]
Hi @galemccommons . I confirm there is no email domain requirement anymore. Thanks a lot for the fix!

**Comment by galemccommons** [comment]
Thanks!
--
Gale McCommons
Program Manager, Linux Foundation
E: ***@***.***
M: +1 210 367 1795
Book time with me: https://calendly.com/gmccommons/meeting
