### ISSUE TITLE
TOC Meeting Invite has run out

### ISSUE THREAD

**Issue by fdegir** [cdfoundation/foundation#313]
It looks like the invite for the TOC Meeting has run out.

https://calendar.google.com/calendar/u/0/embed?src=linuxfoundation.org_mhf0kmgedn67ihni8r129avp24@group.calendar.google.com&ctz=America/Los_Angeles

Could you please extend the invite?

**Comment by tracymiranda** [comment]
This has been restored for the next quarter.

**Comment by tracymiranda** [comment]
THanks for pointing this out!
