### ISSUE TITLE
[Nominations Open] Top GitOps Evangelist Award 2021 🏆

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#316]
This issue is to receive nominations for the Top GitOps Evangelist Award 2021

To nominate someone, reply to this issue with the following:

1. Full name of the person you’re nominating
2. Short description of what they’ve done to evangelize GitOps and why they should win.

Nomination deadline: Friday, April 30, 2021
**EXTENDED to Friday, May 14, 2021**

More details are available here: https://cd.foundation/cdf-community-awards/

**Comment by oleg-nenashev** [comment]
1. Kara de la Marck - @Marckk
2. For promoting best practices for secrets management in GitOps and Kubernetes, and also for promoting GitOps practices in Jenkins X. Here are some [literally] super-sweet slides by Kara from cdCon: https://speakerdeck.com/marckk/kara-de-la-marck

**Comment by cn-sunletian** [comment]
1. Sun Letian https://github.com/cn-sunletian
2.For promoting best practices for applications management in GitOps and Kubernetes. Inspur Cloud, based on GitOps concepts, has developed a deployment component called LCM to bond the connection between CI and CD in the pipeline
[Inspur GitOps practices](https://github.com/cn-sunletian/InspurGitOpsPractice/blob/main/GitOps.pdf)

**Comment by kgamanji** [comment]
Hello everyone 👋 I would like to self-nominate for the Top GitOps Evangelist Award 
1. Katie Gamanji @kgamanji 
2. For advocating the integration and usage of GitOps tools with the wider cloud native ecosystem. Some of the most prominent examples are the fusion of GitOps tools, ArgoCD and FluxCD, in infrastructure provisioning via Cluster API, and the application propagation to the edge via KubeEdge. 
Here is a list of talks delivered in the past few months:
  - [Continuous Lifecycle Online](https://www.continuouslifecycle.london/sessions/gitops-zero-touch-infrastructure-and-application-provisioning/)
  -  Keynote at [GitOps Days](https://www.gitopsdays.com/)
  - Keynote at [DevTalks Romania](https://www.devtalks.ro/)
  - [GitOps Summit](https://sched.co/il7I) 
  - [Akraino Technical Meetings (Spring) ](https://wiki.akraino.org/pages/viewpage.action?pageId=28976760) 
  - [Edge Computing World Europe](https://www.edgecomputingworld.com/edge-computing-world-2021-agenda/)

Including demos video:
- [KubeEdge & ArgoCD - The Power of GitOps to the Edge](https://youtu.be/Nc3hzd4YjdU)
- [Cluster API & FluxCD - the Power of GitOps](https://youtu.be/QbSw8dPhHGM)
- [ClusterOps - ClusterAPI and ArgoCD](https://youtu.be/9pFBgxDa7Aw)
- [ClusterOps: 1-line Commit to Upgrade Your Kubernetes Clusters](https://youtu.be/WwZhH_nfNy0)

And Medium articles:
- [ClusterOps: 1-Line Commit to Upgrade Your Kubernetes Clusters](https://medium.com/swlh/clusterops-1-line-commit-to-upgrade-your-kubernetes-clusters-de3548124d04)
- [ClusterOps: Manage Your Kubernetes Clusters With GitOps](https://medium.com/swlh/clusterops-manage-your-kubernetes-clusters-with-gitops-ac5622f11ac6)

**Comment by zestyroxy** [comment]
We are no longer accepting nominations. Thank you to everyone who nominated someone and good luck to the nominees!
