### ISSUE TITLE
<code> tag breaks paragraph

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#317]
Whenever there is code text in a paragraph it breaks the following line. Can you fix that in the css? 

Eg. <code>Secrets</code>
![code break](https://user-images.githubusercontent.com/18251881/114901200-dbda8d80-9e14-11eb-8c18-354099e826db.png)

**Comment by galemccommons** [comment]
Adding internal link for reference - 

https://jira.linuxfoundation.org/browse/LP-7404

**Comment by zestyroxy** [comment]
Here's an article I'm trying to replicate: https://www.jenkins.io/blog/2021/04/21/tekton-plugin/
I have a draft blog post on cd.foundation for it with the same title and it shows the <code> break bug, so Craig's team can test it there.
![tekton-jenkins](https://user-images.githubusercontent.com/18251881/117325012-a0ba0000-ae90-11eb-92c1-1fcc8c0d7ab2.png)

**Comment by zestyroxy** [comment]
Fixed! As seen here: https://cd.foundation/blog/2021/05/07/easily-reuse-tekton-and-jenkins-x-from-jenkins/
