### ISSUE TITLE
[Nominations Open] Most Valuable Jenkins Advocate 🏆

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#320]
This issue is to receive nominations for the Most Valuable Jenkins Advocate 2021. This award is presented to an individual who has helped advocate for Jenkins through organization of (a) local Jenkins Area Meet­up(s) or virtual equivalent.

To nominate someone, reply to this issue with the following:

1. Full name of the person you’re nominating
2. Short description of their contributions to the Continuous Delivery Foundation and why they should win.

Nomination deadline: Friday, April 30, 2021
**EXTENDED to Friday, May 14, 2021**

More details are available here: https://cd.foundation/cdf-community-awards/

**Comment by CyrilAll** [comment]
Mohamed Labouardy
First of all, he's a great guy :). And then, he wrote a book about Pipeline as Code with Jenkins (https://www.manning.com/books/pipeline-as-code). He published multiple blog posts on DZone, DevOps.com and on his personal blog and spoken about Jenkins at industry-leading events such as AllDayDevOps, DevSecOpsDays, ServerlessDays. He's also a great teacher on those topics and had taught me MANY things about it !!

**Comment by FeynmanZhou** [comment]
I would recommend [Rick Zhao](https://github.com/LinuxSuRen), he is extremely passionate about Jenkins and the community. Rick is the leader of the [KubeSphere](https://github.com/kubesphere) DevOps team and Jenkins Chinese Localization SIG. Meanwhile, he is committed to promoting CDF projects as a CDF ambassador and LFAPAC Open Source Evangelist. 

Oh, you may not know Rick has completed these remarkable jobs in advocacy and outreach:

- Share Jenkins stories with the audiences at the Kick-off meeting as an LFAPAC Open Source Evangelist.
- Record the free [Jenkins serial video tutorials (Chinese)](https://www.bilibili.com/video/BV1fp4y1r7Dd) for Jenkins novices,  which have 28 episodes. It gains 6113 hits so far.
- Promote Jenkins blog and news on WeChat subscription which has +15k subscribers.
- Submit a Jenkins CLI-related proposal to [Open Source Promotion Plan](https://summer.iscas.ac.cn/#/org/orgdetail/jenkins), OSPP is a similar program to GSoC in China.
- Organize Jenkins workshops and meetups to gather Jenkins users together.
- Organize contributors and volunteers to [translate blogs](https://github.com/jenkins-zh/jenkins-zh/issues?q=is%3Aissue+is%3Aopen+label%3Akind%2Ftranslation) in Jenkins Chinese Community, which helps Jenkins to be widely adopted in China.

**Comment by daniel-beck** [comment]
**Oleg Nenashev**

@oleg-nenashev has been a very active contributor to Jenkins for the better part of a decade and joined the Jenkins board in the first election in 2019.
From the beginning, he's been an active advocate for Jenkins, heavily involved in every outreach and advocacy program we have:

* He's been both org admin and mentor in Google Summer of Code every time we participated.
* He's planned our Google Season of Docs participation and was a mentor and org admin in 2020.
* He's been running both local and online meetups for years, including a dozen or more in 2020 alone.
* He's driving the Jenkins governance meeting and setting its agenda.
* He's one of the folks running the Jenkins Twitter and LinkedIn accounts, promoting Jenkins whenever possible.
* He's driven the Jenkins graduation process in the CD Foundation, which included Code of Conduct updates and Core Infrastructure Initiative certification.
* He's introduced and is maintaining the public roadmap of Jenkins.
* He's the lead on Jenkinsfile Runner, a project that makes Jenkins Pipelines available as a reusable command line component for any other environment.
* He's growing the Jenkins core maintainers team by onboarding new contributors and documenting our many "you had to be there" processes and conventions.

Beyond that, he's a maintainer of Jenkins core and several related components, and helps out with many more whenever a need arises, as well as a contributor of the Jenkins security and infra teams.

I'm sure I left some stuff out, but that's expected with Oleg -- there's just too much going on 😉

**Comment by oleg-nenashev** [comment]
I would like to also nominate *Darin Pope* (@darinpope)

* Darin is the co-host of the [DevOps Paradox]()https://www.devopsparadox.com/ podcast with a lot of DevOps and CI/CD focused topics. Jenkins and Jenkins X topics are also covered
* Darin is an active evangelist who creates great learning materials about Jenkins, e.g. [Jenkins Tutorials] (https://www.youtube.com/playlist?list=PLvBBnHmZuNQJeznYL2F-MpZYBUeLIXYEe) and [Jenkins Plugin Developer](https://www.youtube.com/playlist?list=PLvBBnHmZuNQIb4p2t69dgMQyGbzb8qr4T) series
* Darin is an author of multiple blogposts about Jenkins, e.g. [this one](https://www.cloudbees.com/blog/top-10-best-practices-jenkins-pipeline-plugin)

**Comment by oleg-nenashev** [comment]
Although I have already done one nomination, I believe it would be unfair if **Mark Waite** (@MarkEWaite) was not nominated. Mark joined the Jenkins community in Hudson time, and he has been invaluable Jenkins contributor and advocate ever since. I would like to nominate Mark for the 2021 award. Even if I have a potential conflict of interest (Mark is my manager at the moment), I cordially believe this nomination is well deserved.

Just to mention a few recent contributions:

* Coordinating and contributing to many Jenkins outreach programs, including SheCodeAfrica, Google Season of Docs, Hacktoberfest 2020, Jenkins UI/UX Hackathon, etc.
* Hosting and organizing dozens of [Jenkins Online Meetups](https://www.meetup.com/Jenkins-online-meetup/)
* Co-leading the Jenkins [Advocacy and Outreach SIG](https://www.jenkins.io/sigs/advocacy-and-outreach/)
* Spreading the word about recent Jenkins LTS releases and changes inside them, at meetups and podcasts
* Speaking about Jenkins and representing it at many conferences, including but not limited to DevOps World, Jenkins World, cdCon, FOSDEM, STAREAST, etc.
* Doing many trainings and workshops about Jenkins and @CloudBees Jenkins-based products
* Contributing to Jenkins Twitter and LinkedIn social media management
* Helping Jenkins users in many community channels including social media, chats, mailing lists, and issue trackers
* Leading the Jenkins Documentation SIG and coordinating many projects around Jenkins documentation improvements. Good documentation is mission critical for Jenkins advocacy

Thanks a lot for all your contributions @MarkEWaite!

**Comment by mitesh51** [comment]
Hi, I am Mitesh Soni (https://www.linkedin.com/in/mitesh-s-136842b/). I am CD Foundation Community Ambassador. As a part of the Culture transformation initiative, I spread awareness about Jenkins 2.0 specially Pipeline as a Code in my current organization and help different projects to adopt Jenkins Pipelines. I also give training inside the organization and share my knowledge about Jenkins and DevOps. 
Following are some of my contributions:

**Books:**

1. [Hands-on Pipeline as Code with Jenkins: CI/CD Implementation for Mobile, Web, and Hybrid Applications Using Declarative Pipeline in Jenkins](https://www.amazon.com/gp/product/B08WJ99GJF)
2. The upcoming book is on Pipeline as YAML - Jenkins

**Articles:**

1. Rule of Three: Jenkins Pipeline as Code - https://cd.foundation/blog/2020/08/04/rule-of-three-jenkins-pipeline-as-code/
2. Pipeline as a Code: A Brief Look at Blue Ocean: https://devopsinstitute.com/pipeline-as-a-code-a-brief-look-at-blue-ocean/ 
3. Top 10 Open Source Tools for DevOps: https://www.opensourceforu.com/2021/04/top-10-open-source-tools-for-devops/
4. Building the DevOps Pipeline with Jenkins: https://www.opensourceforu.com/2020/07/building-the-devops-pipeline-with-jenkins/
5. Understanding Continuous Integration and Continuous Delivery/Deployment: https://www.opensourceforu.com/2020/06/understanding-continuous-integration-and-continuous-delivery-deployment/
6. TOP 10 OPEN SOURCE TOOL FOR DEVOPS – JENKINS https://etutorialsworld.com/top-10-open-source-tool-for-devops-jenkins/
7. The Role of Nudges in DevOps Implementations https://devopsinstitute.com/the-role-of-nudges-in-devops-implementations/

**Comment by zestyroxy** [comment]
We are no longer accepting nominations. Thank you to everyone who nominated someone and good luck to the nominees!
