### ISSUE TITLE
Conduct toc election for project seats

### ISSUE THREAD

**Issue by tracymiranda** [cdfoundation/foundation#322]
4 of the 9 TOC seats are selected from CDF project representatives as per charter:

i) four representatives nominated by, and voted upon, by the technical oversight body (e.g., a technical steering committee) of the TOC Projects (as defined herein). Each TOC Project may nominate a maximum of one project representative to run for these seats.

This issue tracks work towards running the election for these 4 seats in 2021.

**Comment by tracymiranda** [comment]
Process to be put here: https://github.com/cdfoundation/toc/blob/master/elections/2021/README.md

**Comment by tracymiranda** [comment]
Expanded to include election of 2 seats elected by board members. 
Voter list to come from LFX insights 

Updated election process https://github.com/cdfoundation/toc/tree/master/elections/2021

**Comment by oleg-nenashev** [comment]
The Jenkins community has reviewed the potential candidates and nominated Oleg Nenashev (me) as the CDF TOC Project Representative candidate from Jenkins. You can find the full track of the conversation in the Jenkins developer mailing list: https://groups.google.com/g/jenkinsci-dev/c/N0stgWNmPhg .The decision was signed off at the Jenkins Governance Meeting on May 05.

Please let us know if any additional information is needed.

**Comment by tracymiranda** [comment]
Great, thanks! @oleg-nenashev please have Jenkins community submit the candidate info via https://forms.gle/7HMHeTif1RF6dsUx8

**Comment by oleg-nenashev** [comment]
Ack, thanks! We will need a nomination statement before submitting it

**Comment by tracymiranda** [comment]
2021 TOC election is complete: https://cd.foundation/blog/2021/06/23/continuous-delivery-foundation-announces-new-technical-oversight-committee-members/
