### ISSUE TITLE
Wordpress Login Fails

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#326]
Nearly every time I try to login to WordPress, it fails multiple times (even though I have the correct password). And I spend 30 minutes waiting and trying over and over again.

Login page: https://cd.foundation/wp-admin/

I've tried:
- clearing cookies
- removing ad-blocker
- restarting my computer
- using a different browser
- using an incognito window

Sometimes restarting or a different browser works but not consistently. 

Here's the error I receive:
![wordpress](https://user-images.githubusercontent.com/18251881/116381252-01a06300-a815-11eb-857d-610e32951533.png)

**Comment by galemccommons** [comment]
Created https://jira.linuxfoundation.org/browse/LP-7393

**Comment by tracymiranda** [comment]
Resolved and works for now.
