### ISSUE TITLE
[Nominations Open] Top GitOps End User Award 2021 🏆 

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#327]
This issue is to receive nominations for the Top GitOps End User Award 2021.

To nominate a company, please fill out this form: https://forms.gle/puWX2N5L1vreDyDa9

You may still comment below with who you're nominating!

Nomination deadline: Friday, May 14, 2021

More details are available here: https://cd.foundation/cdf-community-awards/

**Comment by oleg-nenashev** [comment]
I would like to nominate the CloudBees’ operations team and CloudBees as a company for the Top GitOps End User Award. Although the team is called “operations”, in fact it is a cross-functional team participating in all aspects of product development, internal infrastructure and SaaS services.

What does the team do?

* Promoting InnerSource, DevOps and GitOps principles across the internal organization
* Making Infrastructure as Code and declarative definitions a company standard (Terraform, Declarative Kubernetes object configurations, etc.)
* Adopting continuous deployment for the majority of services, including the websites, documentation portals, SaaS products, and the internal infrastructure, etc.
* Empowering the teams to manage their team services on their own
* Sharing experiences and best practices inside and outside the company

Kudos to the team!

**Comment by zestyroxy** [comment]
Thank you for your nominations @cn-sunletian and @oleg-nenashev. Can you email me social@cd.foundation with emails on how to contact someone at the company you nominated?

**Comment by zestyroxy** [comment]
We are no longer accepting nominations. Thank you to everyone who nominated someone and good luck to the nominees! (Reminder @cn-sunletian and @oleg-nenashev to message me)
