### ISSUE TITLE
[Nominations Open] Top CDF End User Award 2021 🏆 

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#328]
This issue is to receive nominations for the Top CDF End User Award 2021.

To nominate a company, fill out this form: https://forms.gle/puWX2N5L1vreDyDa9

You may still comment below with who you're nominating!

Nomination deadline: Friday, May 14, 2021

More details are available here: https://cd.foundation/cdf-community-awards/

**Comment by oleg-nenashev** [comment]
I would like to nominate SalesForce for the Top CDF End User 2021 Award. There are the following reasons for nomination:

- Widely adopting continuous integration, delivery and deployment in the organization.
- Contributing back to the CD-related open source projects, and starting or open-sourcing many projects: https://opensource.salesforce.com/
- Providing and maintaining public documentation about using developer tools for Continuous Integration and Delivery of Salesforce modules, e.g. https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ci_jenkins.htm 
- Promoting continuous delivery for its developer ecosystem, e.g. https://medium.com/@karthick.shanmugam0689/continous-differential-deployment-with-salesforce-dx-and-jenkins-24ab3192163f 
- Active participation in the open source communities. Special thanks to @justinharringa for participating in the Jenkins community, mentoring students, and sharing his experiences on many topics.
- Supporting the Continuous Delivery Foundation and its projects via CDF membership, and participating in the CDF SIGs and events

**Comment by zestyroxy** [comment]
We are no longer accepting nominations. Thank you to everyone who nominated someone and good luck to the nominees!
