### ISSUE TITLE
Approve shared channel for the joint LFX Security, Snyk and Jenkins project

### ISSUE THREAD

**Issue by oleg-nenashev** [cdfoundation/foundation#330]
We'd like to establish a shared channel between the Linux Foundation, Snyk  and Jenkins for LFX Security evaluation. Unfortunately, I cannot accept a shared channel invitation in this workspace. This workspace would be the best option, because other CDF projects may want to join LFX Security 2 pilot project as well

Link for the discussion in the devlist https://groups.google.com/g/jenkinsci-dev/c/lIeGyefi1Y4

![image](https://user-images.githubusercontent.com/3000480/117183499-e8c91c00-add7-11eb-8295-b297ef401514.png)

CC @olblak @MarkEWaite @tracymiranda

**Comment by tracymiranda** [comment]
Is the requirement here to create a channel in CDF Slack for discussing LFX security integration for CDF projects?

I believe we can't set up shared Slack channels as we use a free account (it only works for standard/plus plan). If we simply set up a channel that we invite people too does that meet the requirements for what you are after?

**Comment by oleg-nenashev** [comment]
@tracymiranda Snyk has an enterprise account, so it should be possible to join their channel if you accept the invitation.
I am not sure what is the exact process though

**Comment by oleg-nenashev** [comment]
Started a thread with Wendy and CCed you @tracymiranda

**Comment by oleg-nenashev** [comment]
No longer relevant, we created a new channel instead
