### ISSUE TITLE
Person Profile: Space Missing Between Icons

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#331]
I created a new "person" today, Fatih Degirmenci, and added him to the list of people on the TOC. There's a weird non-existent space between his two social media icons. Can we add one using CSS?

Page to see issue: https://cd.foundation/about/toc/
![space between icons](https://user-images.githubusercontent.com/18251881/117324801-6cdeda80-ae90-11eb-9681-0f32287515a2.png)

**Comment by galemccommons** [comment]
Thanks, Roxanne! Linking [internal jira](https://jira.linuxfoundation.org/browse/LP-7522) for reference.

**Comment by galemccommons** [comment]
@zestyroxy CS added padding to the icons. Can you check and make sure you're good with the changes? Thank you!

**Comment by zestyroxy** [comment]
Looks great! Can they do it for these pages too? Or hard code it for the entire website.
https://cd.foundation/about/governing-board/
https://cd.foundation/ambassador-program-overview-application/community-ambassador-cohort20/

**Comment by galemccommons** [comment]
Asking now 😄

**Comment by galemccommons** [comment]
@zestyroxy they could not add the change for the entire site, so they added the padding for those two pages. let me know if that works.

**Comment by zestyroxy** [comment]
Thank works! Thank you all
