### ISSUE TITLE
Transfer of the Jenkins AWS account to the Continuous Delivery Foundation

### ISSUE THREAD

**Issue by oleg-nenashev** [cdfoundation/foundation#332]
After completion of the Jenkins Infrastructure Azure accounts transfer to the Continuous Delivery foundation, we would like to do the same with the AWS account.

Currently the Jenkins account for AWS is owned by CloudBees, and it complicates external sponsorship like this one:  https://www.jenkins.io/blog/2020/06/17/infra-and-aws-donation/ . It also does not allow adding non-CloudBees employees to to the account as administrators, hence the Jenkins infrastructure team cannot apply the common management process there and onboard more contributors.

We would like to ask the Continuous Delivery Foundation to accept ownership of the account. It does not involve additional costs for the foundation, because the account is fully sponsored by Jenkins company contributors.

CC @olblak @bwalding @tracymiranda @uhafner @ewelinawilkosz @kohsuke @halkeye

**Comment by tracymiranda** [comment]
This makes sense - we need to see what it would take to make the transfer and manage this at CDF so let me look into this.

**Comment by fdegir** [comment]
@oleg-nenashev I'm not sure where we are with this. Where can we learn more about what needs to be done?

**Comment by timja** [comment]
cc @dduportal

**Comment by oleg-nenashev** [comment]
Let's discuss it at the next infrastructure meeting. I will try to join.
The short answer is that the foundation is yet to establish the
infrastructure and the permission model that would allow us to transfer the
infrastructure. There is no other solution available at the moment

**Comment by fdegir** [comment]
@oleg-nenashev We are piloting something similar in collaboration with LFIT and Tekton Community to come up with a permission model for GCP. You can see what they recommended and what we are trying [here](https://github.com/cdfoundation/foundation/issues/359#issuecomment-1205767506).

If it makes sense, I can go and ask LFIT to see if they have a similar recommendation for AWS.
