### ISSUE TITLE
Tekton zoom subaccount

### ISSUE THREAD

**Issue by afrittoli** [cdfoundation/foundation#333]
The Tekton project would like to have a zoom sub-account to run the meetings of the Documentation Working Group - and potentially more working groups in the future.

**Comment by afrittoli** [comment]
Hello @galemccommons @tracymiranda - is there any progress on this? 
We'd like to start the Tekton Docs WG again - but we have a dependency on the zoom account.
Thank you!

**Comment by galemccommons** [comment]
Hi @afrittoli! I had a few quick follow-up questions:

- Has the day and time been decided for the working group so that I can set these when I create the zoom link?
- What would you like for me to use for the full name of the zoom room? "Tekton Docs WG"?
- Will this meeting be recorded?

Thank you!
Gale

**Comment by afrittoli** [comment]
Hi @galemccommons - we do have a date and time for the docs WG.

Would it be possible to have a sub-account assigned to the Tekton project instead?
That way we could maintain the date and time of our meetings on Tekton side, manage recordings and add more WG when needed (for instance the dashboard WG has already mentioned they'd be interested too).

**Comment by galemccommons** [comment]
Hi @afrittoli absolutely! Can you please slack me your preferred email address so that I may share the credentials with you over LastPass? Thank you!

**Comment by galemccommons** [comment]
@afrittoli per our Slack, this account has been created and shared with you directly.
