### ISSUE TITLE
I will be joining cdCon with...

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#334]
There are perks to virtual conferences.
Tell us who will be joining you the week of June 22 for [cdCon](https://events.linuxfoundation.org/cdcon/), [GitOps Summit](https://events.linuxfoundation.org/gitops-summit/), [Spinnaker Summit](https://events.linuxfoundation.org/spinnaker-summit/) or [Jenkins Contributor Summit](https://www.jenkins.io/events/contributor-summit/)!

**Comment by zestyroxy** [comment]
I will be joined by my "too-many plants" and will be drinking chai.
![PXL_20210609_163918277 MP](https://user-images.githubusercontent.com/18251881/121395322-96d56200-c952-11eb-85b6-c563dfb535d5.jpg)

**Comment by zestyroxy** [comment]
I will be joined by my "too-many plants" and will drink chai.
![plants-roxy](https://user-images.githubusercontent.com/18251881/121395543-d603b300-c952-11eb-8508-5fc682ecfc1f.jpg)

**Comment by tracymiranda** [comment]
These piggies may drop in to up their delivery game
![116111912_755517528533180_4527730509159493542_n](https://user-images.githubusercontent.com/5173122/121399941-fae13180-c924-11eb-9476-ef7c18dc6dc0.jpg)

**Comment by jsalinas29** [comment]
![6F52A2D1-B471-482F-A53B-B224B570B08B_1_105_c](https://user-images.githubusercontent.com/54957621/121402040-55908280-c951-11eb-89c8-0595e86f943c.jpeg)

Bella will be joining from bed.

**Comment by erkist** [comment]
I will be joined by my friend and architect-in-crime Piret

![IMG_20210611_150743970](https://user-images.githubusercontent.com/17197212/121691395-3ddb0a80-cac7-11eb-8952-1e25a0215b63.jpg)

**Comment by tracymiranda** [comment]
Thanks all for these and #cdconBestinShow pics, was great fun to welcome all the furry pals.
