### ISSUE TITLE
Update TOC page to reflect new TOC members

### ISSUE THREAD

**Issue by tracymiranda** [cdfoundation/foundation#337]
As of July 1 the TOC is:

- Garima Bajpai
- Jithin Emmanuel
- Andrea Frittoli
- Jason Hall
- Melissa McKay
- Oleg Nenashev
- Steve Taylor
- Fatih Degirmenci
- Dan Lorenc

The TOC page needs updating to reflect the current members: https://cd.foundation/about/toc/

**Comment by zestyroxy** [comment]
Updated

**Comment by tracymiranda** [comment]
Thank you!
