### ISSUE TITLE
Add a CDF Staff Page

### ISSUE THREAD

**Issue by tracymiranda** [cdfoundation/foundation#338]
Under 'About' menu would be great to have a staff page so folks know who-is-who e.g. https://www.cncf.io/people/staff/
and reflect the onboarding guide:
https://docs.google.com/presentation/d/12sp2cdiu2if5aWr4ro3ygXhiS2xHM47A6kEMApiv0F0/edit#slide=id.g502e72928c_0_113

**Comment by zestyroxy** [comment]
Done! https://cd.foundation/about/staff/

**Comment by tracymiranda** [comment]
Looks great!
