### ISSUE TITLE
Large amount of spam companies on the CDF Job Board

### ISSUE THREAD

**Issue by obowersa** [cdfoundation/foundation#346]
Not sure who to flag it to, but I noticed a bit of spam on the CDF Job Board, some not 100% SFW:

https://jobs.cd.foundation/employers/927588-miss-rubi
https://jobs.cd.foundation/employers/916435-poojarathoremodel
https://jobs.cd.foundation/employers/928666-priya-rawat
https://jobs.cd.foundation/employers/911177-rahat-company
https://jobs.cd.foundation/employers/911765-rahat-company
https://jobs.cd.foundation/employers/911141-rahat-company
https://jobs.cd.foundation/employers/910964-rahima
https://jobs.cd.foundation/employers/926306-roboswalker
https://jobs.cd.foundation/employers/927337-silky-gupta
https://jobs.cd.foundation/employers/912208-medicalsparx
https://jobs.cd.foundation/employers/933827-jessicabyrne11
https://jobs.cd.foundation/employers/913696-myactivetribe
https://jobs.cd.foundation/employers/933631-hp-printer
https://jobs.cd.foundation/employers/933531-hp-printer
https://jobs.cd.foundation/employers/917852-fantasy-power-11
https://jobs.cd.foundation/employers/916614-email-setting
https://jobs.cd.foundation/employers/934538-education
https://jobs.cd.foundation/employers/935027-dissertation-writer
https://jobs.cd.foundation/employers/931698-canon-printer-setup
https://jobs.cd.foundation/employers/935044-best-online-tech-support
https://jobs.cd.foundation/employers/932798-alinabeth
https://jobs.cd.foundation/employers/914917-sonclark

I think that's the majority of it.

**Comment by tracymiranda** [comment]
Thanks, good spot - these have now been deleted and we've set up some filters on the domains so hopefully this will help in future.
