### ISSUE TITLE
Artwork for CDEvents

### ISSUE THREAD

**Issue by tracymiranda** [cdfoundation/foundation#348]
This issue tracks the artwork request for the CDEvents intitative from the CD Events sig

**Comment by afrittoli** [comment]
> I agree with you Andrea. The rounded edges on both letters and waves (and antenna tip of 'd') looks better. I'd like to see an alternative where the waves are not tapered but still rounded, like it is in this proposal: ![image](https://user-images.githubusercontent.com/19428320/139198324-3d24ddb5-aedf-48c4-9f9e-a26b47ac6271.png) 

We'd like to also have a stacked version of this logo as well: ^^^

**Comment by tracymiranda** [comment]
Let me know if folks have all had a chance to weigh in and the group has reached consensus about how to move forward. If you can provide the feedback summary I'll pass that onto the designer for the next iteration.

**Comment by e-backmark-ericsson** [comment]
@tracymiranda , here is a summary of our latest comments, that could now be provided to the logo designers:

- We currently like the blue/green color scheme best, but you could try some more ones if you like as well
- We'd like rounded edges on both letters and waves, so please provide a selection of different fonts where all (or most) have rounded edges
- The line thickness on the waves should probably be equal to the thickness of the characters in "cd", and not tapered, to make them seem to be part of the same font
- The waves could maybe be a bit more dominant/large, and could even partly be hidden below the lines of the 'c' and the first 'e' if that makes sense
- We like both a horisontal version, a stacked version (where "events" is below "cd" and the waves are still on the 'd' in "cd"), and also an icon version where the "events" text is omitted

**Comment by tracymiranda** [comment]
Thanks, can confirm feedback has been passed on and will keep you posted on any questions/updates.

**Comment by tracymiranda** [comment]
Apologies for the delay - here are variants from the designer: "I created a lot just because I am a bit unsure about what they want for the waves so thought this would help. Let me know any feedback when you have a chance!"
[cd-events-logo_v3-1.pdf](https://github.com/cdfoundation/foundation/files/7847192/cd-events-logo_v3-1.pdf)

**Comment by erkist** [comment]
Top right gets my vote, and I would be fine with sticking with it.

If we want to keep experimenting, I would be interested in a variant of row3-col1 with slightly thinner "cd" letters and slighly thinner "waves", and exactly the same letter coloring as the top right one.

**Comment by e-backmark-ericsson** [comment]
I agree with @erkist that the top right one is probably the nicest. I could put my final vote on that one.

**Comment by m-linner-ericsson** [comment]
Agree, I would vote for the top right one.

**Comment by e-backmark-ericsson** [comment]
We had a closer look at the latest proposal (cd-events-logo_v3-1.pdf) during a meeting in the SIG yesterday. We believe a combination of the top right (row1:col2) and the left one on the third row (row3:col1) would be best.

- We like the shorter stem on the 'd' in r3:c1
- We like the font in r1:c2
- We think the waves should be aligned to the left with the 'c', as in r3:c1, and to provide that the waves could be a little less tight/packed
- We believe the weight/thickness of the waves should be equal to that of 'cd'
- If we should have a stacked version with all text in it we believe the text "events" should be placed under "cd", left-aligned
- An minimal version should be created that does not have the word "events" in it (alt 1 below), and maybe with only the leftmost waves in it (alt 2 below)
- There should also be a monochrome/black version of all three logos

We tried to summarize and sketch these comments using MS Paint below
- Horizontal version:
![image](https://user-images.githubusercontent.com/19428320/149124837-475a5c86-526c-4d3a-8951-8b5990d99cd8.png) 
- Stacked version:
![image](https://user-images.githubusercontent.com/19428320/149124964-fdc82f57-89dc-4c3f-85eb-0b1e485999bb.png) 
- Minimal version, alt 1:
![image](https://user-images.githubusercontent.com/19428320/149125026-e3436298-6608-452d-978a-04663e96b9ff.png) 
- Minimal version, alt 2:
![image](https://user-images.githubusercontent.com/19428320/149125073-e0e6220f-a7d8-406d-9b87-ff80ba5d3247.png) 

Please make a final (?) round of proposals based on this input
cc @tracymiranda

**Comment by oleg-nenashev** [comment]
FWIW Minimum version could be made even smaller, especially for favicons
Otherwise the proposed logos and the color scheme look good to me

![image](https://user-images.githubusercontent.com/3000480/149320072-96bead32-eff8-43cf-8699-eb53f2edd4ba.png)

**Comment by tracymiranda** [comment]
I have attached a page with the logos based on the feedback, let us know if these work!

[cd-events-logo_v4.pdf](https://github.com/cdfoundation/foundation/files/7884453/cd-events-logo_v4.pdf)

**Comment by afrittoli** [comment]
Thanks for the quick turnaround @tracymiranda 
For the minimal version I'd prefer alternative 2.
Will we get black, white and colour versions like for each of the three logos, like for other logos in https://github.com/cdfoundation/artwork?

**Comment by MarckK** [comment]
These look great! 
Are we looking to make a choice between the 2 options large and 2 options smaller/minimal, or accept all 4 designs?

**Comment by m-linner-ericsson** [comment]
I accept this. I would also vote for the same as @e-backmark-ericsson

**Comment by oleg-nenashev** [comment]
The logos look good to me 👍

**Comment by e-backmark-ericsson** [comment]
As a representative for SIG Events I can now say that we accept these proposals as they are! The SIG has had some days to reflect on the proposals and no complaints/concerns have been raised, so they can be considered accepted by now.

So, top one is the horizontal version, middle one is the stacked version, and lower right one is the icon version we've decided on.

**Comment by MarckK** [comment]
Hi @e-backmark-ericsson, 
I have let the design team know that you all are happy with the logo designs as they are and of the minimal versions the team prefers the more square, second alternative.

@afrittoli 

> Will we get black, white and colour versions like for each of the three logos, like for other logos in https://github.com/cdfoundation/artwork?

I've asked to ensure that this is the case. :)

These CD Events logos look great y'all! 🎉

**Comment by MarckK** [comment]
📯 Hi all,

CD Events logos have been added to CDF artwork repo! 
They can be found in their own directory here: https://github.com/cdfoundation/artwork/tree/main/cdevents
And you can see them [amongst all the CDF logos on the ReadMe](https://github.com/cdfoundation/artwork).

🎉  🎉  🎉

Please review and if there are no issues, I'll be closing the request with the LF design team. Thanks!

**Comment by afrittoli** [comment]
Great news, thank you @MarckK !!
The logos look great :)

**Comment by m-linner-ericsson** [comment]
Good looking logos

**Comment by e-backmark-ericsson** [comment]
Great! Thanks @MarckK and the LF design team!

**Comment by MarckK** [comment]
Glad you all are happy with the logo artwork! I think the designs look great as well. 🥳

I'm closing this issue and the parallel one with LF design team.

Thank you all!
