### ISSUE TITLE
Create an IP and Whitelist policy for licenses

### ISSUE THREAD

**Issue by danlopez00** [cdfoundation/foundation#35]
Does the CDF want to create an IP and Whitelist policy for licenses?

Ref: https://github.com/cncf/foundation/blob/master/whitelist-policy.md

**Comment by tracymiranda** [comment]
+1. Is this something we can put on the agenda for next board meeting?

**Comment by danlopez00** [comment]
This will be on next board meeting and working with LF team to provide IP Policy proposal CDF-wide

**Comment by fdegir** [comment]
Closing this issue since it is more than 3 years old.

The work to document CDF IP and License policies are tracked under issues #445 and #446.
