### ISSUE TITLE
Bitwarden/password management solution for Shipwright

### ISSUE THREAD

**Issue by adambkaplan** [cdfoundation/foundation#350]
Shipwright has several community owned accounts that need their credentials to be shared among the project maintainers. We would like to utilize a password management solution that allows the secure sharing and backup of credentials.

Bitwarden would be our preferred solution, as it is open source and has a team/organization plans [1]. At this moment the "Teams" plan would be sufficient for our use case.

[1] https://bitwarden.com/pricing/business/

**Comment by micmarti85** [comment]
Great! @adambkaplan if you could give me your email address I'll add you to the shared folder for Shipwright and make you the owner so you can share credentials with your team.
thanks,
M

**Comment by tracymiranda** [comment]
I believe this was resolved but please reopen if not.

**Comment by adambkaplan** [comment]
Yes, this can be closed. We're going to use 1-Password instead, since they have a free tier for open source projects.

https://github.com/1Password/1password-teams-open-source
