### ISSUE TITLE
Establish process for streaming SIG & TOC meetings to youtube

### ISSUE THREAD

**Issue by tracymiranda** [cdfoundation/foundation#351]
To streamline community videos to Youtube there are two options. We need to document these as well as the process for SIG chairs to access youtube/zoom. 

1) Projects can livestream straight to YouTube. In a meeting, the Host can click "More" and select "Live on YouTube". They will then be prompted to select a YouTube account, choose a title, and it'll livestream to https://livestream.cd.foundation
Pros: Video available immediately without extra work.
Cons: Only the Host can live-stream, so they'll need the CDF Zoom credentials. Also, the host needs to be at least "Manager" on the YouTube account (see below)

2) Projects can record all meetings to the cloud, and then someone can download and post the video file asynchronously. If the same person is always responsible for posting videos, we can set them to be notified via email when a cloud recording. They can then log into Zoom and download the mp4, and upload it to YouTube.
Pros: You can set any recurring meeting to record automatically, and the person posting the video doesn't have to join
Cons: Meetings can pile up fast, and it requires manual intervention.

In order to stream to the CDF youtube channel or post videos, the Host will need to be a channel manager with the "Manager" permission

**Comment by zestyroxy** [comment]
On hold for now

**Comment by afrittoli** [comment]
@MarckK @zestyroxy I wonder if it would make sense to pay for an existing integration like [YouTube for Zoom](https://marketplace.zoom.us/apps/WPKzwuoLQDuj_gPs68AQxw) - I've not tested it, it's just the first hit in the marketplace.

We are adopting Zoom meetings for several of Tekton WGs as well, but we have quite a few working groups, so the manual download and upload of meetings takes some work :)

**Comment by zestyroxy** [comment]
Maybe :) To be honest, I don't have much space to reflect on this at the moment and find it easier to just upload everything once a week.

**Comment by MarckK** [comment]
Closing as, for now, we are going with the solution mentioned by @zestyroxy above.
