### ISSUE TITLE
Add CD Events as official project to the website and all CDF resources

### ISSUE THREAD

**Issue by oleg-nenashev** [cdfoundation/foundation#353]
The TOC has just accepted the CD Events proposal in https://github.com/cdfoundation/toc/pull/136 . We ask the CDF to add the project to the CDF listing on the website and other resources like the Linux Foundation database, LFX Insights, etc., etc.

CC @tracymiranda @MarckK

**Comment by tracymiranda** [comment]
Website/landscape is dependant on https://github.com/cdfoundation/foundation/issues/348

**Comment by afrittoli** [comment]
#348 is closed now 🎉 

It would be nice to have this done in time for the FOSDEM talk on Feb 6th https://fosdem.org/2022/schedule/event/interoperability_in_the_continuous_delivery_space_with_cdevents/

**Comment by e-backmark-ericsson** [comment]
We're working on the last thing remaining for adding CDEvents to the landscape through this ticket: https://github.com/cdfoundation/cdf-landscape/pull/192

@MarckK , are you the one who will make sure that CDEvents is added to the CDF website menus etc?

**Comment by MarckK** [comment]
CDEvents are on the landscape 😄  https://landscape.cd.foundation/

<img width="526" alt="Screenshot 2022-01-31 at 14 27 33" src="https://user-images.githubusercontent.com/15032115/151811425-251b10eb-7770-4cdc-b283-2bc46b6f3faa.png">

And on CDF website, listed with all the other projects 🥳  https://cd.foundation/projects/

<img width="1455" alt="Screenshot 2022-01-31 at 14 29 53" src="https://user-images.githubusercontent.com/15032115/151811795-3ca61a14-eebc-458b-b072-272052b53faf.png">

**Comment by MarckK** [comment]
FYI notes:
1) You can add CDEvents twitter to the CDEvents card on landscape, when you all would like to do so.
2) The drop down menus on the CDF website have been removed (for all projects).

**Comment by MarckK** [comment]
Ahhh! I made a mistake on my review for the landscape... CDEvents should have a large card (as a CDF project)
* Going to go fix now..... *

**Comment by MarckK** [comment]
Hi @afrittoli, @e-backmark-ericsson, @oleg-nenashev, et al,

I believe this issue is now completed and am closing it.
