### ISSUE TITLE
Create Tektoncd Operator Logo

### ISSUE THREAD

**Issue by nikhil-thomas** [cdfoundation/foundation#355]
Hello from [Tektoncd/operator](https://github.com/tektoncd/operator).  Shall we create a logo for tektoncd/operator.

The primary objectives of Tektoncd Operator are:

1. Manage the lifecycle (install, upgrade, uninstall) of all the other Tektoncd Components (Pipelines, Triggers, Dashboard, Hub, Results, Chains...)
2. Provide additional Day 2 operational automation. (eg: change configuarion of installed components, configure new namespaces for Tekton Components by creating necessary permissions.)
3. Deliver additional building blocks such as curated Tasks, Pipelines, TriggerBindings etc

Places where logo will be used:

1. [OperatorHub entry for Tektoncd Opezrator](https://operatorhub.io/operator/tektoncd-operator)
2. Helm Charts (a single helm chart for all tektoncd components - inprogress)
3. [tektoncd/operator](https://github.com/tektoncd/operator)

**Comment by nikhil-thomas** [comment]
one idea i have is our "Robo Cat a Music Conductor" :innocent: :technologist:

**Comment by MarckK** [comment]
I've submitted the request. We should hear back from the design team over the next few weeks and can further refine the designs together.

**Comment by concaf** [comment]
Great work, love the logos 🙃 🎉 
(Strictly my option 🙃) I'd like a mix or top left and bottom right; essentially, I envision the Tekton operator to be a multi-tasking cat that's doing 10 things at the same time, like a human "computer" operator/admin.
These logo options have a "telephone operator" vibe which is cool, but we could also consider a "computer operator" vibe.

The same vibe as the following images maybe?
![image](https://user-images.githubusercontent.com/9133660/169232794-272a339e-f6c7-45cb-9a3a-e30252e4fdb1.png)
![image](https://user-images.githubusercontent.com/9133660/169232814-1d9c8210-e40d-462c-ae49-5991b27b7fa4.png)
![image](https://user-images.githubusercontent.com/9133660/169232824-f7383f84-ea09-4922-b4ea-e9055b1dff5e.png)

Sources:
https://image.shutterstock.com/image-vector/multitasking-cat-sunglasses-six-paws-600w-1365098336.jpg
https://media.istockphoto.com/vectors/set-of-cat-boy-who-perform-multitasking-vector-id1332080479
https://www.vectorstock.com/royalty-free-vector/multitasking-businessman-cartoon-flat-vector-18202994

**Comment by MarckK** [comment]
Hi @concaf, your requests have been shared and I am excited to see what the Design Team comes up with!

Personally, I like the floating (meditating?) chilled-out, multi-tasking cat. 😸 

Caveat: When looking over the new designs we want to make sure that the Tektoncd Operator Logo doesn't share too many broad visual traits with Octocat.

**Comment by nikhil-thomas** [comment]
@MarckK out of the first set [posted on 18th may](https://github.com/cdfoundation/foundation/issues/355#issuecomment-1130050466) i like the bottom right plain head.

The reason being that is the only one which will be recognizable when used as an icon in operatorHub, a emoji in slack and in any other format.

It is simple, meaningful and elegant. 🧑‍💻

**Comment by nikhil-thomas** [comment]
i appreciate the dense details in the set [posted on 1st June](https://github.com/cdfoundation/foundation/issues/355#issuecomment-1142547560). 

I believe none of these options will scale well especially when used as an emoji. 🤓

**Comment by nikhil-thomas** [comment]
Shall we consider a fusion of the head (bottom right in [may 18 set](https://github.com/cdfoundation/foundation/issues/355#issuecomment-1130050466)) with some of the multimedia elements floating around it. 🙂 

Technically speaking operator doesn't explicitly hold on to many things. It just records its desires and Kubernetes full fills it. 😇

**Comment by concaf** [comment]
> out of the first set https://github.com/cdfoundation/foundation/issues/355#issuecomment-1130050466 i like the bottom right plain head.

@nikhil-thomas I agree with you.

> with some of the multimedia elements floating around it.

not sure if the multimedia elements really showcase what the operator does; we could have a keyboard, mouse, etc but no camera, radio, gaming controller, etc.

**Comment by nikhil-thomas** [comment]
> we could have a keyboard, mouse, etc but no camera, radio, gaming controller, etc.

+1 🧑‍💻

**Comment by MarckK** [comment]
Sounds good. And the design is becoming narrowed down and clarified.

So, I'm going to ask for the following image with a few elements free floating around it:
<img width="506" alt="Screenshot 2022-06-02 at 08 13 38" src="https://user-images.githubusercontent.com/15032115/171626779-532e48ac-e5eb-4591-b4e5-c51f91f60604.png">

The free floating elements will be: 
* a keyboard, mouse, etc but no camera, radio, gaming controller, etc.

**Comment by MarckK** [comment]
Latest iteration of the logo!

[tekton-operator_v3.pdf](https://github.com/cdfoundation/foundation/files/8879826/tekton-operator_v3.pdf)

<img width="1142" alt="Screen Shot 2022-06-10 at 10 45 29 AM" src="https://user-images.githubusercontent.com/15032115/173091004-4884a257-7331-45e5-a7c2-75c2594b7c86.png">


<img width="1131" alt="Screen Shot 2022-06-10 at 10 45 38 AM" src="https://user-images.githubusercontent.com/15032115/173091021-d6736e49-642d-417b-9573-ca0f2a7c9594.png">

**Comment by MarckK** [comment]
Hi all, I'm off on PTO next week, so am adding @zestyroxy and @fdegir to keep an eye on this while I am away.
Thank you!

**Comment by nikhil-thomas** [comment]
I think we shall pick the simple icon with "head with headphones" without any other additional elements. 🧑‍💻 

this one: https://user-images.githubusercontent.com/15032115/171626779-532e48ac-e5eb-4591-b4e5-c51f91f60604.png

**Comment by concaf** [comment]
I agree 🙃 and apologies for the noise!

**Comment by vdemeester** [comment]
@nikhil-thomas @concaf we can also "use" more than one accross the project *but* have an official one, which I agree, might probably be the simplest one, with the headphones 😬

**Comment by zestyroxy** [comment]
Cool, so final logo decision is this one? Please reply with +1 if you agree
<img width="506" alt="tekton operator" src="https://user-images.githubusercontent.com/18251881/175269509-c80f38b8-3dcb-4bcd-a7ea-39c9811af5b8.png">

**Comment by MarckK** [comment]
Hi @vdemeester @nikhil-thomas @concaf et al, 

If you all are happy with the new Tekton Operator logo, we'll close this issue.

Thank you for the 👍 @vdemeester. 😄  

Since @nikhil-thomas and @concaf have stated their approval above of this final design, we'll close the issue now.

Enjoy the new logo!

You can always reopen, or open another issue, if there is anything else you need!

**Comment by sm43** [comment]
@MarckK Where can I find the final logo in which repository? I was looking into https://github.com/cdfoundation/artwork but couldn't find the one for the operator.
