### ISSUE TITLE
Jenkins X zoom subaccount

### ISSUE THREAD

**Issue by ankitm123** [cdfoundation/foundation#356]
It would be nice to have a zoom sub-account dedicated to the Jenkins X project. We want to use it for the community office hours, and any other meetings (docs/testing etc  ...) we might plan in the future.
Atm, I use my personal account which has a limit of max 40 mins for a meeting with more than 3 people in it.

We run office hours every other Tuesday at 15:00 UTC.

**Comment by oleg-nenashev** [comment]
The CDF will be moving to Bevy from what I understood. In such a case it does not make much wense to provision a Zoom account right now unless strongly needed. CC @MarckK

**Comment by ankitm123** [comment]
I am fine with that, it seems from the slack thread that the ETA is early Q1.

**Comment by zestyroxy** [comment]
https://community.cd.foundation/jenkins-x/ @ankitm123 we can also set you up with a sub-zoom if you want

**Comment by ankitm123** [comment]
> we can also set you up with a sub-zoom if you want

Yes, that will be nice. We can slowly transition to bevy (and may be disable zoom later?)

**Comment by ankitm123** [comment]
Yup, thanks!
Closing this.
