### ISSUE TITLE
Non-profit Sponsorship Application to HackMD

### ISSUE THREAD

**Issue by fdegir** [cdfoundation/foundation#358]
Few SIGs (Interop, Events, Best Practices) use HackMD for collaborative editing. Its push capabilities help the community to send docs to our GitHub repos for version controlling.

However, HackMD seems to have introduced limits for free plans - no of commits that can be pushed to GitHub is limited to 20 and no of versions displayed on HackMD interface is limited to 10. It looks like there is a limit on no of members teams could have which may not be that critical given that people can still collaborate without being a member.

HackMD has a non-profit plan as well and it would be good if CDF could investigate applying for it.
The terms and application process is documented here.

https://hackmd.io/c/tutorials/%2F%40docs%2FNPOplan

**Comment by fdegir** [comment]
As an additional note and as I said on Slack, I could work with/on HackMD to help with migrating notes from personal accounts to CDF account if/when CDF gets non-profit plan.

**Comment by MarckK** [comment]
Hi all,
Question on the non-profit status of CDF came up at TOC meeting today, 1/2/2022.

The CDF is a 501(c)(6) as a sub organization of the Linux Foundation, which is a 501(c)(6):
https://en.wikipedia.org/wiki/Linux_Foundation#CD_Foundation

**Comment by fdegir** [comment]
Docs created/used by SIG Interoperability:

- https://hackmd.io/HuufSDMaTPyb3qxkyBKg3A
- https://hackmd.io/niM1USFoQyycav8IczCmzQ
- https://hackmd.io/BYbkuR8uSlKt_w7Y4KE1OQ
- https://hackmd.io/__6IAnVuR8C8mPD--XMbWg
- https://hackmd.io/AizhDLlRTyuYWz-XidWdGg

**Comment by erkist** [comment]
Docs created by SIG Events
https://hackmd.io/xjK5ujQbTHSaEZjoY28b8g
https://hackmd.io/2FRGlw9fTMmKN1OQUVvguA
https://hackmd.io/ZCS2KYKZTpKBqhU9PMuCew

**Comment by tdcox** [comment]
Best Practices:
https://hackmd.io/uxoIwj7fTjKkI161-IZeFw

**Comment by fdegir** [comment]
FYI - I just sent an email to support@hackmd.io and sharing the answers to the questions they ask as part of the application for transparency.
Will add more info to this issue as it becomes available.

- Documentations that prove nonprofit status in your country.
    - The status of CDF and its parent organization Linux Foundation (LF) is written here: https://github.com/cdfoundation/foundation/issues/358#issuecomment-1027280371
    - I included Kara de la Marck from LF/CDF in this mail thread if you have additional questions about this.
- A brief introduction to your organization or program.
    - The CDF is a vendor-neutral, non-profit organization that is establishing better developer experiences through best practices advocacy, educational programming, and a global community of practice.
    - The CDF is home to most popular CI/CD projects such as Jenkins, Spinnaker, Tekton and so on. More info is available here: https://cd.foundation/projects/
    - In addition to the projects, the CDF hosts Special Interest Groups (SIG) for community members to contribute to CI/CD domain.
- A brief introduction on how you will use HackMD in your team.
    - CDF SIGs heavily use HackMD for collaboration such as for keeping agenda/minutes of meetings, birds of a feather sessions during conferences, drafting very early versions of the specs and so on.
    - You can see some of the documents from this link: https://github.com/cdfoundation/foundation/issues/358
    - If our application for non-profit sponsorship is approved, more groups may start using HackMD for their needs.
- Other references that would help us get familiar with your mission.
    - CDF Website: https://cd.foundation/
    - CDF on GitHub: https://github.com/cdfoundation

**Comment by fdegir** [comment]
Our application process has been finalized and we moved to Team Plan.
(Co)Chairs of the SIGs are granted admin permissions for [HackMD CDFoundation Team](https://hackmd.io/team/cdfoundation).
Existing docs used by the SIGs are transferred to HackMD CDFoundation Team.

Thanks to all who helped!
Closing the issue.
