### ISSUE TITLE
Incorrect Logo for Red Hat

### ISSUE THREAD

**Issue by adambkaplan** [cdfoundation/foundation#361]
On the CD Foundation [Members page](https://cd.foundation/members/), the old logo for Red Hat ("shadowman") is presented. This logo was replaced in 2019 with the current "fedora" logo.

Please refer to Red Hat's [logo standards](https://www.redhat.com/en/about/brand/standards/logo) for the correct logos and brand guidance.

**Comment by zestyroxy** [comment]
cc/ @MarckK to be updated on https://github.com/cdfoundation/cdf-landscape

**Comment by MarckK** [comment]
Hi @adambkaplan, The logos on the Members page are pulled directly from [the CDF landscape](https://landscape.cd.foundation/).  

To update RedHat's logo on the CDF landscape, and thus the Members page, please make a PR to the [CDF landscape repo](https://github.com/cdfoundation/cdf-landscape).

Please note that the logo needs to be an SVG. You can find [more detailed instructions on the CDF landscape repo README](https://github.com/cdfoundation/cdf-landscape#logos).

**Comment by MarckK** [comment]
Hi Adam, Thank you for adding the new Red Hat logo to the CDF landscape!

I'll close this issue now as it is resolved. 

My only suggestion to you / Red Hat is that a stacked logo shows slightly better on the CDF landscape and on the CDF Members page. 
Ultimately, the logo representing the an individual company is chosen by that company, so the choice of stacked or vertical logo is up to Red Hat.

**Comment by adambkaplan** [comment]
Thanks - I was able to submit a follow-up PR with the stacked logo, and it now renders correctly.

+1 to the assets pipeline you built for the website!
