### ISSUE TITLE
[Nominations Open] Continuous Enthusiast Award 2022 🏆

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#364]
This issue is to receive nominations for the Continuous Enthusiast Award 2022. 

This is the special award for the community contributors. When you think of the CDF community, this person should be on the shortlist, because they're everywhere!

To nominate someone, reply to this issue with the following:
1. Full name of the person you’re nominating
2. Short description of their contributions to the Continuous Delivery Foundation and why they should win.

**Nomination Deadline:** ~~Tuesday, March 29, 2022~~ [EXTENDED to April 11, 2022]

More details are available here: https://cd.foundation/cdf-community-awards/

**Comment by e-backmark-ericsson** [comment]
Nomination: Fatih Degirmenci

Fatih has been a driving force within CDF all the way from its birth. He early initiated the SIG Interoperability which attracted the interest of a multitude of companies and organizations and he served as one of the chairs for that SIG until he recently initiated the SIG Software Supply Chain, which recently had its formation meeting where more than 10 companies where represented. Fatih is a frequent presenter at various summits/conferences, both open source oriented and others, and he always promotes the CDF community and its different working groups and projects wherever he shows up.

Fatih should win the CEA 2022 as he always brings a positive drive to wherever he attends, pushing us all to jointly strive for the best for the community.

**Comment by MarkEWaite** [comment]
## Nomination: Darin Pope (@darinpope)

Darin is a long-time "Continuous Enthusiast".  He hosts the [DevOps Paradox podcast](https://www.devopsparadox.com/) with Viktor Farcic.  Darin and Viktor discuss DevOps topics and challenges in a wide ranging podcast.

Darin is a great advocate for open source.  He's created many videos focused on open source software, including:

* [What's new in Jenkins LTS](https://www.youtube.com/watch?v=W6MkDotLOJE) (monthly)
* [Modernizing a Jenkins plugin](https://www.youtube.com/playlist?list=PLvBBnHmZuNQIwIZ86HL39uot6751EOd-f) (five part series)
* [Jenkins tutorials](https://www.youtube.com/playlist?list=PLvBBnHmZuNQJeznYL2F-MpZYBUeLIXYEe) (over 100 videos)
* [Behind the scenes of plugins.jenkins.io](https://www.youtube.com/watch?v=sR4ev0q9zNA&list=PLvBBnHmZuNQIb4p2t69dgMQyGbzb8qr4T&index=1)

Several of Darin's videos are included in the official Jenkins documentation site, including:

* [Installing Jenkins on Linux](https://www.jenkins.io/doc/book/installing/linux/)
* [Installing Jenkins on Windows](https://www.jenkins.io/doc/book/installing/windows/)
* [Using Jenkins Agents](https://www.jenkins.io/doc/book/using/using-agents/)
* [Managing Nodes](https://www.jenkins.io/doc/book/managing/nodes/)

Darin has shared blog posts on [jenkins.io](https://www.jenkins.io/) this year, including:

* [Use containers as build agents](https://www.jenkins.io/blog/2021/12/08/containers-as-build-agents/)
* [Use just enough Pipeline](https://www.jenkins.io/blog/2021/10/26/just-enough-pipeline/)

**Comment by salaboy** [comment]
@zestyroxy I wonder why I am not on the list of ambassadors.. did I miss an email?

**Comment by zestyroxy** [comment]
### Nomination: Jennifer Hooper @justjenu 

Jennifer is a driving force for the Spinnaker community and is present for all things CDF. She always shares great ideas and is always enthusiastic about future events and projects. She's also volunteered to be on the cdCon 2022 Program committee.

**Comment by afrittoli** [comment]
**Nomination: Tracy Ragan**

Tracy served.on the CDF governing board, managed the CDF meetup community, created the initial CD landscape, relaunched the events in CI/CD group as a SIG of its own, contributing to it and continuously advocating for the SIG work and mission. Tracy is involved with various SIGs and she makes things happen everywhere around the CDF!

**Comment by zestyroxy** [comment]
🚫 Nominations are now closed! 
Voting will start April 13, link will be posted here.

**Comment by zestyroxy** [comment]
Thank you, everyone! Award ceremony happened at cdCon 2022.
Congratulation to the winner @darinpope!
All winners here: https://github.com/cdfoundation/awards/blob/main/README.md
