### ISSUE TITLE
[Nominations Open] Top Doc(umenter) Award 2022 🏆

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#365]
This issue is to receive nominations for the Top Doc(umenter) Award 2022. 

This award recognizes excellence in documentation contributions to the CDF and its projects. Outstanding technical documentation is one of the best ways projects can lower the barrier to contribution.

To nominate someone, reply to this issue with the following:
1. Full name of the person you’re nominating
2. Short description of their contributions to the Continuous Delivery Foundation and why they should win.

**Nomination Deadline:** ~~Tuesday, March 29, 2022~~ [EXTENDED to April 11, 2022]

More details are available here: https://cd.foundation/cdf-community-awards/

**Comment by MarkEWaite** [comment]
Nomination: **Meg McRoberts** (@StackScribe)

Meg is an active contributor to [Jenkins documentation](https://github.com/jenkins-infra/jenkins.io/pulls?q=is%3Apr+author%3AStackScribe+is%3Aclosed+).  She has improved the Jenkins security documentation and the Jenkins user guide.  Her reviews of pull requests are consistently helpful and encouraging for new contributors.

Meg mentored the Jenkins project in the [2021 She Code Africa Contributhon](https://www.jenkins.io/blog/2021/04/07/contributhon-participants/#mentors).  She spent a month on a development project with five women from Africa as they submitted their first open source contributions.

Meg is an active participant in [Jenkins documentation office hours](https://community.jenkins.io/tag/sig-docs).  She has guided documentation structural improvements, has planned the She Code Africa Contributhon for 2022, and continues to [support documentation contributors](https://docs.google.com/document/d/1ygRZnVtoIvuEKpwNeF_oVRVCV5NKcZD1_HMtWlUZguo/edit?usp=sharing).

**Comment by caniszczyk** [comment]
Oleg Nenashev has done an amazing job in improving documentation across different areas of CDF, including TOC processes.

**Comment by zestyroxy** [comment]
+1 for @oleg-nenashev

**Comment by fdegir** [comment]
Nomination: Tara Hernandez

Tara has been part of the CDF community since very early days and contributed to initial versions of the TOC processes. She   served the community as a member to CDF TOC. 

Tara currently chairs SIG Best Practices, leading efforts on collecting & documenting best practices and contributing to the development of the website to publish them. This initiative is one of the most critical initiatives happening within the CDF community since it will help organisations who are on their way to embrace CD with a place where they can learn about the practices they can adapt and Tara puts a lot of time and effort into it.

**Comment by e-backmark-ericsson** [comment]
Nomination: Andrea Frittoli

Andrea has been very active in forming the written material around the CDEvents project, previously within the SIG Events repository and nowadays under its own Github organization. That work has involved launching a project page for CDEvents (https://cdevents.dev/), documenting the governance and related material for the CDEvents project itself, as well as providing a solid base for the CDEvents event specification itself.

Andrea should win the top doc award for his willingness to provide well written, relevant and accurate documentation for CDEvents

**Comment by zestyroxy** [comment]
🚫 Nominations are now closed! 
Voting will start April 13, link will be posted here.

**Comment by zestyroxy** [comment]
Thank you, everyone! Award ceremony happened at cdCon 2022.
Congratulation to the winner @oleg-nenashev!
All winners here: https://github.com/cdfoundation/awards/blob/main/README.md
