### ISSUE TITLE
[Nominations Open] Most Valuable Jenkins Contributor 2022 🏆

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#366]
This issue is to receive nominations for the Most Valuable Jenkins Contributor 2022. This award is presented to an individual who has contributed to the Jenkins project the most through new features, bug fixes or plugin development efforts.

To nominate someone, reply to this issue with the following:

1. Full name of the person you’re nominating
2. Short description of their contributions to the Continuous Delivery Foundation and why they should win.

**Nomination Deadline:** ~~Tuesday, March 29, 2022~~ [EXTENDED to April 11, 2022]

More details are available here: https://cd.foundation/cdf-community-awards/

**Comment by uhafner** [comment]
Nomination: Jan Faracik

He did a tremendous job in improving the user experience and design of the Jenkins user interface. His work includes new icons, improved UI form elements, view redesign, UI developer API, helpful developer documentation, etc. His changes let Jenkins look modern again!

**Comment by alyssat** [comment]
@jmMeessen and I are pleased to nominate Kris Stern (@krisstern on GitHub) for the Most Valuable Advocate award. Kris is a new contributor to the Jenkins project, and has shown exemplary dedication to the meaning of giving back. Kris volunteered to be a mentor and an org admin for Jenkins Google Summer of Code 2022. Since signing up he has displayed genuine commitment to the success of this program. He is present at every office hours even when it is 1am his local time. He is always available and responsive to all GSoC potential contributors, providing feedback, guidance and technical advice. At times Kris could be seen gracefully challenging potential contributors to think outside of the box, as a good mentor does. There are times throughout the program where the ratio of potential contributors outnumbered the mentors prompting a flurry of inquiries, Kris rose to the occasion and took the lead to address those inquiries, even when he is the very few doing so.

Kris’ contributions, commitment, and thoughtfulness amplify what the Jenkins community stands for which is fostering an open and welcoming community.

Many Thanks Kris!

**Comment by MarkEWaite** [comment]
Nomination: Basil Crow (@basil)

Basil modernized major components in Jenkins core.  He converted the Linux installers from System V init to systemd.  He updated, adopted, and released additional core Jenkins components.  He adopted, updated, and released multiple Jenkins plugins.

Some examples of his contributions:

* Member of the Jenkins core team, reviewing and improving Jenkins core
  * Over [300 pull requests to Jenkins core](https://github.com/jenkinsci/jenkins/pulls?page=1&q=is%3Apr+author%3Abasil+is%3Aclosed) in the last 15 months
    * Multiple challenging upgrades of core components like [Guava](https://github.com/jenkinsci/jenkins/pulls?q=is%3Apr+author%3Abasil+is%3Aclosed+guava), [Guice](https://github.com/jenkinsci/jenkins/pulls?q=is%3Apr+author%3Abasil+is%3Aclosed+Guice), [ASM](https://github.com/jenkinsci/jenkins/pulls?q=is%3Apr+author%3Abasil+is%3Aclosed+ASM), and [JNR](https://github.com/jenkinsci/jenkins/pulls?q=is%3Apr+author%3Abasil+is%3Aclosed+JNR)
    * Quality improvement with [spotbugs](https://github.com/jenkinsci/jenkins/pulls?q=is%3Apr+author%3Abasil+is%3Aclosed+spotbugs), [checkstyle](https://github.com/jenkinsci/jenkins/pulls?q=is%3Apr+author%3Abasil+is%3Aclosed+checkstyle), and [spotless](https://github.com/jenkinsci/jenkins/pulls?q=is%3Apr+author%3Abasil+is%3Aclosed+spotless)
* Installation improvements
  * Over [50 pull requests to Jenkins Linux installer](https://github.com/jenkinsci/packaging/pulls?q=is%3Apr+author%3Abasil+is%3Aclosed) in the last 6 months
* Java support improvements
  * Identified and resolved [Java 11 support](https://issues.jenkins.io/browse/JENKINS-67688) issues
  * Identified and resolved [Java 17 support](https://issues.jenkins.io/browse/JENKINS-67908) issues
* Maintainer of 23 plugins
  * API plugins like [Jakarta activation API](https://plugins.jenkins.io/jakarta-activation-api/), [Jakarta mail API](https://plugins.jenkins.io/jakarta-mail-api/), [JavaX activation API](https://plugins.jenkins.io/javax-activation-api/), [JavaX mail API](https://plugins.jenkins.io/javax-mail-api/), [Jersey2 API](https://plugins.jenkins.io/jersey2-api/), and [JNR POSIX API](https://plugins.jenkins.io/jnr-posix-api/)
  * Infrastructure plugins like [file leak detector](https://plugins.jenkins.io/file-leak-detector/), [email ext](https://plugins.jenkins.io/email-ext/), and [SQLite database](https://plugins.jenkins.io/database-sqlite/)
  * Pipeline plugins like [workspace cleanup](https://plugins.jenkins.io/ws-cleanup/), [timestamper](https://plugins.jenkins.io/timestamper/), [lockable resources](https://plugins.jenkins.io/lockable-resources/), [resource disposer](https://plugins.jenkins.io/resource-disposer/), and [http_request](https://plugins.jenkins.io/http_request/)
  * Authentiation plugins like [GitHub OAuth](https://plugins.jenkins.io/github-oauth/) and [GitLab OAuth](https://plugins.jenkins.io/gitlab-oauth/)

**Comment by zestyroxy** [comment]
Thank you, everyone! Award ceremony happened at cdCon 2022.
Congratulation to the winner @basil!
All winners here: https://github.com/cdfoundation/awards/blob/main/README.md

**Comment by uhafner** [comment]
Are the voting results public as well? I.e., who got how many votes?

**Comment by fdegir** [comment]
Thanks for reaching out @uhafner.

> Are the voting results public as well? I.e., who got how many votes?

The results are not public.
In order to increase the transparency of CDF Awards process, we are working on documenting it.
Please feel free to share your feedback about it directly on [the corresponding issue](https://github.com/cdfoundation/foundation/issues/387).

We can include you as a reviewer to PR once it becomes available so you can provide your feedback directly on it.
Please let us know.

**Comment by fdegir** [comment]
@uhafner we have made a few changes to the CDF Awards Program for 2023.

* The [awards program guidelines](https://github.com/cdfoundation/foundation/blob/main/CDF%20Awards%20Guidelines.md) are published.
* [As noted on the guidelines](https://github.com/cdfoundation/foundation/blob/main/CDF%20Awards%20Guidelines.md#project-awards), each CDF project conducts their own selection process for their Most Valuable Contributor Award.
* For [CDF Awards](https://github.com/cdfoundation/foundation/blob/main/CDF%20Awards%20Guidelines.md#-cdf-community-awards), we introduced a new role, Awards Officer, overseeing the nomination and voting process for CDF Awards.

Please let us know if you want to become the Awards Officer for the CDF Awards.

**Comment by uhafner** [comment]
Hi @fdegir, yes, I am happy to help! What are the steps to do? Review the documents?

**Comment by fdegir** [comment]
That's great @uhafner. It would be good if you could review [the awards program guidelines](https://github.com/cdfoundation/foundation/blob/main/CDF%20Awards%20Guidelines.md) as well as [the community roles](https://github.com/cdfoundation/foundation/blob/main/CDF%20Community%20Roles%20.md#other-community-roles) and let us know of your feedback by opening up an issue in [the foundation repo](https://github.com/cdfoundation) or directly proposing changes via PRs.

We added awards officer topic to [the agenda of the TOC Meeting](https://docs.google.com/document/d/1uBHar55fTInWF9Li4t0lyG3tTC8BRLU0FfBfsgk_Jrs/edit#heading=h.efj7mpikrslq) that will happen on Tuesday, February 14th at 16:00 UTC and call for volunteers. If possible, it would be good if you could join and state your interest.

**Comment by fdegir** [comment]
@uhafner could you please pass your email address to me via a private message on CDF Slack so we can communicate nomination and voting related information with you?
