### ISSUE TITLE
Permissions update to update CDF Public Calendar

### ISSUE THREAD

**Issue by mjmckay** [cdfoundation/foundation#371]
As a co-chair of the Interoperability SIG, I need to have permission to update the CDF Public Calendar. We will need to update our regular meeting time after this week.

**Comment by NSouthernLF** [comment]
Working on this now, Melissa. Should have it resolved shortly.

**Comment by mjmckay** [comment]
@NSouthernLF Is this resolved? Let me know if you need anything from me.

**Comment by mjmckay** [comment]
@NSouthernLF I've checked my permissions. It looks like I have permissions to the Governing Board calendar instead of the Public calendar. Can you assist?

**Comment by MarckK** [comment]
Hi Melissa,

Apologies that the permissions were not granted correctly the first time!

Michelle Martineau, a PM at the LF, will reach out to you and get you the correct permissions.

**Comment by fdegir** [comment]
I just got confirmation that this was done so closing the issue. Please let us know if it wasn't so we look into it.

**Comment by NSouthernLF** [comment]
Hi, Faith. I am no longer on this project.
