### ISSUE TITLE
[Nomination Open]Top Ortelius Contributor

### ISSUE THREAD

**Issue by TracyRagan** [cdfoundation/foundation#372]
This issue is to receive nominations for the Ortelius Most Valuable Contributor (MVC) Award 2022.

This award recognizes excellence of contributions to the Ortelius project, which may be any or a combination of contributions, advocacy, community involvement, and fostering adoption in other communities.

To nominate someone, reply to this issue with the following:

Full name of the person you’re nominating
Short description of their contributions to the Orelius project and why they should win.
Nomination Deadline: Tuesday, March 29, 2022

More details are available here: https://cd.foundation/cdf-community-awards/

cc: @TracyRagan  fyi - I created this for Ortelius community

**Comment by TracyRagan** [comment]
I am nominating Brad McCoy for our 2022 MVP. Brad has shown his commitment to the Ortelius project in so many ways. He has served as an individual contributor, led the Australian Architecture sub-committee including recruiting highly skilled individuals. He has worked on outreach, presentations, and mentorship. Ortelius is better because of his commitments to the project.

**Comment by sbtaylor15** [comment]
+1 - Brad has done an outstanding job with the Australian Architecture group. Ortelius has grown because of him.

**Comment by Saim-Safdar** [comment]
+1 Brad has done great work and also helped others in the process.

**Comment by scanalesespinoza** [comment]
Utkarsh Sharma! awesome working on issues and improving Ortelius, I see him on github keeping our community alive day by day

**Comment by sbtaylor15** [comment]
Utkarsh Sharma is another great contributor to Ortelius.  He has helped new members learn how to contribute and is always there to code, answer questions and attend meetings with helpful input.

**Comment by sachajw** [comment]
+1 Brad

**Comment by codeWithUtkarsh** [comment]
+1 Brad

**Comment by benhpoh** [comment]
+1 Brad. He doesn't just contribute as a sole operator, but also uplifts others so they gain the skills to be able to complete the tasks on their own. Gotta commend those who teach others how to fish

**Comment by bradmccoydev** [comment]
+1 @codeWithUtkarsh he has shown great consistency throughout the year with his valuable contributions, and always welcoming and friendly within the community
