### ISSUE TITLE
Uploading SIG Software Supply Chain Meeting Recordings to Youtube

### ISSUE THREAD

**Issue by fdegir** [cdfoundation/foundation#373]
Could get a new playlist for the SIG Software Supply Chain on CDF Youtube Channel and upload the recordings for the two meetings we had on March 10th and March 24th there?

Thanks!

**Comment by zestyroxy** [comment]
Yes, the recordings aren't on the main zoom? Is there a sub zoom I need access to?

**Comment by zestyroxy** [comment]
Oh, I found them. They were labelled Interoperability. Can you fix that for the future?
March 10: https://youtu.be/3i6pcPr09Uk
March 24: https://youtu.be/9SXcXk2cO3c (still uploading)

**Comment by fdegir** [comment]
> Oh, I found them. 

Thanks a lot!

> They were labelled Interoperability. Can you fix that for the future?

We just reused the same Zoom link the SIG Interoperability uses and I didn't know they are labeled.
I am not sure if I have permission to setup new Zoom meetings and/or label meetings but I can do that going forward if I know how.

**Comment by zestyroxy** [comment]
Ah, if you can login to zoom, I believe you can schedule new meetings. If not, let me know and we can do it together.
