### ISSUE TITLE
Zoom sub-account for Shipwright (reopening)

### ISSUE THREAD

**Issue by adambkaplan** [cdfoundation/foundation#376]
This effectively a reopening of #345. Unclear where the breakdown happened, but the Shipwright project currently does not have access to the Zoom sub-account. We would like to use this for our contributor/community summit at cdCon for virtual participants.

CC @imjasonh @qu1queee @SaschaSchwarze0

**Comment by adambkaplan** [comment]
cc @MarckK

**Comment by imjasonh** [comment]
My recollection is that a Zoom account was created, but that the password for it wasn't visible. Sorry for the breakdown.

In the meantime, I believe CDF has started trying to use a different meeting platform, Bevy. At least, that's what TOC meetings use ([ref](https://community.cd.foundation/events/details/cd-foundation-technical-oversight-committee-toc-presents-cdf-technical-oversight-committee-meeting/)). I don't know if they also recommend that for projects' meetings, or if Zoom is still fine there.

**Comment by zestyroxy** [comment]
The transition to Bevy is on hold until further notice. 

For the Zoom account, [Michelle Martineau](mailto:mmartineau@linuxfoundation.org) has all the credentials. You need a LastPass Account + Browser add-on and she shares the file with whoever needs it.

**Comment by fdegir** [comment]
I just got confirmation that this was done so closing the issue. Please let us know if it wasn't so we look into it.
