### ISSUE TITLE
CSS breakpoint issue on the website.

### ISSUE THREAD

**Issue by justinabrahms** [cdfoundation/foundation#377]
At certain window sizes, the buttons go weird on the website. See attached. We should probably swap to the mobile view faster.
<img width="1181" alt="Screen Shot 2022-05-19 at 14 11 42 " src="https://user-images.githubusercontent.com/3853/169407218-ccbc2f6f-5ba5-471b-8b2b-a4efecc5c77e.png">
<img width="1072" alt="Screen Shot 2022-05-19 at 14 11 35 " src="https://user-images.githubusercontent.com/3853/169407219-27979487-8204-4455-92ce-3229cd8cc0b4.png">
<img width="838" alt="Screen Shot 2022-05-19 at 14 11 31 " src="https://user-images.githubusercontent.com/3853/169407223-38ed76f4-12da-4692-a33d-dfd83ed8ab73.png">

**Comment by zestyroxy** [comment]
Indeed, thank you! I'll report an issue to the website team on Asana.

**Comment by zestyroxy** [comment]
The LF Team reported this as fixed, I tested it and it seems to work better. Feel free to re-open if you disagree :)
