### ISSUE TITLE
AWS and Azure testing account for Jenkins X

### ISSUE THREAD

**Issue by ankitm123** [cdfoundation/foundation#378]
Jenkins X supports the 3 major cloud providers - AWS, GCP and Azure (https://jenkins-x.io/v3/about/#administration).
However our tests only run on GCP (Google Cloud Platform). This makes it hard to guarantee stability for other cloud providers when a new version of jx is released (We rely on the community to do manual tests and come back to us if they see issues - which can lead to bad experiences for users).

It would be great if we could get an AWS (Most Jenkins X users are on AWS according to a survey) and Azure account from CD Foundation (same set up as the GCP Account) which we can exclusively use for testing.

**Cost Estimates**

In the last few months, we made steady improvements to the main jx infra as well the e2e testing gcp account.
Our efforts have led to the costs going down by more than 80%.
These are breakdowns from the current GCP projects/accounts used by Jenkins X (testing account + main account) in the last 3 months (All amounts are in USD):
- March: 1299 + 365 = 1664
- April: 488 + 428 = 916
- May: 58 + 274 = 332

We expect the costs to go down a bit in June (or atleast stay near the may costs)

Based on these numbers, we need no more than 100 USD per cloud provider per month - so 200 USD total for AWS and Azure is plenty for our tests.
  
**Current Set up**

* GCP account for hosting main infra
* GCP account for running e2e tests

**Desired set up**

* GCP account for hosting main infra
* GCP, AWS and Azure account for running e2e tests

**Comment by fdegir** [comment]
@ankitm123 I believe you have cloud credits from AWS now. Have you received any response from Azure?

**Comment by ankitm123** [comment]
Nothing from azure, I will send them a follow up email, and see where we are with the process.

**Comment by afrittoli** [comment]
@ankitm123 @fdegir what is the status of this?

**Comment by fdegir** [comment]
@afrittoli Ankit applied for cloud credits to AWS and Azure.

The project received  (some) credits from AWS and the response from Azure was still
pending the last time we discussed this.

I suggest to close this issue and create a new one specific to Azure so we can follow it ip
with them.

**Comment by afrittoli** [comment]
AWS part is solved.
Azure part superseded by https://github.com/cdfoundation/foundation/issues/449
