### ISSUE TITLE
Add Adam Kaplan to the CDF Governing Board page

### ISSUE THREAD

**Issue by adambkaplan** [cdfoundation/foundation#379]
I have been nominated to replace @imjasonh as Red Hat's representative to the governing board.

Please add me to the governing board membership page: https://cd.foundation/about/governing-board/

Thank you.

**Comment by zestyroxy** [comment]
+1 what do you want your profile to say? And should I use your LinkedIn Photo with the hat?

Example
**Jason Hall**
Red Hat
Jason co-founded Google Cloud Build and the Tekton project at Google. He recently joined Red Hat to continue working on Tekton and Shipwright.
+ Twitter or LinkedIn Link

**Comment by adambkaplan** [comment]
Profile:
**Adam Kaplan**
Red Hat

Adam is a Principal Software Engineer at Red Hat and a maintainer of Shipwright.

* Twitter: https://twitter.com/AdamBKaplan
* LinkedIn: https://www.linkedin.com/in/adambkaplan/

My LinkedIn profile picture (with the fedora) works.

Thanks!
