### ISSUE TITLE
Update "Adopt Best Practices" link on cd.foundation main page

### ISSUE THREAD

**Issue by tequilarista** [cdfoundation/foundation#382]
bestpractices.cd.foundation is now public and we're engaging with contributors, so we should redirect to there

**Comment by fdegir** [comment]
@zestyroxy I'm wondering if you could help with this since I don't have access to CMS yet?

**Comment by zestyroxy** [comment]
Done! The best practices button now leads to https://bestpractices.cd.foundation/

I also put it under the resources menu. Let me know if we want it anywhere else. We should write a blog about it after cdCon

**Comment by fdegir** [comment]
Thanks @zestyroxy! @tequilarista could we consider this issue as done?

**Comment by fdegir** [comment]
The Best Practices website is listed on the landing page of the CDF website. Closing the issue.
