### ISSUE TITLE
Member & Project Pages Broken

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#384]
The Landscape iframe is broken -- working with the LF through Asana to fix it.

CNCF and OpenSSF pages seem fine, but their code doesn't work on ours (OpenSSF code used to work, it's the one I copied to fix issue #77.

cc/ @caniszczyk in case you have insights

**Temporary fix:** png image of members and projects that link to the Landscape.
https://cd.foundation/members/
https://cd.foundation/projects/

**Comment by fdegir** [comment]
@zestyroxy I think this is working now. If so, can we close the issue please?

**Comment by zestyroxy** [comment]
yes, fixed by the LF webteam
