### ISSUE TITLE
Including CDF Google Calendar on CDF Website

### ISSUE THREAD

**Issue by fdegir** [cdfoundation/foundation#385]
Could the link to [CDF Community Calendar in UTC](https://calendar.google.com/calendar/embed?src=linuxfoundation.org_mhf0kmgedn67ihni8r129avp24%40group.calendar.google.com&ctz=UTC) be included on CDF Website, perhaps under Community Dropdown list and/or Community webpage?

**Comment by zestyroxy** [comment]
Added to both, let me know if you want the wording to be different

https://cd.foundation/community/

**Comment by fdegir** [comment]
The calendar is linked to the CDF website so closing the issue.
