### ISSUE TITLE
Call a vote this week (9/22/19) for agreement on 9 strategic goals for 2019/2020

### ISSUE THREAD

**Issue by kimsterv** [cdfoundation/foundation#39]
Slide 2 - https://docs.google.com/presentation/d/1zj7rq2qu5modhkeeaI_A6uxMNgS-e0izEn-3UoRrZUM/edit?ts=5d6fd92e#slide=id.g418a8f92d3_0_0

**Comment by danlopez00** [comment]
1. Drive continuous delivery adoption
2. Cultivate growth & adoption of projects
3. Foster Tool Interoperability
4. Champion diversity & inclusion in our communities
5. Foster community relations
6. Grow the membership base
7. Create value for all members
8. Promote security as a first class citizen
9. Expand into emerging technology areas

**Comment by danlopez00** [comment]
This should be done via Groups.io vote (+1, -1, 0) to the GB list

**Comment by jsalinas29** [comment]
[CD.Foundation_strategic_goals_email_v1-9.26.docx](https://github.com/cdfoundation/foundation/files/3658293/CD.Foundation_strategic_goals_email_v1-9.26.docx)

@danlopez00 - here is the draft of the email. Please review and update so we can send out to the board for the vote. Thanks!

**Comment by danlopez00** [comment]
Great. lets come up with a plan to get the vote out next week

**Comment by jsalinas29** [comment]
[CD.Foundation_strategic_goals_email_v2-9.30.docx](https://github.com/cdfoundation/foundation/files/3672536/CD.Foundation_strategic_goals_email_v2-9.30.docx)

**Comment by caniszczyk** [comment]
can we do this in a gdoc so it's easier to comment?

**Comment by danlopez00** [comment]
moving it now. standby

**Comment by danlopez00** [comment]
Voting inititiated
