### ISSUE TITLE
Add Jenkins X office hours to the CDF public calender

### ISSUE THREAD

**Issue by ankitm123** [cdfoundation/foundation#395]
Is it possible to add the Jenkins X office hours to the CDF public calender?
This might result in more awareness around Jenkins X as a project (We have the office hours in the Jenkins X public calender, but the CD Foundation public calender is more well known)

Details:
* Zoom link: https://zoom.us/j/94376109791?pwd=OWswL3dvTUxSUW9VWkJmQXBTOHlCZz09
* We meet for office hours every other Tuesday at 15:00 UTC (for example, we have meeting on Tuesday July 5, 2022)

Source: https://jenkins-x.io/community/#office-hours

**Comment by fdegir** [comment]
As discussed on Slack, please attempt creating events on Bevy which should sync them to CDF Public Calendar.
Please let me know once you do that so we can check.

**Comment by fdegir** [comment]
@ankitm123 Can you please follow the instructions [here](https://github.com/cdfoundation/foundation/blob/master/Access%20to%20CDF%20Assets%20and%20Tools.md#edit-access-to-cdf-community-calendar) and open a ticket to get permissions to add Jenkins X meetings to the CDF Public Calendar?

**Comment by ankitm123** [comment]
Thanks, I opened a ticket.

**Comment by fdegir** [comment]
Closing this ticket since the ticket is now logged in the other system.
