### ISSUE TITLE
Add Pyrsia as incubating project to the CDF

### ISSUE THREAD

**Issue by oleg-nenashev** [cdfoundation/foundation#406]
The TOC voted for adding Project Pyrsia to the CDF in the incubating status. We kindly ask the CDF staff to add the project to the website, and to organize the rest of the logistics: announcements, public calendar, trademark and domain transfer, etc., etc.

* Project proposal: https://github.com/cdfoundation/toc/pull/149
* Voting thread: https://lists.cd.foundation/g/cdf-toc/topic/92507314

## Checklist for CDF

See the onboarding list [here](https://github.com/cdfoundation/toc/blob/master/process/new_project_onboarding.md)

- [x] Add the project to the CDF website
- [x] Add the project to the [CDF Landscape](https://github.com/cdfoundation/cdf-landscape) for better visibility
- [x] Add community meetings to the CDF Public calendar
- [x] Recommended: Delegate a representative to the Continuous Delivery Foundation that would participate in the CDF TOC mailing list and other foundation events
- [x] Prepare the public announcement

## Checklist for the project

- [x] Projects must list their status prominently on their website/README
- [x] Identify key messaging and community members to provide quotes and email [pr@cd.foundation](mailto:pr@cd.foundation)
- [x] Code of Conduct - The project should introduce an inclusive code of conduct if it does not already exist. It is recommended to adopt [Contributor Covenant](https://www.contributor-covenant.org/) and document the Continuous Delivery Foundation as the escalation level next to the project
- [x] Code of Conduct - The project should introduce an inclusive code of conduct if it does not already exist.
- [ ] Domain Transfer - project-related domains should be transferred to the Linus Foundation via an issue created here https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/group/19
- [ ] Github Repos - project-related repositories must be located in a neutral LF Github organization. The current GitHub organization owner must invite the user "thelinuxfoundation" (no quotes) as an owner. GitHub’s documentation for how to do that is here: https://docs.github.com/en/organizations/managing-organization-settings/transferring-organization-ownership
- [x] Zoom account - projects may request a zoom sub-account for scheduling community meetings. Please submit a ticket to CDF Helpdesk, identifying key community members who should have access.
- [ ] Other communication channels - Ideally we expect all communication channels (e.g. Slack, Mailing Lists, etc.) to be transferred to the CDF/Linux Foundation. Please coordinate the list with the stakeholders from the foundation.
- [x] Any registered marks for the project must be transferred to the Linux Foundation.
- [ ] Recommended: the project should establish the open source license scanning for the project.
- [ ] Recommended: Podcast - projects are welcome to do a kickoff episode on The Pipeline Podcast, more detail here: https://cd.foundation/podcast/

**Comment by fdegir** [comment]
Thanks for submitting the issue @oleg-nenashev.
We will come back with a list of items we need to work on.

**Comment by oleg-nenashev** [comment]
Any updates @fdegir ? The website and the resources have not been updated yet.
IIUC @betarelease is a contact point / coordinator from the project side

**Comment by fdegir** [comment]
We received the required information from the Pyrsia Team on Friday and @micmarti85 submitted a ticket on LF side a few minutes ago to get the project formation process started. We will work with transfer of certain items such as trademark once the project is added to corresponding LF systems.

We're communicating with @LoriLorusso, @betarelease and @sbtaylor15 as we work on this and will provide additional updates as we progress.

Additionally and if I remember correctly from the TOC meeting last Tuesday, August 16th, @sbtaylor15 mentioned that the domain name was either transferred already or it was kicked off. @sbtaylor15 can you please provide updates on that?

**Comment by fdegir** [comment]
Another update - we received information and documents from the LF Legal (draft technical charter, project contribution agreement and series agreement) and passed it to @LoriLorusso, @betarelease and @sbtaylor15 for review/signatures.

Will get back with more updates as soon as we have them.

**Comment by fdegir** [comment]
More updates regarding onboarding Pyrsia to the CDF.

* Legal Onboarding is nearly completed and we expect it to be finalized before CD Summit on October 25.
* Charter for the technical community is shared with the community.
* Community added their meetings to CDF Public Calendar and created channels on CDF Slack.
* Work is ongoing with marketing and press release with target being the CD Summit on October 25.
* Project maintainers are scheduled to take part in the new series created in collaboration with Techstrong TV.

Will provide more updates until the work is completed.

**Comment by fdegir** [comment]
Pyrsia legal onboarding is completed as well and we are working on announcement which is planned to be made on October 25th.

We will update the CDF website and landscape to list the project which will be done on October 25th so we can keep this issue open until after we conclude everything.

**Comment by fdegir** [comment]
Here are final updates from CDF based on the work we did over the last couple of weeks.

### Checklist for CDF

* **Add the project to the CDF website:** Pyrsia is on [the CDF Website](https://cd.foundation/projects/) now.
* **Add the project to the [CDF Landscape](https://github.com/cdfoundation/cdf-landscape) for better visibility:** Project is added to the landscape under the Library Management category with possibility of reevaluating the category it is currently placed under in future.
* **Add community meetings to the CDF Public calendar:** The community meetings are on [the CDF Public Calendar](https://calendar.google.com/calendar/u/0/embed?src=linuxfoundation.org_mhf0kmgedn67ihni8r129avp24@group.calendar.google.com&ctz=America/Los_Angeles).
* **Recommended: Delegate a representative to the Continuous Delivery Foundation that would participate in the CDF TOC mailing list and other foundation events.** Could you @betarelease please confirm the project representative?
* **Prepare the public announcement: ** [Announcement](https://www.prnewswire.com/news-releases/cd-foundation-welcomes-new-software-supply-chain-security-project-pyrsia-announces-tekton-graduation-and-cdevents-release-301658458.html) was made on October 25th.

### Checklist for the project

I marked some of the items in the checklist as complete as well based on the work we have been doing.
Could you @betarelease please review them and provide updates for the ones that are pending.

**Comment by afrittoli** [comment]
@betarelease @fdegir @oleg-nenashev is anything missing here before we can close this issue?

**Comment by fdegir** [comment]
@afrittoli I see @betarelease listed the pending items as completed so this issue can be closed.
