### ISSUE TITLE
Add access to CDF calendar for Pyrsia contributors 

### ISSUE THREAD

**Issue by sbtaylor15** [cdfoundation/foundation#408]
Please add access for steve@deployhub.com and sudhindrar@jfrog.com to create Pyrsia events on CDF Calendar.

**Comment by micmarti85** [comment]
@sbtaylor15 I've added you both tot he CDF Google calendar. Please email me @ mmartineau@linuxfoundation.org if you have not receive your invite.

**Comment by fdegir** [comment]
thanks for the help @micmarti85. closing the issue.
