### ISSUE TITLE
Change all cdfoundation repository default branches to main

### ISSUE THREAD

**Issue by bradmccoydev** [cdfoundation/foundation#409]
Most of the Repositories in the cdfoundation org are still set to master, including this one.  We should therefore change all of these to main, and make sure the org default branch for new repositories is set to main.

I'm happy to do this work if required.

**Comment by fdegir** [comment]
Thanks for highlighting this @bradmccoydev.
I think this is a good idea but it may have impacts on some other places such as HackMD which needs to be checked.

Additionally, I am wondering if you could bring the topic up to TOC as well?
The next meeting is on August 16th at 16:00 UTC. If the time of the meeting is too late for you, I can add the topic to the agenda and ask feedback from the TOC.

/cc @oleg-nenashev

**Comment by bradmccoydev** [comment]
Hi @fdegir yes, I'm happy to bring it up at TOC if there is time!

**Comment by MarckK** [comment]
[CD Lanscape repo](https://github.com/cdfoundation/cdf-landscape) default branch changed to **main**.

**Comment by MarckK** [comment]
[Foundation repo](https://github.com/cdfoundation/foundation) default branch has been changed to **main**.  ✅

**Comment by MarckK** [comment]
[TOC ](https://github.com/cdfoundation/toc/branches)default branch has been changed to **main**.  ✅

**Comment by MarckK** [comment]
[CDF Presentations](https://github.com/cdfoundation/presentations) default branch has been changed to **main**.  ✅

**Comment by MarckK** [comment]
[SIG Interoperability](https://github.com/cdfoundation/sig-interoperability) default branch has been changed to **main**.  ✅ 

This is the first SIG repo whose default branch we have renamed. Consequently, we will wait a few days/week and see if any issues arise with Hackmd, etc, and fix accordingly.

Then we can work with the other SIGs to update their default branches.

**Comment by MarckK** [comment]
[CDF Charter](https://github.com/cdfoundation/charter) default branch has been changed to **main**.  ✅

**Comment by MarckK** [comment]
[CDF SoC](https://github.com/cdfoundation/soc) default branch has been changed to **main**.  ✅ 

[CDF Newsletter](https://github.com/cdfoundation/newsletter) default branch has been changed to **main**.  ✅ 

[CDF faq](https://github.com/cdfoundation/faq) default branch has been changed to **main**.  ✅

**Comment by bradmccoydev** [comment]
Thanks @MarckK I made a script to look for the last ones and there are 7 left

| Name | URL |
| ---- | --- |
| cdfoundation/cla | https://github.com/cdfoundation/cla |
| cdfoundation/sig-security | https://github.com/cdfoundation/sig-security |
| cdfoundation/surveys | https://github.com/cdfoundation/surveys |
| cdfoundation/sig-security-sbom | https://github.com/cdfoundation/sig-security-sbom |
| cdfoundation/sig-security-supply-chain | https://github.com/cdfoundation/sig-security-supply-chain |
| cdfoundation/cluster | https://github.com/cdfoundation/cluster |
| cdfoundation/tekton-helm-chart | https://github.com/cdfoundation/tekton-helm-chart |

**Comment by MarckK** [comment]
Awesome! Thank you, @bradmccoydev! 

The Interoperability SIG has had no issues (with HackMD, etc) with the switch to naming default branch main, so we are good to change the default branch names on these last 7 repos. 👍

**Comment by MarckK** [comment]
Hi Brad, I believe cdfoundation/tekton-helm-chart is the last repo left to change the default branch name.
I've opened an issue on the repo. 👍

**Comment by bradmccoydev** [comment]
Thanks for your help!!, I will close this issue. I also changed all Ortelius repos to use the default branch main.

**Comment by MarckK** [comment]
Thank you for raising this issue! And thank you very much for changing all Ortelius repos' default branch to main. 
🙌
