### ISSUE TITLE
define a marketing roadmap and strategy

### ISSUE THREAD

**Issue by danlopez00** [cdfoundation/foundation#41]
Outreach Committee to define a marketing roadmap and strategy, and she and Maria will work on this and bring back to team with recommendations.

**Comment by timfong888** [comment]
What is actionable on this?  Jim and I are working on projects to write copy, and this should all flow from a core messaging document which I am starting to do.

We should probably have internal LF review and then have content reviewed/edited/contributed to in a messaging format.  This will inform things like our membership nurture, our website copy, and what the editorial calendar is.

**Comment by danlopez00** [comment]
This ticket is not actionable and will be closed in favor of specifics related to Outreach activities moving fwd.
