### ISSUE TITLE
Pyrsia - create slack channels for the community on CDF slack instance

### ISSUE THREAD

**Issue by betarelease** [cdfoundation/foundation#410]
We would like the following slack channels to be created on the CDF Slack instance/organization

#pyrsia - channel for all community interactions (easy for community to engage and ask questions)
#pyrsia-team - channel to interact with the team (more noise here from the team)
#pyrsia-notifications - channel to integrate with github notifications

All the above are `public` channels

**Comment by betarelease** [comment]
I was able to create the following channels on the CDF slack

#pyrsia 
#pyrsia-team
#pyrsia-notifications

**Comment by fdegir** [comment]
@betarelease thanks for creating those channels. Closing the issue.
