### ISSUE TITLE
Jenkins X needs access to the google search console

### ISSUE THREAD

**Issue by babadofar** [cdfoundation/foundation#411]
To get access to the [google search console](https://search.google.com/search-console/welcome?utm_source=about-page) , we need to add a TXT record to the DNS records for jenkins-x.io
with these contents 
```
google-site-verification=wzIXGdIwM0BEdKbUx8XFXghALlHGqgHCR6mFnKwB7ms
```
If somebody with access to DNS could add this it would be very helpful

**Comment by fdegir** [comment]
@babadofar a ticket has been logged to LF web team. Will get back to you once I hear back.

**Comment by babadofar** [comment]
Yes we have access now. Thanks
