### ISSUE TITLE
HackMD sub account for Jenkins X

### ISSUE THREAD

**Issue by ankitm123** [cdfoundation/foundation#425]
We use [google docs](https://docs.google.com/document/d/1gQIIVYboInUTpb2v5ZxC80suBPJ6T2Z18Ba1EL7YPOI/edit#heading=h.q4io1hnuzkfp) for keeping track of our office hour meeting notes and other meeting notes. It would be great to have a hackMD account for Jenkins X.

**Comment by fdegir** [comment]
@ankitm123 there are two ways this can be done.

* The CDF SIGs use CDF account on HackMD and Jenkins X maintainers could be added as admins to the CDF Team there, creating/managing Jenkins X documents. The notes could be displayed together with the others on [this page](https://hackmd.io/@cdfoundation/Sy6QIeu3c/https%3A%2F%2Fhackmd.io%2FVyFUVh7hS_WLHnuRVoz5Tw). I can help you with that.
* Jenkins X could request an account from HackMD directly. The details on how to apply for a non profit sponsorship plan is documented [here](https://hackmd.io/c/tutorials/%2F%40docs%2FNPOplan). If you want to apply for this, the answer to the first question, Documentations that prove nonprofit status in your country, is as below and the rest can be provided by Jenkins X community.

> The CDF is a 501(c)(6) as a sub organization of the Linux Foundation, which is a 501(c)(6):
> https://en.wikipedia.org/wiki/Linux_Foundation#CD_Foundation

**Comment by ankitm123** [comment]
First option would be better (cdf account). Is it possible to push the hackmd notes directly to jx community repository? I guess access needs to be added to the cdf hackmd account to push to the repo?

**Comment by fdegir** [comment]
Yes, you can configure which files should be pushed to which repo and branch on HackMD.

Please note that HackMD push doesn't work if branch protection rules are enabled in the repo for example for the main branch and they don't support that use case.
What we did in SIG Software Supply Chain is that we created a separate branch named [hackmd](https://github.com/cdfoundation/sig-software-supply-chain/tree/hackmd) which HackMD bot pushes. We then open a PR to main branch ourselves.

Could you please pass the HackMD usernames of the maintainers who will manage HackMD for Jenkins X Community so I add them to the team?

**Comment by ankitm123** [comment]
Thanks @fdegir. I gave the link to the other maintainers. Also moved all our office hour notes from google drive to hackMD. 
Closing this issue.
