### ISSUE TITLE
[Nominations Open] Continuous Enthusiast Award 2023 🏆

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#432]
This issue is to receive nominations for the Continuous Enthusiast Award 2023. 

This is the special award for the community contributors. When you think of the CDF community, this person should be on the shortlist, because they're everywhere!

To nominate someone, reply to this issue with the following:
1. Full name of the person you’re nominating
2. Short description of their contributions to the Continuous Delivery Foundation and why they should win.

**Nomination Deadline:** Friday, March 3, 2023

**Please note:** Last year's winner, Darin Pope, cannot win the award for Continuous Enthusiast again this year.

More details are [available here](https://github.com/cdfoundation/foundation/blob/main/CDF%20Awards%20Guidelines.md).

**Comment by bradmccoydev** [comment]
I would like to nominate [Lori Lorusso](https://github.com/LoriLorusso) for this award.

She has made a huge impact on the CD foundation this year with her efforts and passions in many aspects of the foundation from the Outreach committee, GB, TOC, cdCon committee, and many other places. And I confirm she is actually everywhere!

**Comment by afrittoli** [comment]
+1 for @LoriLorusso !

**Comment by zestyroxy** [comment]
Thank you everyone! Nominations are closed.
