### ISSUE TITLE
[Nominations Open] Top Doc(umenter) Award 2023 🏆

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#433]
This issue is to receive nominations for the Top Doc(umenter) Award 2023. 

This award recognizes excellence in documentation contributions to the CDF and its projects. Outstanding technical documentation is one of the best ways projects can lower the barrier to contribution.

To nominate someone, reply to this issue with the following:
1. Full name of the person you’re nominating
2. Short description of their contributions to the Continuous Delivery Foundation and why they should win.

**Nomination Deadline:** Friday, March 3, 2023

**Please note:** Last year's winner, Oleg Nenashev, cannot win the award for Top Doc(umenter) again this year.

More details are [available here](https://github.com/cdfoundation/foundation/blob/main/CDF%20Awards%20Guidelines.md).

**Comment by bradmccoydev** [comment]
I nominate [Terry Cox](https://github.com/tdcox) for his work and guidance around the cdevents project documentation and also other SIG's and CD Foundation projects.

**Comment by afrittoli** [comment]
+1 for @tdcox !

**Comment by zestyroxy** [comment]
Thank you everyone! Nominations are closed.
