### ISSUE TITLE
Logo request: Tekton Results

### ISSUE THREAD

**Issue by wlynch** [cdfoundation/foundation#440]
cc @adambkaplan (feel free to correct / add any additional details!)

### Project Objective

Tekton Results is a Tekton sub-project that aims to help users logically group CI/CD workload history and separate out long term result storage away from the Pipeline controller. This allows you to:

- Provide custom Result metadata about your CI/CD workflows not available in the Tekton TaskRun/PipelineRun CRDs (for example: post-run actions)
- Group related workloads together (e.g. bundle related TaskRuns and PipelineRuns into a single unit)
- Make long-term result history independent of the Pipeline CRD controller, letting you free up etcd resources for Run execution.
- Store logs produced by the TaskRuns/PipelineRuns so that completed Runs can be cleaned to save resources.

### How the logo would be used, where it will be placed 

Primarily on the repo (https://github.com/tektoncd/results) + any external materials (e.g. talks, blogs, etc).

### Logo ideas

Would like to stay on-theme with the other sub-project logos https://github.com/cdfoundation/artwork/tree/main/tekton/additional-artwork

- "Archives" - e.g. file cabinets, floppy disks, etc.

### Deadline / Timelines

None

**Comment by fdegir** [comment]
Thanks @wlynch.

We submitted an LF Design Request and will get back to you as soon as we get response to the request.

**Comment by adambkaplan** [comment]
I started a poll on the Results project to get direct community feedback: https://github.com/tektoncd/results/discussions/451

**Comment by adambkaplan** [comment]
@fdegir feedback from the community ([source](https://github.com/tektoncd/results/discussions/451)):

Concepts A and B combined had the plurality of votes. Consensus is that using "B" as the base (with the file icon in the background) with design elements from A could work. The "circuit board" design elements in B didn't resonate. For reference/inspiration, I used a ["cat in file cabinet"](https://www.flickr.com/photos/23408922@N07/6085972735) image in my cdCon presentation for Results, and that elicited positive reaction from the audience.

Concept E had a large number of votes, but many of the active contributors rejected it in subsequent working group meetings. Concepts C and D had the least votes.

**Comment by fdegir** [comment]
Thanks @adambkaplan. I passed the community feedback to our team and will get back to you under this issue as soon as I hear back.

**Comment by fdegir** [comment]
@wlynch @adambkaplan Our team updated the design based on community feedback. Could you please take a look at it in [this file](https://github.com/cdfoundation/foundation/files/11666927/TektonResults-LogoPresentation-v2.pdf) and let me know of your feedback?

**Comment by adambkaplan** [comment]
@fdegir apologies it's taken a while to get back - based on our discussion, this version feels too cluttered an can be simplified. We suggested the following:

* The "folder" can be made smaller so only the top is visible.
* The two extra lines near the cat's neck can be removed.
* Padding around the cat's face doesn't appear to be consistent (especially around the ears).
* Remaining icons can be adjusted (and/or removed) to achieve a balanced look and feel.

See also https://github.com/tektoncd/results/discussions/451#discussioncomment-6191062

**Comment by fdegir** [comment]
Thanks @adambkaplan! I passed the feedback to our team and get back to you once I hear back.

**Comment by fdegir** [comment]
@adambkaplan Please find the new concept attached and let me know of the feedback from the community.

[TektonResults-LogoConcepts-v3.pdf](https://github.com/cdfoundation/foundation/files/12249701/TektonResults-LogoConcepts-v3.pdf)

**Comment by adambkaplan** [comment]
@fdegir apologies for the delay on this, it was on my queue and slipped through the cracks.

:+1: on v3 of the logo! https://github.com/tektoncd/results/discussions/451#discussioncomment-6627199

**Comment by fdegir** [comment]
@adambkaplan @wlynch Sent the Tekton Result logos based on v3 via a pull request to [artwork](https://github.com/cdfoundation/artwork) repo. Could you please take a look?
