### ISSUE TITLE
Switch from LastPass to 1Password in docs

### ISSUE THREAD

**Issue by afrittoli** [cdfoundation/foundation#448]
The [Assets and Tools](https://github.com/cdfoundation/foundation/blob/main/CDF%20Assets%20and%20Tools.md) doc references LastPass instead of 1Password which is used today

**Comment by fdegir** [comment]
Thanks for reporting this @afrittoli.

@micmarti85 can we update the [Assets and Tools](https://github.com/cdfoundation/foundation/blob/main/CDF%20Assets%20and%20Tools.md) document with 1Password information please?

**Comment by micmarti85** [comment]
done!

MICHELLE MARTINEAU | PROGRAM MANAGER

***@***.***

<https://github.com/micmarti85>
<https://www.linkedin.com/in/michelle-martineau/>
