### ISSUE TITLE
[Nominations Open] Top Doc(umenter) Award 2024 🏆

### ISSUE THREAD

**Issue by roxannejoncas** [cdfoundation/foundation#453]
This issue is to receive nominations for the Top Doc(umenter) Award 2024.

This award recognizes excellence in documentation contributions to the CDF and its projects. Outstanding technical documentation is one of the best ways projects can lower the barrier to contribution.

➡️ Nominate someone, by replying to this issue with the following:

- Full name of the person you’re nominating
- Short description of their contributions to the Continuous Delivery Foundation and why they should win.

**Nomination Deadline:** Sunday, February 19, 2024 at 11:59 PST
**Please note:** Last year's winner, Terry Cox, cannot win the award for Top Doc(umenter) again this year.

- [CDF Award Guidelines](https://cd.foundation/cdf-community-awards-2024/)
- [2024 Awards Page](https://github.com/cdfoundation/foundation/blob/main/CDF%20Awards%20Guidelines.md) (where you can nominate someone for another award)

**Comment by TracyRagan** [comment]
I would like to nominate Ole Lensmar for this award. Ole worked on CDEvents for testing, which included both design and excellent documentation. He has also contributed blogs on the topic.

**Comment by tiffanyjachja** [comment]
I would like to nominate Vlad Silverman. Vlad is a Jenkin's documentation contributor. 

https://github.com/vsilverman

**Comment by MarkEWaite** [comment]
I nominate Kevin Martens (@kmartens27) as CDF top documentor.

Kevin is the [Jenkins documentation officer](https://www.jenkins.io/project/board/#documentation) and is a key contributor to [Jenkins documentation](https://github.com/jenkins-infra/jenkins.io/pulls?q=is%3Apr+author%3Akmartens27+is%3Aclosed).  He creates the [upgrade guide](https://www.jenkins.io/doc/upgrade-guide/) and the [changelog](https://www.jenkins.io/changelog-stable/) for the Jenkins long term support releases every 4 weeks.  He monitors, maintains, updates, and corrects the [weekly changelog](https://www.jenkins.io/changelog/).

Kevin is a skilled and capable reviewer of documentation pull requests.  He's been deeply involved as a [reviewer](https://github.com/Vandit1604/jenkins-docs/issues?q=is%3Aissue+is%3Aclosed+author%3Akmartens27) of the [versioned documentation project](https://github.com/Vandit1604/jenkins-docs) from Google Summer of Code 2023.  He regularly reviews and merges pull requests to the Jenkins documentation.

He hosts [weekly documentation office hours](https://community.jenkins.io/tag/sig-docs) and involves others in his efforts.  He is the lead author of contributor stories to the [Jenkins contributor spotlight](https://contributors.jenkins.io/).  He has published 5 contributor spotlights with many more in preparation for publication in 2024.

**Comment by zestyroxy** [comment]
⚠️ Nominations for this award are now closed. Thank you all for submitting your nominations. Voting will open on February 22.

The CDF Award voting is done by members of the TOC, Ambassadors, and Outreach Committee,who will receive an email with information on how to vote.

**Comment by roxannejoncas** [comment]
[Award Winners](https://github.com/cdfoundation/foundation/blob/main/CDF%20Awards%20Guidelines.md) were announced at cdCon 2024.
