### ISSUE TITLE
[Nominations Open] Continuous Enthusiast Award 2024 🏆

### ISSUE THREAD

**Issue by roxannejoncas** [cdfoundation/foundation#454]
This issue is to receive nominations for the Continuous Enthusiast Award 2024.

This is the special award for the community contributors. When you think of the CDF community, this person should be on the shortlist, because they're everywhere!

➡️ Nominate someone, by replying to this issue with the following:
- Full name of the person you’re nominating
- Short description of their contributions to the Continuous Delivery Foundation and why they should win

**Nomination Deadline:** Sunday, February 19, 2024 at 11:59 PST
**Please note:** Last year's winner, Lori Lorusso, cannot win the award for Continuous Enthusiast again this year.

- [CDF Award Guidelines](https://cd.foundation/cdf-community-awards-2024/)
- [2024 Awards Page](https://github.com/cdfoundation/foundation/blob/main/CDF%20Awards%20Guidelines.md) (where you can nominate someone for another award)

**Comment by yada** [comment]
Hi,
Thanks for this initiative, I'm happy to nominate V SREENIVAS:
https://github.com/cnu1812/cnu1812
For his expertise in Continuous Delivery Foundation (CDF) and strong involvement. He's the first person I think of when it comes to CDF and his contributions to open source are truly impressive.

**Comment by LoriLorusso** [comment]
I am nominating Andrea Frittoli for the CDF Enthusiast Award. Over the last year he has met with so mutiple companies, given so many talks, and has been an amazing advocate on behalf of the CDF as TOC Chair, and advocate and maintainer for CDEvents and Tekton. He is always positive and his passion for the CDF and the projects he works on is inspiring!

**Comment by jerdog** [comment]
I am nominating Lori Lorusso for the CDF Enthusiast Award. Lori tirelessly gives of herself to go above and beyond in serving the CDF in whatever way possible. She's a fantastic advocate for the CDF, and all things continuous delivery, and is a great and positive presence in the community.

**Comment by dsanyika** [comment]
I am nominating Benjamin Powell for CDF Enthusiast Award. Ben has dedicated himself to the CDEvents project while maintaining a level of excellence for his Spinnaker project work. He has committed to help new comers to the projects collaborating on Ticketing and Approvals for CDEvents as well as reviewing and collaborating on the work to make Spinnaker CDEvents ready.

**Comment by zestyroxy** [comment]
> I am nominating Lori Lorusso for the CDF Enthusiast Award. Lori tirelessly gives of herself to go above and beyond in serving the CDF in whatever way possible. She's a fantastic advocate for the CDF, and all things continuous delivery, and is a great and positive presence in the community.

Although very true @jerdog -- Lori won last year and cannot win again this year

**Comment by zestyroxy** [comment]
I'd like to nominate Alyssa Tong (@alyssat) who has been attending the Outreach Meetings for years and helps drives important initiatives like GSoC for Jenkins while also taking the time to share that knowledge with the rest of the CDF community.

**Comment by bajpaigarima1** [comment]
I would like to nominate Thomas Schuetz (WhizUs) for this work in the K8sGPT, leading the workshops and also spreading the word about CDF through his numerous talks, blogs and being a bridge between CNCF and CDF ambassador. We highly regard the work, knowledge and experience he brings for the ambassadors.

**Comment by zestyroxy** [comment]
I would like to nominate @jerdog Jeremy Meiss who has been involved in our events in many ways over the years and supported various CDF initiatives (big and small).

**Comment by zestyroxy** [comment]
⚠️ Nominations for this award are now closed. Thank you all for submitting your nominations. 

Voting will open on February 22.

The CDF Award voting is done by members of the TOC, Ambassadors, and Outreach Committee,who will receive an email with information on how to vote.

**Comment by roxannejoncas** [comment]
[Award Winners](https://github.com/cdfoundation/foundation/blob/main/CDF%20Awards%20Guidelines.md) were announced at cdCon 2024.
