### ISSUE TITLE
[Nominations Open] Top CDF Ambassador Award 2024 🏆

### ISSUE THREAD

**Issue by roxannejoncas** [cdfoundation/foundation#455]
This issue is to receive nominations for the Top CDF Ambassador Award 2024.

This award recognizes a champion for the continuous delivery space. This individual helps spread awareness of the CDF and its projects. The CDF Ambassador is a part of the [active Ambassador cohort](https://cd.foundation/ambassadors/) and leverages multiple platforms, both online as well as speaking engagements, driving interest and excitement around the ecosystem.

➡️ Nominate someone, by replying to this issue with the following:
- Full name of the person you’re nominating
- Short description of their contributions to the Continuous Delivery Foundation and why they should win.

**Nomination Deadline:** Sunday, February 19, 2024 at 11:59 PST
**Please note:** Last year's winner, Saim Safdar, cannot win the award for Top Ambassador again this year.

- [CDF Award Guidelines](https://cd.foundation/cdf-community-awards-2024/)
- [2024 Awards Page](https://github.com/cdfoundation/foundation/blob/main/CDF%20Awards%20Guidelines.md) (where you can nominate someone for another award)

**Comment by LoriLorusso** [comment]
I am nominating Andrea Frittoli for the CDF Ambassador Award. Over the last year he has met with so mutiple companies, given so many talks, and has been an amazing advocate on behalf of the CDF as TOC Chair, and advocate and maintainer for CDEvents and Tekton. He is always positive and his passion for the CDF and the projects he works on is inspiring!

**Comment by LoriLorusso** [comment]
I am happy to nominate Anna Daughtry from Ospera. In addtion to her work within her corporate work in the DevOps space, Anna  speakes at conferences and I was delighted by her session at the CDF Mini Summit in Spain. She consistently spreads information regarding the CDF and community on her soical properties, she is the chair of the cdCon 24 program commitee and is a great example of what it means to be a CDF Ambassador.

**Comment by jerdog** [comment]
I am nominating Lori Lorusso for the CDF Ambassador Award. Lori is a fantastic advocate for the CDF, and all things continuous delivery, and is a great and positive presence in the community. The time she devotes out of all other things she's involved in to make sure the community is informed and knows what is happening is immensely valuable to the CDF.

**Comment by cnu1812** [comment]
I would like to nominate @bradmccoydev for the top ambassador award!

**Comment by bajpaigarima1** [comment]
I would like to nominate Safeer C.M. - he has contributed actively during the year to bring new ideas to the ambassador group, collaborated in training material and blog writing. 

He has also delivered sessions in the local SRE community to spread awareness about CD Foundation

**Comment by bajpaigarima1** [comment]
I would like to nominate Paweł Piwosz (space lift) for his excellent contribution in the Continuous Delivery space as an ambassador, bringing new ideas, spreading awareness about difficult topics like open source licensing in IaC space. He was also nominated for his best podcast series at Devops dozen. We highly regard his contributions.

**Comment by bajpaigarima1** [comment]
I would like to nominate Thomas Schuetz (WhizUs) for this work in the K8sGPT, leading the workshops and also spreading the word about CDF through his numerous talks, blogs and being a bridge between CNCF and CDF ambassador.  We highly regard the work, knowledge and experience he brings for the ambassadors.

**Comment by bajpaigarima1** [comment]
I would like to nominate Muktesh Mishra, he is working in the observability driven development and we had engaging discussions with him on  various topics, he is active contributor in CdCon, his talk is one of the selected talks for this years open source summit.

**Comment by zestyroxy** [comment]
I would like to nominate Giorgi Keratishvili  @Galphaa who was an active member of the cdCon 2024 program committee and volunteered to help with other initiatives over the last year.

**Comment by zestyroxy** [comment]
> I would like to nominate Paweł Piwosz (space lift) for his excellent contribution in the Continuous Delivery space as an ambassador, bringing new ideas, spreading awareness about difficult topics like open source licensing in IaC space. He was also nominated for his best podcast series at Devops dozen. We highly regard his contributions.

Yes, and he contributed articles to the cd.foundation blog

**Comment by zestyroxy** [comment]
I would like to nominate Natale Vinto @blues-man who spoke at CDF events, volunteered for other CDF initiatives, and represents the CDF in his talks outside of CDF events as well as in other ways (like writing about Tekton in the "GitOps Cookbook" he co-authored)

**Comment by Galphaa** [comment]
I would like to nominate @pawelpiwosz Paweł Piwosz  for his contribution and spreading knowladge via his podcast and involvement in community

**Comment by Galphaa** [comment]
I would like to nominate Garima Bajpai @bajpaigarima1   as he has been active persons contributing in creating learning materials and has been active on conferences by presenting CD foundation

**Comment by Galphaa** [comment]
I would like to nominate Anna Daughtry @ajdaughe for her contribution in cdCon 2024 Program Chair

**Comment by Galphaa** [comment]
I would like to say big thank you to Roxanne Joncas @zestyroxy for her proactive position and commitment to grow CDF community

**Comment by bajpaigarima1** [comment]
I would like to nominate Moise Kameni  for his contributions to the blog writing and contributions towards translation of best practice to French ( inception stages) . He has been advocating for CD foundation in French community and increasing the outreach of the initiatives.

**Comment by bajpaigarima1** [comment]
I would like to nominate Matheus Paes Pereira for his contribution in Latin America and spreading the word about CDF in Brazil. He has also written blogs and delivered talks, he is active in translating  CDF initiative in Portuguese

**Comment by zestyroxy** [comment]
Thank you @Galphaa - although I'm not part of the active ambassador cohort and therefore do not qualify :)

**Comment by zestyroxy** [comment]
⚠️ Thank you all for submitting your nominations. We are no longer accepting nominations. Voting will open on February 22.

**Comment by roxannejoncas** [comment]
[Award Winners](https://github.com/cdfoundation/foundation/blob/main/CDF%20Awards%20Guidelines.md) were announced at cdCon 2024.
