### ISSUE TITLE
[Nominations Open] Top CDF Contributor Award 2024 🏆

### ISSUE THREAD

**Issue by roxannejoncas** [cdfoundation/foundation#456]
This issue is to receive nominations for the Top CDF Contributor Award 2024.

This award recognizes excellence of technical contributions to the CDF and its projects. This individual commits key pieces to projects and, more importantly, contributes in a way that benefits the project neutrally as a whole.

➡️ Nominate someone, by replying to this issue with the following:
- Full name of the person you’re nominating
- Short description of their contributions to the Continuous Delivery Foundation and why they should win.

**Nomination Deadline:** Sunday, February 19, 2024 at 11:59 PST
**Please note:** Last year's winner, Steve Taylor, cannot win the award for Top Contributor again this year.

- [CDF Award Guidelines](https://cd.foundation/cdf-community-awards-2024/)
- [2024 Awards Page](https://github.com/cdfoundation/foundation/blob/main/CDF%20Awards%20Guidelines.md) (where you can nominate someone for another award)

**Comment by e-backmark-ericsson** [comment]
I nominate Andrea Frittoli for the CDF Top Contributor Award

Andrea has contributed a lot to CDF as part of the Tekton and CDEvents communities, but also as a TOC chair. He has also been a frequent speaker at events and been active promoting the CDF projects in related projects such as Harbor, Argo CD and Open Telemetry, to mention a few.

**Comment by cnu1812** [comment]
I would like to nominate **Adam Kaplan** for this award. He has contributed a lot towards the ShipWright and has been promoted the same in many big conferences. So, I feel he deserves it.

**Comment by TracyRagan** [comment]
I would like to nominate Utkarsh Sharma for this award. Utkarsh has been a committed contributor to the Oretlius project, in both code and outreach. He received our highest recognition badge this past December. He is a great technologist and an amazing mentor, working with some of your most inexperienced contributors and building our community one person at a time.

**Comment by afrittoli** [comment]
I would like to nominate [Emil Bäckmark](https://github.com/e-backmark-ericsson) for this award. 

Emil has been instrumental in the Events Special Interest Group and all aspects of the CDEvents project, from governance to working groups, sharing his great expertise to guide the development of the specification as well as advocating for the project. Emil also contributes to the Interoperability SIG and Technical Oversight Committee community.

**Comment by bajpaigarima1** [comment]
I would like to nominate Anna Daughtry from Ospera for her active contribution to the organizing committees and her work towards the outreach of CD Foundation

**Comment by zestyroxy** [comment]
> I would like to nominate Anna Daughtry from Ospera for her active contribution to the organizing committees and her work towards the outreach of CD Foundation. 

Thank you, @bajpaigarima1 but unfortunately this award is to recognize "excellence of technical contributions to the CDF and its projects. This individual commits key pieces to projects and, more importantly, contributes in a way that benefits the project neutrally as a whole."

**Comment by zestyroxy** [comment]
Melissa McKay @mjmckay also deserves this award. She leads the Interoperability SIG, is on the Technical Oversight Committee and wrote an analysis about the 2023 State of CD Report, among other things.

**Comment by zestyroxy** [comment]
⚠️ Nominations for this award are now closed. Thank you all for submitting your nominations. 

Voting will open on February 22.

The CDF Award voting is done by members of the TOC, Ambassadors, and Outreach Committee,who will receive an email with information on how to vote.

**Comment by roxannejoncas** [comment]
[Award Winners](https://github.com/cdfoundation/foundation/blob/main/CDF%20Awards%20Guidelines.md) were announced at cdCon 2024.
