### ISSUE TITLE
CDF TOC Project Representatives 2024 Election process begins September 11, 2024 and ends on October 15, 2024

### ISSUE THREAD

**Issue by micmarti85** [cdfoundation/foundation#457]
Hi CDF Community,

**The CDF TOC Project Representatives 2024 Election process begins September 11, 2024 and ends on October 15, 2024.** 

4 of the 9 CDF TOC seats are elected from CDF Project representatives per charter. With Alan dong stepping down and Steve Taylor being elected as the End User Representative we have two seats up for election. Each CDF Project may nominate a maximum of one project representative to run for these seats. 

With representatives from Jenkins and Tekton already represented

- Andrea Frittoli, Open Source Advocate, IBM, Tekton
- Mark Waite, Manager, CloudBees, Jenkins

Screwdriver, Spinnaker, JenkinsX, Ortelius, and cdevents are the only projects eligible to assign representation.

Please make sure you check with the people you are nominating before you nominate the person. The assumption is that they have accepted their nomination from the project.

**Required information for nominations: (Anyone in the CDF community can nominate)**
Name of the Candidate
Project which the Candidate is Nominated By
Candidate Title
Candidate Affiliation
Candidate Bio
Nomination Statement

**Eligible Voters**
Eligible voter list was determined using the data from LFX Insights so it is important to update your LFX profile and associate your GitHub handle with your preferred email address. Please share this [eligible voter list](https://github.com/cdfoundation/toc/blob/main/elections/2024/Voters.md) with your communities to ensure we don't miss contributors who should be considered eligible and if someone is missing from this list please add them using the [voter registration form](https://docs.google.com/forms/d/e/1FAIpQLSdsxCadKwauQ4EHjaNihGtVQJQ027ECsXBZACU7WqXm4dBMCw/viewform) Voter Registration ends September 30th, if you are on the eligible voter list you do not need to register, only eligible contributors not represented on the voter list will need to register. 

Timeline:
Nomination Period: September 11- September 30 
Voting Period October 1- October 14
Winner announced October 15

**Comment by TracyRagan** [comment]
Self Nominating - Tracy Ragan
Ortelius
CEO
DeployHub
Tracy is an expert in software supply chain management and pipeline DevOps practices with a hyper-focus on microservices and cloud-native architecture. She has served on the [OpenSSF](https://openssf.org/) Governing Board (2022-23) as a General Member Representative, the OpenSSF Governing Board Committee, and the [Continuous Delivery Foundation (CDF)](https://cd.foundation/) Technology Oversite Committee. She previously served as a founding board member of the CDF and the Eclipse Foundation.  She is the Executive Director of the Ortelius Open Source project, an open-source security evidence store.

Nomination Statement
Building the CDF community will require visionary leadership to drive the future of DevOps. Key challenges the DevOps community must address include modernizing pipelines to integrate security and AI tooling, enhancing metrics and metadata collection, and automating workflows with tools like CDEvents. I have shown my commitment to these areas in the past. I hope to continue working in these areas in the coming critical years.

**Comment by jithine** [comment]
Nominating Vonny Jap @VonnyJap for Screwdriver

**Name of the Candidate**: Vonny Jap
**Project which the Candidate is Nominated By**: Screwdriver Open Source Project
**Candidate Title**: Senior Software Development Manager
**Candidate Affiliation**: Yahoo Inc.
**Candidate Bio**:
Vonny Jap is a Senior Software Development Manager at Yahoo Inc., currently overseeing and guiding the development of Screwdriver, an open-source continuous delivery platform. With a background in software engineering and team leadership, Vonny is focused on advancing the project's capabilities and ensuring its continued growth and adoption. They work closely with the community and internal teams to drive innovation, improve development workflows, and support contributors in building scalable, efficient CI/CD solutions.
**Nomination Statement**:
I am nominating Vonny Jap to serve on the CI/CD Committee because of their dedication to improving CI/CD practices through open-source contributions. Vonny has been instrumental in its ongoing development and refinement, providing strategic oversight and technical guidance. Their commitment to fostering collaboration and advancing the state of CI/CD makes them an excellent candidate to contribute to the committee’s efforts in shaping industry standards and best practices.

**Comment by link108** [comment]
Name of the Candidate: Jason McIntosh @jasonmcintosh
Project which the Candidate is Nominated By: Spinnaker
Candidate Title: Engineering Architect
Candidate Affiliation: Harness

Candidate Bio:

Jason McIntosh is a highly skilled architect with extensive experience in both development and operations. With a deep understanding of JVMs, systems analysis, and architecture, Jason has developed a reputation for his ability to identify and resolve complex technical issues. His expertise extends to security, where he leads efforts to improve the safety and resilience of systems. Jason is a strong advocate for open-source software, regularly sharing his knowledge through blog posts, social media, and public discussions. His broad technical knowledge, combined with his ability to engage with both high-level concepts and specific technical challenges, make him a valuable contributor to any project.


Nomination Statement:

Jason McIntosh has been a driving force in the Spinnaker open-source community. As the largest contributor to Spinnaker Slack, Jason actively engages with developers, answering questions, providing guidance, and fostering collaboration. His leadership extends to the Spinnaker Security Special Interest Group (SIG), where he has made significant contributions to securing the platform and mentoring others in best practices. Jason's dedication to promoting open-source software is evident not only in his technical contributions but also in his role as a mentor and guide within the community. He regularly shares his insights through public forums, encouraging broader participation in open-source projects. His blend of technical expertise, leadership, and commitment to the open-source ethos makes him an ideal candidate for the Continuous Delivery Foundation’s Technical Oversight Committee.
