### ISSUE TITLE
Add blog post on CD Summit agenda

### ISSUE THREAD

**Issue by tracymiranda** [cdfoundation/foundation#46]
From co-chairs perspective (mine & Christie)

https://docs.google.com/document/d/1ISietFKo72TqkJmUJpy2PgBmeFl8XZY9PmpgdlH7sp4/edit?ts=5d8df0f6#

**Comment by jcasman** [comment]
@tracymiranda - This is great, it scheduled to go out Mon, Sept 30, 8am PT (California time), under tmiranda in the Announcements section of the CD Foundation blog.

I added a few edits, just quickly noting here:
- Added a clear date (November 18) at the start of the article
- Added registration links at the top and bottom of the article, as well as where it was already linked to in the middle 
- Small fixes throughout

**Comment by danlopez00** [comment]
https://cd.foundation/announcement/2019/09/30/join-us-at-continuous-delivery-summit/
