### ISSUE TITLE
Create blog post, and media post google form and spreadsheet for content production management

### ISSUE THREAD

**Issue by danlopez00** [cdfoundation/foundation#51]
Create blog post, and media post google form and spreadsheet for content production management

**Comment by jsalinas29** [comment]
https://forms.gle/yEhsYw12uPMsyMmLA
- @danlopez00, when Jesse gets back I'd like for him to review the intake form to see if there is any missing fields or if we can make this more concise. I've linked the intake form to an excel sheet and as folks enter details it will populate in the excel sheet.

**Comment by danlopez00** [comment]
As ref: #53 We will also need to account for emails, campaigns etc to be created in a similar fashion
