### ISSUE TITLE
create new event submission form

### ISSUE THREAD

**Issue by danlopez00** [cdfoundation/foundation#55]
create new event submission form to be incorporated into main CDF events page

**Comment by jsalinas29** [comment]
https://forms.gle/euWdi9ZSYkFqRZEU7
i will just need to link this to the cd foundation webpage - please review and lmk if there's any additional info needed. Thx

**Comment by danlopez00** [comment]
convert to a gravity forms

**Comment by danlopez00** [comment]
move forms to wordpress and marketing cloud

**Comment by timfong888** [comment]
So this is now (given it is closed) in marketing Cloud?  @danlopez00 ?  What object in SFDC is creatd so we can report on it?
