### ISSUE TITLE
Create CDF member survey

### ISSUE THREAD

**Issue by caniszczyk** [cdfoundation/foundation#56]
poll members on satisfaction, desires etc for 2020

**Comment by danlopez00** [comment]
is there an exising CNCF or hyperledger survey of reference?

**Comment by caniszczyk** [comment]
we are slowly open sourcing all of our survey questions + data + results here, feel free to be inspired https://github.com/cncf/surveys

**Comment by caniszczyk** [comment]
This could be a great item for @jsalinas29 to kick off with SFDC or surveymonkey

**Comment by jsalinas29** [comment]
end user community survey draft - https://docs.google.com/document/d/13EX4hSzN9ZXstJiAswzYwaIbnPFnGAqkOA4Lhptp5H8/edit

maintainers survey draft - 
https://docs.google.com/document/d/1FLXn4DsjdjtCHZNAJn6CDTS8QK2IUDlpZ-hT26GrvJc/edit

**Comment by danlopez00** [comment]
https://forms.gle/MnYbtywhBKz884BU8  <-- in process

**Comment by danlopez00** [comment]
@jsalinas29 can you please update and close out as this survey went out to the community
