### ISSUE TITLE
Meetup - transition doc from JAMS to CDF 

### ISSUE THREAD

**Issue by jsalinas29** [cdfoundation/foundation#59]
- summary/announcement to the JAMs leaders about our transition request
- blog announcement (kk)
- active # of meetups
- dorment mtgs that we are shutting down
-  number of meetup willing to transition
- social media announcement
- meetup admin transition to Jacque

**Comment by jsalinas29** [comment]
- summary/announcement: https://docs.google.com/document/d/1_896BNktOZgKL2xj728RVvsXkUnNtG3g/edit?ts=5da4affe
- content survey for group organizers 
https://forms.gle/JLuPrwqzWTicmVvn
- jacque made admin
- next on the docket: blog announcement to be drafted by KK or Tracy M (?)
- 28 dormant accounts of 106
https://drive.google.com/file/d/1sXXe7R5zAKGrQpTKHY3T2RDCBnbSLd0P/view?usp=sharing 
https://drive.google.com/file/d/1qHL242GoaGAgQrbuFphwjBfSLrq1FmTX/view?usp=sharing 
- 22 dormant organizers 
https://drive.google.com/file/d/1pl6VA9MAPrzG04cOUIk9KUrL6L2QCMsV/view?usp=sharing
https://drive.google.com/file/d/121aVfyzpdvEmXnC3TfXfwDEq4ECvwgF7/view?usp=sharing
- email update sent to TM, TR, Max

**Comment by danlopez00** [comment]
Please post this content to the meetups repo: 

https://github.com/cdfoundation/meetups

**Comment by danlopez00** [comment]
See #89

**Comment by danlopez00** [comment]
Connect with Jenkins team regarding updating this page: https://jenkins.io/projects/jam/

**Comment by jsalinas29** [comment]
https://www.meetup.com/pro/cicd-cdf pro account rebrand complete
- @danlopez00 good catch. I will send a note to our Cloudbees counterpart to help update this page.
