### ISSUE TITLE
Webinar program

### ISSUE THREAD

**Issue by jsalinas29** [cdfoundation/foundation#60]
- replicate the ops model from cncf
- set up cal for members to sign up
- create an editorial cal of topics we want to discuss by month 
- lead gen emails
- social media cal to promote
- speakers

**Comment by danlopez00** [comment]
This is a great topic and of much interest. I believe Hyperledger does this well too. Updating list: 

- establish content, speakers, verticals, recording, and retention
- set up cal for members to sign up (some free, some paid, some member only)
- create an editorial cal of topics we want to discuss routine basis 
- lead gen, nurture, post-hoc survey emails
- social media cal to promote
- speakers to promote topics such as security, standards, specs, portability, conformance

**Comment by timfong888** [comment]
@jsalinas29 when you have recordings I have a platform that is building a community around webinars for open source projects.  Or we can use it for live webinars as well.  It's outside of LF.

**Comment by caniszczyk** [comment]
see this as an example: https://github.com/cncf/foundation/blob/master/webinar-guidelines.md

talk to Kim McMahon <kmcmahon@linuxfoundation.org> if you need help building a program

**Comment by danlopez00** [comment]
Yes, we have implemented a guidelines similar: https://github.com/cdfoundation/foundation/blob/master/webinars-guidelines.md

Will reach out to Kate!

**Comment by jsalinas29** [comment]
cdf webinar program guidelines: https://docs.google.com/document/d/1j4IPDelTb_3Jbb94EAavMr1YDV6-xPBGRLxIZbmtiIE/edit?usp=sharing

launching May/June
