### ISSUE TITLE
Create office hours and AMA

### ISSUE THREAD

**Issue by jsalinas29** [cdfoundation/foundation#61]
- office hrs infrastructure/strategy doc
- need zoom mtg and calendly ink
- establish cadence & support volunteers
- ask me anything board 
- zoom/webpage google form? 
- moderators

**Comment by danlopez00** [comment]
Please assign a calendar to the speaker bureau volunteers that want to participate. The first should be planned for San Diego.

**Comment by danlopez00** [comment]
closing this as we have supplanted with slack, webinar, ambassador progs
