### ISSUE TITLE
Monthly Podcast program 

### ISSUE THREAD

**Issue by jsalinas29** [cdfoundation/foundation#62]
- lay down foundation of program 
- editorial cal of topics for 1H of 2020
- securing speakers 
- cal 
- lead gen/promo emails

**Comment by danlopez00** [comment]
Spoke with other LF team members on how they do it. Its fairly simple and fairly cheap, and an effective way to build content. Using Zoom, you can have participants call in and record the meeting. Zoom can transcribe. The audio can be uploaded to a service or 2 for getting out to a wide audience when enough content is built up. 

Seems to be the next step would be to create the following:

- audio pre/post roll that announces CDF
- calendar of interviews, scheduling of a calendar with priority going to board, speaker b, members, then developer community

**Comment by jsalinas29** [comment]
program guidelines and strategy: https://docs.google.com/document/d/1XC0GUQdUSrtE-Q2DDQpBrc-4fCbmQWZXmpQlpitvQdo/edit?usp=sharing

First episode to launch in May
