### ISSUE TITLE
Podcast at CDF 

### ISSUE THREAD

**Issue by jsalinas29** [cdfoundation/foundation#63]
- mtg w/devops (deborah) on 9/9 to explore cost 
- ref https://github.com/cdfoundation/foundation/issues/62 (this would be our 1st podcast) 
- lead gen/promo emails 
- invite gb & members to participate (secure speakers)

**Comment by jsalinas29** [comment]
passing on this since the cost is $1500

**Comment by danlopez00** [comment]
What will cost $1500?

**Comment by jsalinas29** [comment]
Sorry, should have clarified and provided more detail. Tracy R suggested we investigate how to get a panel podcast through a direct publisher onsite.  After doing a call with them the cost for a direct publisher to facilitate the podcast onsite at Kubecon would cost $1500.

**Comment by danlopez00** [comment]
this is more broad than 1 event

**Comment by danlopez00** [comment]
dup of #62
