### ISSUE TITLE
Update: outreach committee mailing list w/marketing POCs

### ISSUE THREAD

**Issue by jsalinas29** [cdfoundation/foundation#64]

**Comment by danlopez00** [comment]
This is complete, as this is mostly contractual. However, the CDF routinely contacts our members to make sure they update their POCs. Let me know if you have any questions.

**Comment by danlopez00** [comment]
post GB meeting we will want to send out an email blast to the OC and make sure the marketing contact is accurate for member orgs. Suggest closing this and creating one that reflects and maintenance workflow
