### ISSUE TITLE
Build case study program for CDF projects

### ISSUE THREAD

**Issue by caniszczyk** [cdfoundation/foundation#76]
Do something like this: https://www.cncf.io/projects/case-studies/

**Comment by danlopez00** [comment]
Had meeting to discuss production, strategy around case studies

**Comment by danlopez00** [comment]
There is a follow up with a premier member team regarding content week of Nov 4

**Comment by jsalinas29** [comment]
https://docs.google.com/document/d/1wXDbjWXbuA_9yfeoIub0-GSKhvFOh81ih2-BhTSX3ME/edit?usp=sharing

Submission Form: https://cd.foundation/cdf-case-study-submission-form/
Share Drive:  https://drive.google.com/open?id=1BFPnNMVho6Xp6celnOy3mr6b4Nzg2-KY
Case Study Template: https://docs.google.com/document/d/1z8rGhPRYj1NK8s13FdEwDm0n3wTcnmGTw54uIvB2nSA/edit?usp=sharing 
CDF Case Study landing page: https://cd.foundation/case-studies/#community
CDF Project Archive landing page: https://cd.foundation/case-studies/jenkins-case-studies/
CDF Project Case Study landing page: https://cd.foundation/case-studies/spinnaker-case-studies/lookout-achieves-fedramp/
