### ISSUE TITLE
Embed CDF landscape into CDF members page

### ISSUE THREAD

**Issue by caniszczyk** [cdfoundation/foundation#77]
https://landscape.cd.foundation/format=card-mode&grouping=category&project=company

**Comment by caniszczyk** [comment]
make it look like this: https://foundation.graphql.org/members/

**Comment by caniszczyk** [comment]
@danlopez00 how's this going? shouldn't be super hard to do

**Comment by zestyroxy** [comment]
Correct link to embed: https://landscape.cd.foundation/card-mode?grouping=category&project=company&embed=yes&style=borderless 

I've tested this and it works, but to make it smooth, I will need a little help from LF Creative Services to do some JavaScript Magic like Graphql did: ([their raw code](https://github.com/graphql/graphql.github.io/blob/source/src/pages/foundation/members.tsx))

Main problem: When you click on a logo, the box with the member detail appears in the middle of the page.
Secondary problem: The height can't be set to 100%, probably needs a wordpress workaround, so I need to set a max height in pixels, which makes the page unresponsive to different screen sizes.

Here's the draft page: https://cd.foundation/members-new/

**Comment by zestyroxy** [comment]
LF Jira Issue link: https://jira.linuxfoundation.org/browse/WEB-604

**Comment by zestyroxy** [comment]
I believe I could fix it by copying OpenSSF's code: https://openssf.org/about/members/

Updated page: https://cd.foundation/members-new/

**Comment by tracymiranda** [comment]
This is now the new members page, thanks Roxanne!
