### ISSUE TITLE
Follow up with LF China Team

### ISSUE THREAD

**Issue by danlopez00** [cdfoundation/foundation#79]
Establish bi-weekly call
Goals
Events, meetups, members
localization (what to translate eg slide decks, github docs)
Wechat postings

**Comment by jsalinas29** [comment]
scheduled & updated invite to bi-wkly cadence

**Comment by danlopez00** [comment]
Kickoff agenda, map out details and due dates:

- Goals
- Events, meetups, members
- localization (what to translate eg slide decks, github docs)
- Wechat postings
