### ISSUE TITLE
Create a CDF Meetup event in South Bay with help from JFrog

### ISSUE THREAD

**Issue by danlopez00** [cdfoundation/foundation#80]
Work with JFrog team to stand up a meetup in South Bay as well as possibly in Israel

**Comment by jsalinas29** [comment]
- coordinated mtg w/israel team to plan events and execution 
- will connect w/southbay team to plan event

**Comment by jsalinas29** [comment]
- mtgs fell through b/c JFrog team is traveling

**Comment by danlopez00** [comment]
Closing due to COVID-19 concerns. Can revisit at a later date, or migrate into virtual event strategies
