### ISSUE TITLE
Write and review membership inquiry nurture

### ISSUE THREAD

**Issue by timfong888** [cdfoundation/foundation#85]
We are currently developing the nurture emails for membership inquiry:

https://docs.google.com/document/d/1jUV7IFXiwablcOEpdnVZT5wO0T861Vj4zixYPcqTYTk/edit?ts=5db88b58

I'm taking a pass at it -- but it needs to align with overall messaging (such as goals, benefits of membership, etc).

This is mostly FYI but we should align to understand this is what we're doing.

**Comment by fdegir** [comment]
We already have this so closing the issue.
