### ISSUE TITLE
draft code of conduct guidelines for CDF representation

### ISSUE THREAD

**Issue by kimsterv** [cdfoundation/foundation#9]

**Comment by danlopez00** [comment]
We have this for the TOC: https://github.com/cdfoundation/toc/blob/master/CODE_OF_CONDUCT.md

However, it seems more like guidelines for web, and content such as: https://github.com/cncf/foundation/blob/master/website-guidelines.md

**Comment by danlopez00** [comment]
CNCF also has this in their charter for the GB to manage:

https://github.com/cncf/foundation/blob/master/charter.md#5-governing-board

**Comment by tracymiranda** [comment]
Default file is https://github.com/cdfoundation/.github/blob/main/CODE_OF_CONDUCT.md
