### ISSUE TITLE
Update Jenkins page for JAM conversion to CDF Meetups

### ISSUE THREAD

**Issue by danlopez00** [cdfoundation/foundation#90]
Need this updated: https://jenkins.io/projects/jam/

Update Jenkins page for JAM conversion to CDF Meetups

**Comment by jsalinas29** [comment]
https://docs.google.com/document/d/1lLH0VanMgYwjm0tbip1ieIoiLs0dNsmsWkovGrfXDKQ/edit
- doc w/updated copy and connected w/Jenkins team to update.

**Comment by jsalinas29** [comment]
+alyssa - she has the copy and just needs to update the page

**Comment by jsalinas29** [comment]
Alyssa has submitted the copy changes & awaiting update confirmation.
