### ISSUE TITLE
Associate CDF billing accounts with Spinnaker GCP projects and AWS account

### ISSUE THREAD

**Issue by ttomsu** [cdfoundation/foundation#96]
We still need to close the loop on these for the Spinnaker OSS community.

**Comment by danlopez00** [comment]
@ttomsu Lets schedule time to finish setting this up. we also have a bit more infrastructure coming our way we should sync up on

**Comment by danlopez00** [comment]
@ttomsu can we connect on this topic this week?

**Comment by ttomsu** [comment]
Yep - just sent you a meeting invite.

**Comment by danlopez00** [comment]
Completed with @ttomsu !
