### ISSUE TITLE
Youtube link on website

### ISSUE THREAD

**Issue by TracyRagan** [cdfoundation/foundation#98]
We need to add a sub-menu link to our YouTube page, probably under news and events

https://www.youtube.com/channel/UC7HcWhSetq6nTlpMXPHKz_A/featured

**Comment by danlopez00** [comment]
The link is already in the icon at the top of the page using the Youtube icon: https://www.youtube.com/channel/UC7HcWhSetq6nTlpMXPHKz_A?disable_polymer=true

**Comment by danlopez00** [comment]
Closing for now as we have a Youtube link in icon form in nav
